--------------------------------------------------------
--  DDL for Index IDXACT0010
--------------------------------------------------------

  CREATE INDEX "SCACTUALIZADORVT"."IDXACT0010" ON "SCACTUALIZADORVT"."TAERROR_LOG" ("FIERR_CONS", "ORA_ERR_ROWID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TAERRORLOG_IDX" ;
