--------------------------------------------------------
--  DDL for Package PAACTUALIZA0002
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCACTUALIZADORVT"."PAACTUALIZA0002" AS
    PROCEDURE SPPROCESSDETAIL (
        PA_COUNTRY         SCACTUALIZADORVT.TATRNCRCB.FIPAISID%TYPE,
        PA_CHANNEL         SCACTUALIZADORVT.TATRNCRCB.FICANAL%TYPE,
        PA_BRANCH          SCACTUALIZADORVT.TATRNCRCB.FISUCURSAL%TYPE,
        PA_TRANSACTION     SCACTUALIZADORVT.TATRNCRCB.FITRANNO%TYPE,
        PA_TRN_TYPE        SCACTUALIZADORVT.TATRNCRCB.FITRANTIPO%TYPE,
        PA_CON_TYPE        SCACTUALIZADORVT.TATRNCRCB.FICONSECTIPO%TYPE,
        PA_DATE            SCACTUALIZADORVT.TATRNCRCB.FDTRANSFECHR%TYPE,
        PA_WS              SCACTUALIZADORVT.TATRNCRCB.FCTRANWS%TYPE,
        PA_USER            SCACTUALIZADORVT.TATRNCRCB.FCTRANUSR%TYPE,
        PA_FAULT           OUT INTEGER,
        PA_MESSAGE_FAULT   OUT VARCHAR2
    );

    PROCEDURE SPGETRECORDDETAIL (
        PA_COUNTRY   IN INTEGER,
        PA_CHANNEL   IN INTEGER,
        PA_RECORD    IN INTEGER,
        PA_ACTION    OUT INTEGER,
        PA_SP_NAME   OUT VARCHAR2
    );

    PROCEDURE SPGETSTRUCTUREDETAIL (
        PA_SPNAME      IN VARCHAR2,
        PA_STRUCTURE   OUT SCACTUALIZADORVT.ARR_ESTRUCTURA_TAEST,
        PA_LENGTH      OUT SCACTUALIZADORVT.TACATESTRUCTURA.FIEST_LENGTH%TYPE
    );

END PAACTUALIZA0002;

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."PAACTUALIZA0002" TO "SCSISGES";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."PAACTUALIZA0002" TO "SCVENTASTIENDA";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."PAACTUALIZA0002" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."PAACTUALIZA0002" TO "USRINFFENIX";
