--------------------------------------------------------
--  DDL for Type TYPTRANCRECAB
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TYPTRANCRECAB" AS OBJECT (
  FIPAISID     NUMBER(5),
  FICANAL      NUMBER(5),
  FISUCURSAL   NUMBER(10),
  FITRANNO     NUMBER(10),
  FITRANTIPO   NUMBER(5),
  FICONSECTIPO NUMBER(10),
  FDTRANSFECHR DATE,
  FCTRANWS     VARCHAR2(10 CHAR),
  FCTRANUSR    VARCHAR2(10 CHAR));

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANCRECAB" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANCRECAB" TO "USRINFFENIX";
