--------------------------------------------------------
--  DDL for Package PALOGCOLERR
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PALOGCOLERR" 
AS
   PROCEDURE SPSAVE (PA_PROCESS   IN SCSISGES.TALOGCOLERR.FCPROCESO%TYPE,
                     PA_COLERR    IN SCSISGES.TYTBLOG);

   PROCEDURE SPGET (
      PA_PROCESS        IN     SCSISGES.TALOGCOLERR.FCPROCESO%TYPE,
      PA_INITIAL_DATE   IN     SCSISGES.TALOGCOLERR.FDCREACION%TYPE,
      PA_FINAL_DATE     IN     SCSISGES.TALOGCOLERR.FDCREACION%TYPE,
      PA_DATOS             OUT SYS_REFCURSOR,
      PA_CODE              OUT INTEGER,
      PA_MESSAGE           OUT VARCHAR2,
      PA_DETAIL            OUT VARCHAR2);

   PROCEDURE SPPURGE (PA_CODE      OUT INTEGER,
                      PA_MESSAGE   OUT VARCHAR2,
                      PA_DETAIL    OUT VARCHAR2);
END PALOGCOLERR;

/

  GRANT EXECUTE ON "SCSISGES"."PALOGCOLERR" TO "USRSISGES";
