--------------------------------------------------------
--  DDL for Package PAREPORTES0001
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PAREPORTES0001" 
AS

    PROCEDURE SPSGESTIONES(
        PA_FECHAINICIO   IN  DATE,
        PA_FECHAFIN      IN  DATE,
        PA_GESTIONES     OUT SCSISGES.PATYPES.RCGCURSOR,
        PA_CODIGO        OUT NUMBER,
        PA_MENSAJE       OUT VARCHAR2,
        PA_MENSAJEERROR  OUT VARCHAR2
    );

    FUNCTION FNSUCEMPLEADO(
        PA_FIIDUSUARIO IN SCSISGES.TCUSUARIO.FIIDUSUARIO%TYPE  
    ) RETURN VARCHAR2;

    FUNCTION FNNOMBREEMPLEADO(
        PA_FIIDUSUARIO IN SCSISGES.TCUSUARIO.FIIDUSUARIO%TYPE  
    ) RETURN VARCHAR2;

    FUNCTION FNDESCTIPOGESTION(
        PA_FITIPOGESTIONID IN SCSISGES.TCTIPOGESTION.FITIPOGESTIONID%TYPE  
    ) RETURN VARCHAR2;

    FUNCTION FNDESCMEDIO(
        PA_FIMEDIOGESTIONID IN SCSISGES.TCMEDIOGESTION.FIMEDIOGESTIONID%TYPE  
    ) RETURN VARCHAR2;

    FUNCTION FNDESCRESULTADO(
        PA_FIRESULTGESTIONID IN SCSISGES.TCRESULTGESTION.FIRESULTGESTIONID%TYPE
    ) RETURN VARCHAR2;

    FUNCTION FNDESCEVENTO(
        PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE
    ) RETURN VARCHAR2;

    PROCEDURE SPSEVENTO(
        PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE,
        PA_FIUSUARIOID OUT SCSISGES.TAEVENTGEST.FIUSUARIOID%TYPE,
        PA_FIEVENTOID  OUT SCSISGES.TAEVENTGEST.FIEVENTOID%TYPE,
        PA_FICLIENTE   OUT SCSISGES.TAEVENTGEST.FICLIENTE%TYPE
    );

    FUNCTION FNFECHAEVENTO(
         PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE
    ) RETURN VARCHAR2;
END PAREPORTES0001;

/

  GRANT EXECUTE ON "SCSISGES"."PAREPORTES0001" TO "USRSISGES";
