--------------------------------------------------------
--  DDL for Package PQFXWFMIGRACIONPF
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PQFXWFMIGRACIONPF" IS

  -- Author  : 149766 - Arturo Lopez Patricio
  -- Created : 03/09/2018
  -- Purpose : stores para mapas de migracion de Productos Financieros a Sistemas Gestion Fenix


PROCEDURE SPFXTRUNCACAMPANAS;
PROCEDURE SPFXDEPURACAMP;
PROCEDURE SPFXTRUNCACARTERA;
PROCEDURE SPFXDEPURACART;
PROCEDURE SPFXTRUNCAUSU;
PROCEDURE SPFXDEPURAUSU;
PROCEDURE SPFXTRUNCACLIENTES;
PROCEDURE SPFXDEPURACTES;
PROCEDURE SPFXTRUNCAGEOBAZEKT;
PROCEDURE SPFXDEPURABAZEKT;
PROCEDURE SPREGISTRAFINPROC;
PROCEDURE SPFXTRUNCACAMPAMKT;
PROCEDURE SPREGISTRAFINCAMP ;
END PQFXWFMIGRACIONPF;

/

  GRANT EXECUTE ON "SCSISGES"."PQFXWFMIGRACIONPF" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."PQFXWFMIGRACIONPF" TO "USRINFSISGES";
