--------------------------------------------------------
--  DDL for Package PQFXCALENDARIOEKT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PQFXCALENDARIOEKT" IS

  -- Author  : 149766 - Arturo Lopez Patricio
  -- Created : 09/10/2018
  -- Purpose : stores para procesar calendario
/*FUNCION AUXILIAR PARA EXTRAER SOLO CALENDARIO CON SEMANAS PROCESADAS
 PARAMETROS:
          PA_FECHAINI: INDICAR LA FECHA DE INICIO, CONSIDERAR QUE EKT INICIA LUNES
          PA_FECHAFINAL: INDICAR CUALQUIER FECHA DEL ULTIMO MES DEL ANIO
          PA_ANIO: INDICAR EL ANIO DEL CUAL SE VA A CREAR EL CALENDARIO
          **** para las fechas manejar formato DD/MM/YYYY ***
          RETORNA:
               UNA COLECCION DE TODO EL ANIO INDICADO, QUE CONTIENE:
                *FCFECHA
                *FIANIO
                *FISEMANA
*/
FUNCTION FNCALPRELIMINAR(
  PA_FECHAINI VARCHAR2,
  PA_FECHAFINAL VARCHAR2,
  PA_ANIO NUMBER
  ) RETURN  SCSISGES.TYTBCALENDARIO;

/*GENERAR CALENDARIO DEL ANIO DESEADO
PARAMETROS:
  PA_FECHAINI: INDICAR LA FECHA DE INICIO, CONSIDERAR QUE EKT INICIA LUNES
  PA_FECHAFINAL: INDICAR CUALQUIER FECHA DEL ULTIMO MES DEL ANIO
  PA_ANIO: INDICAR EL ANIO DEL CUAL SE VA A CREAR EL CALENDARIO*/
PROCEDURE SPGENERACALEKT
  (
   PA_FECHAINI VARCHAR2,
   PA_FECHAFINAL VARCHAR2,
   PA_ANIO NUMBER
  ) ;
/*PROCESA LA ULTIMA SEMANA DEL ANIO PROCESADO EN CASO DE ESTAR INCOMPLETA,
 CADA SEMANA DEBE CONTENER 7 DIAS INICANDO DE LUNES A DOMINGO
 PARAMETROS:
      COLECCION DE CALENDARIO*/
PROCEDURE SPGENERACALFALTANTE
  (
   PA_CALPRELIMINAR SCSISGES.TYTBCALENDARIO
  ) ;
/*STORE CREADO PARA MANTENIMIENTO DE CALENDARIO*/
PROCEDURE SPDEPURACALENDARIO
(
          PA_OPCION NUMBER
         ,PA_ANIO NUMBER
         ,PA_SEMANA NUMBER
         ,PA_FECHA VARCHAR2
         ,PA_CURS         OUT SYS_REFCURSOR
) ;
PROCEDURE SPCONSULTACAL
(
 PA_ANIO NUMBER,
 PA_CURS         OUT SYS_REFCURSOR
) ;
END PQFXCALENDARIOEKT;

/

  GRANT EXECUTE ON "SCSISGES"."PQFXCALENDARIOEKT" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."PQFXCALENDARIOEKT" TO "USRINFSISGES";
  GRANT EXECUTE ON "SCSISGES"."PQFXCALENDARIOEKT" TO "USRSISGES";
