--------------------------------------------------------
--  DDL for Package PQSISGESALERTAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PQSISGESALERTAS" 
AS
   PROCEDURE SPGUARDARALERTA (
      pa_FIALERTAID     IN     SCSISGES.TAALERTA.FIALERTAID%TYPE,
      pa_FIUSUARIOID    IN     SCSISGES.TAALERTA.FIUSUARIOID%TYPE,
      pa_FCTITULO       IN     SCSISGES.TAALERTA.FCTITULO%TYPE,
      pa_FCALERTADESC   IN     SCSISGES.TAALERTA.FCALERTADESC%TYPE,
      pa_FDFECINICIAL   IN     SCSISGES.TAALERTA.FDFECINICIAL%TYPE,
      pa_FDFECTERMINO   IN     SCSISGES.TAALERTA.FDFECTERMINO%TYPE,
      pa_FICANALID      IN     SCSISGES.TAALERTA.FICANALID%TYPE,
      pa_GEOALERTA      IN     SCSISGES.TBGEOALERTA,
      PA_PERFILES       IN     SCSISGES.TYTPERFILALERTA,
      pa_CODIGO            OUT INTEGER,
      pa_MENSAJE           OUT VARCHAR2,
      pa_MENSAJEERROR      OUT VARCHAR2);

   PROCEDURE SPCONSULTALERTAS (
      PA_FIEMPNUM         IN     SCSISGES.TAGEOALERTA.FIEMPNUM%TYPE,
      PA_FIPAISID         IN     SCSISGES.TAGEOALERTA.FIPAISID%TYPE,
      PA_FITERRITORIOID   IN     SCSISGES.TAGEOALERTA.FITERRITORIOID%TYPE,
      PA_FIZONAID         IN     SCSISGES.TAGEOALERTA.FIZONAID%TYPE,
      PA_FIREGIONID       IN     SCSISGES.TAGEOALERTA.FIREGIONID%TYPE,
      PA_FISUCURSALID     IN     SCSISGES.TAGEOALERTA.FISUCURSALID%TYPE,
      PA_FICANALID        IN     SCSISGES.TAALERTA.FICANALID%TYPE,
      PA_FIFUNCION        IN     SCSISGES.TAGEOALERTA.FIFUNCION%TYPE,
      pa_DATOS               OUT SCSISGES.PATYPES.RCGCURSOR,
      pa_CODIGO              OUT INTEGER,
      pa_MENSAJE             OUT VARCHAR2,
      pa_MENSAJEERROR        OUT VARCHAR2);

   PROCEDURE SPVISUALALERTAS (
      pa_FIEMPNUM       IN     SCSISGES.TAEMPALERTA.FIEMPNUM%TYPE,
      pa_FIALERTAID     IN     SCSISGES.TAEMPALERTA.FIALERTAID%TYPE,
      pa_CODIGO            OUT INTEGER,
      pa_MENSAJE           OUT VARCHAR2,
      pa_MENSAJEERROR      OUT VARCHAR2);

   PROCEDURE SPCALERTASHISTORICO (
      pa_FDFECINICIAL     IN     SCSISGES.TAALERTA.FDFECINICIAL%TYPE,
      pa_FDFECTERMINO     IN     SCSISGES.TAALERTA.FDFECINICIAL%TYPE,
      pa_FIUSUARIOID      IN     SCSISGES.TAALERTA.FIUSUARIOID%TYPE,
      pa_FIALERTDESTINO   IN     SCSISGES.TAALERTA.FIALERTDESTINO%TYPE,
      pa_DATOS               OUT SCSISGES.PATYPES.RCGCURSOR,
      pa_CODIGO              OUT INTEGER,
      pa_MENSAJE             OUT VARCHAR2,
      pa_MENSAJEERROR        OUT VARCHAR2);

   PROCEDURE SPDEL (pa_FIALERTAID         SCSISGES.TAALERTA.FIALERTAID%TYPE,
                    pa_FCEMPNUM           SCSISGES.TAALERTA.FIUSUARIOID%TYPE,
                    pa_CODIGO         OUT INTEGER,
                    pa_MENSAJE        OUT VARCHAR2,
                    pa_MENSAJEERROR   OUT VARCHAR2);


   PROCEDURE ACTUALIZA (
      pa_FIALERTAID         SCSISGES.TAALERTA.FIALERTAID%TYPE,
      pa_FCTIPOALERTA       SCSISGES.TAALERTA.FCTIPOALERTA%TYPE,
      pa_FCALERTADESC       SCSISGES.TAALERTA.FCALERTADESC%TYPE,
      pa_FDINICIO           SCSISGES.TAALERTA.FDFECINICIAL%TYPE,
      pa_FDFIN              SCSISGES.TAALERTA.FDFECTERMINO%TYPE,
      pa_FISTATUS           SCSISGES.TAALERTA.FISTATUS%TYPE,
      pa_USRMODIFICO        SCSISGES.TAALERTA.USRMODIFICO%TYPE,
      pa_FICANALID          SCSISGES.TAALERTA.FICANALID%TYPE,
      pa_FCTITULO           SCSISGES.TAALERTA.FCTITULO%TYPE,
      pa_FIALCANCEID        SCSISGES.TAALERTA.FIALCANCEID%TYPE,
      pa_FIUSUARIOID        SCSISGES.TAALERTA.FIUSUARIOID%TYPE,
      pa_FIROLID            SCSISGES.TAALERTA.FIROLID%TYPE,
      pa_CODIGO         OUT INTEGER,
      pa_MENSAJE        OUT VARCHAR2,
      pa_MENSAJEERROR   OUT VARCHAR2);

   PROCEDURE SPALTAALERTAAUTOM (
      pa_FIALERTAID      IN     SCSISGES.TAALERTA.FIALERTAID%TYPE,
      pa_FIUSUARIOID     IN     SCSISGES.TAALERTA.FIUSUARIOID%TYPE,
      pa_FCTITULO        IN     SCSISGES.TAALERTA.FCTITULO%TYPE,
      pa_FCALERTADESC    IN     SCSISGES.TAALERTA.FCALERTADESC%TYPE,
      pa_FDFECINICIAL    IN     SCSISGES.TAALERTA.FDFECINICIAL%TYPE,
      pa_FDFECTERMINO    IN     SCSISGES.TAALERTA.FDFECTERMINO%TYPE,
      pa_FICANALID       IN     SCSISGES.TAALERTA.FICANALID%TYPE,
      PA_FITIPOALERTA    IN     SCSISGES.TAALERTA.FITIPOALERTA%TYPE,
      PA_FIEMPNUM        IN     SCSISGES.TAALERTAPERSONA.FIEMPNUM%TYPE,
      PA_FICATALERTAID   IN     SCSISGES.TAALERTAPERSONA.FICATALERTAID%TYPE,
      PA_FIPAIS          IN     SCSISGES.TAALERTACLIENTE.FIPAIS%TYPE,
      PA_FICANAL         IN     SCSISGES.TAALERTACLIENTE.FICANAL%TYPE,
      PA_FISUCURSAL      IN     SCSISGES.TAALERTACLIENTE.FISUCURSAL%TYPE,
      PA_FIFOLIO         IN     SCSISGES.TAALERTACLIENTE.FIFOLIO%TYPE,
      PA_FNVALOR         IN     SCSISGES.TAALERTACLIENTE.FNVALOR%TYPE,
      pa_CODIGO             OUT INTEGER,
      pa_MENSAJE            OUT VARCHAR2,
      pa_MENSAJEERROR       OUT VARCHAR2);

   PROCEDURE SPCONSULTADETALLEALERTA (
      pa_FIALERTAID   IN     SCSISGES.TAALERTACLIENTE.FIALERTAID%TYPE,
      pa_DETAIL          OUT SCSISGES.PATYPES.RCGCURSOR,
      pa_MENSAJE         OUT VARCHAR2,
      pa_CODERROR        OUT VARCHAR2,
      pa_DESERROR        OUT VARCHAR2);
END PQSISGESALERTAS;

/

  GRANT EXECUTE ON "SCSISGES"."PQSISGESALERTAS" TO "SCVENTASTIENDA";
  GRANT EXECUTE ON "SCSISGES"."PQSISGESALERTAS" TO "USRSISGES";
