--------------------------------------------------------
--  DDL for Package TEST_PAOBJETIVOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PAOBJETIVOS" IS

   /* generated by utPLSQL for SQL Developer on 2019-05-13 15:49:10 */

   --%suite(test_paobjetivos)
   --%suitepath(alltests)

   --%test
   PROCEDURE spobjetivodiaemp;

   --%test
   PROCEDURE spobjetivosememp;

   --%test
   PROCEDURE spobjetivodiasuc;

   --%test
   PROCEDURE spobjetivosemsuc;

   --%test
   PROCEDURE spobjetivodiareg;

   --%test
   PROCEDURE spobjetivosemreg;

   --%test
   PROCEDURE spobjetivodiazon;

   --%test
   PROCEDURE spobjetivosemzon;

   --%test
   PROCEDURE spobjetivodiapais;

   --%test
   PROCEDURE spobjetivosempais;

END TEST_PAOBJETIVOS;

/
