--------------------------------------------------------
--  DDL for Package TEST_PAREPORTES0002
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PAREPORTES0002" IS

   /* generated by utPLSQL for SQL Developer on 2019-03-19 17:25:05 */

   --%suite(test_pareportes0002)
   --%suitepath(alltests)
    
   --%test
   PROCEDURE spInsertGestiones; 
    
   --%test
   PROCEDURE spgestionesExitosa;

   --%test
   PROCEDURE spgestionesv2Exitosa;
  
    --%test
   PROCEDURE spDeleteGestiones;
   
   --%test
   PROCEDURE spgestionesNoExiste;

END test_pareportes0002;

/
