--------------------------------------------------------
--  DDL for Package TEST_PAPROCESAOBJETIVOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PAPROCESAOBJETIVOS" IS

   /* generated by utPLSQL for SQL Developer on 2019-05-13 16:24:00 */

   --%suite(test_paprocesaobjetivos)
   --%suitepath(alltests)

   --%test
   PROCEDURE spinsjerarquia;

   --%test
   PROCEDURE spinsobjetivossuc;

   --%test
   PROCEDURE spinsobjetivosreg;

   --%test
   PROCEDURE spinsobjetivoszon;

   --%test
   PROCEDURE spinsobjetivospais;

   --%test
   PROCEDURE spinsobjetivosemp;

   --%test
   PROCEDURE spprocesossem;

   --%test
   PROCEDURE spinsobjetivoshist;

   --%test
   PROCEDURE spdelobjetivosemp;

   --%test
   PROCEDURE spinsobjetivosememp;   

   --%test
   PROCEDURE spprocesosdia;

   --%test
   PROCEDURE spdelobjetivoshist;

END test_paprocesaobjetivos;

/
