create or replace PACKAGE SCSISGES.TEST_PAFXGESTIONSEM AS 

  -- %suite
  -- %displayname(Consulta gestiones semanales por geografia)

  -- %test
  -- %displayname(Consulta de gestiones empleado exitosa)
  
  /*Descripcion: Paquete de pruebas unitarias para gestiones semanales
    Fecha creación: 11/06/2019*/
	
  procedure consulta_gestiones;
  
END TEST_PAFXGESTIONSEM;
/
create or replace PACKAGE BODY SCSISGES.TEST_PAFXGESTIONSEM AS

  procedure consulta_gestiones AS

   /* generated by utPLSQL for SQL Developer on 2019-04-29 13:33:33 */

        pa_fnempleado       NUMBER;
        pa_fnsucursal       NUMBER;
        pa_fnregion         NUMBER;
        pa_fnzona           NUMBER;
        pa_fnterritorio     NUMBER;
        pa_fnpais           NUMBER;
        pa_fdfecha          VARCHAR2(8);
        cur_gestionsememp   SYS_REFCURSOR;
        cur_gestionsemsuc   SYS_REFCURSOR;
        cur_gestionsemreg   SYS_REFCURSOR;
        cur_gestionsemzon   SYS_REFCURSOR;
        cur_gestionsemter   SYS_REFCURSOR;
        cur_gestionsempais  SYS_REFCURSOR;
        pa_codigo           NUMBER;
        pa_mensaje          VARCHAR2(200);
                
  BEGIN
        pa_fnempleado   := 309078;
        pa_fnsucursal   := 2024;
        pa_fnregion     := 186366;
        pa_fnzona       := 186926;
        pa_fnterritorio := 186337;
        pa_fnpais       := 1;
        pa_fdfecha      := '20190612';    

        scsisges.pafxgestionsem.spgestionsememp(pa_fnempleado => pa_fnempleado, pa_fdfecha => pa_fdfecha, cur_gestionsememp => cur_gestionsememp, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsememp,'Se espera que el cursor devuelva solo una fila').to_have_count(1);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));
        --ut.expect(cur_gestionsememp,'El cursor es nulo').to_be_not_null();
        --ut.expect(pa_opened_cursor,'El cursor esta cerrado').to_(equal(TRUE));

        --open l_cursor for select * from dual connect by level <=10;
        --ut.expect( l_cursor ).to_have_count(10);        
        --close cur_gestionsememp;    
        scsisges.pafxgestionsem.spgestionsemsuc(pa_fnsucursal => pa_fnsucursal, pa_fdfecha => pa_fdfecha, cur_gestionsemsuc => cur_gestionsemsuc, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsemsuc,'Se espera que el cursor devuelva mas de una una fila').to_have_count(8);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));

        scsisges.pafxgestionsem.spgestionsemreg(pa_fnregion => pa_fnregion, pa_fdfecha => pa_fdfecha, cur_gestionsemreg => cur_gestionsemreg, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsemreg,'Se espera que el cursor devuelva mas de una una fila').to_have_count(11);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));

        scsisges.pafxgestionsem.spgestionsemzon(pa_fnzona => pa_fnzona, pa_fdfecha => pa_fdfecha, cur_gestionsemzon => cur_gestionsemzon, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsemzon,'Se espera que el cursor devuelva mas de una una fila').to_have_count(11);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));

        scsisges.pafxgestionsem.spgestionsemter(pa_fnterritorio => pa_fnterritorio, pa_fdfecha => pa_fdfecha, cur_gestionsemter => cur_gestionsemter, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsemter,'Se espera que el cursor devuelva mas de una una fila').to_have_count(6);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));


        scsisges.pafxgestionsem.spgestionsempais(pa_fnpais => pa_fnpais, pa_fdfecha => pa_fdfecha, cur_gestionsempais => cur_gestionsempais, pa_codigo => pa_codigo, pa_mensaje => pa_mensaje);
        ut.expect(cur_gestionsempais,'Se espera que el cursor devuelva mas de una una fila').to_have_count(3);
        
        ut.expect(pa_codigo,'Código de salida no es 200').to_(equal(200));
        ut.expect(pa_mensaje,'Mensaje de salida no es igual OK').to_(equal('OK'));
      
  END consulta_gestiones;

END TEST_PAFXGESTIONSEM;