--------------------------------------------------------
--  DDL for Package Body TEST_PQPROCESAREG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCVENTASTIENDA"."TEST_PQPROCESAREG" is

--INSERTA EN TACLIENTES
PROCEDURE SPINSERTA_REG10 is    
conteoreg number;
       
  BEGIN
     DELETE FROM SCVENTASTIENDA.TACLIENTES  WHERE TRUNC(fdcreacion)='25/04/2019';
     
     INSERT INTO SCVENTASTIENDA.TACLIENTES( fipais,
                                            ficanal,
                                            fisucursal,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fiocuid,
                                            fcctenombre,
                                            fccteapaterno,
                                            fccteamaterno,
                                            fcctedircalle,
                                            fcctedirnoext,
                                            fcctedirnoint,
                                            fcctecp,
                                            fcctecolonia,
                                            fcctesexo,
                                            fcctetel,
                                            fccterfc,
                                            fcctefismor,
                                            fitdaatiende,
                                            fdctefecalt,
                                            ficteeco,
                                            fiedocivil,
                                            fnlineacred,
                                            fdctefecnac,
                                            fcnocobrador,
                                            fitranno,
                                            fitrannoact,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                   VALUES ( 1,
                                            1,
                                            2024,
                                            1,
                                            2024,
                                            12546,
                                            8,
                                            789654,
                                            'PEDRO',
                                            'GARCIA',
                                            'CARMONA',
                                            'AV INSURGENTES',
                                            '5',
                                            '12',
                                            '01140',
                                            'ESCANDON',
                                            'M',
                                            '5563258964',
                                            'CAFE860307AR4',
                                            '1524',
                                            '2024',
                                            '25/04/2019',
                                            40,
                                            1,
                                            115,
                                            '14/01/1980',
                                            'SYS',
                                            555147896,
                                            555147896,
                                            '25/04/2019',
                                            '25/04/2019',
                                            'VENTASTIENDA'
                                            );
                                            
     INSERT INTO SCVENTASTIENDA.TACLIENTES( fipais,
                                            ficanal,
                                            fisucursal,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fiocuid,
                                            fcctenombre,
                                            fccteapaterno,
                                            fccteamaterno,
                                            fcctedircalle,
                                            fcctedirnoext,
                                            fcctedirnoint,
                                            fcctecp,
                                            fcctecolonia,
                                            fcctesexo,
                                            fcctetel,
                                            fccterfc,
                                            fcctefismor,
                                            fitdaatiende,
                                            fdctefecalt,
                                            ficteeco,
                                            fiedocivil,
                                            fnlineacred,
                                            fdctefecnac,
                                            fcnocobrador,
                                            fitranno,
                                            fitrannoact,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                   VALUES ( 1,
                                            1,
                                            2024,
                                            1,
                                            2024,
                                            12547,
                                            8,
                                            789654,
                                            'JAVIER',
                                            'LOPEZ',
                                            'LOPEZ',
                                            'AV CONSCRIPTO',
                                            '5',
                                            '12',
                                            '01140',
                                            'VILLA',
                                            'M',
                                            '5563258964',
                                            'CEDFE60307AR4',
                                            '1524',
                                            '2024',
                                            '25/04/2019',
                                            40,
                                            1,
                                            115,
                                            '14/01/1980',
                                            'SYS',
                                            555147896,
                                            555147896,
                                            '25/04/2019',
                                            '25/04/2019',
                                            'VENTASTIENDA'
                                            );
                                            
         INSERT INTO SCVENTASTIENDA.TACLIENTES( fipais,
                                            ficanal,
                                            fisucursal,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fiocuid,
                                            fcctenombre,
                                            fccteapaterno,
                                            fccteamaterno,
                                            fcctedircalle,
                                            fcctedirnoext,
                                            fcctedirnoint,
                                            fcctecp,
                                            fcctecolonia,
                                            fcctesexo,
                                            fcctetel,
                                            fccterfc,
                                            fcctefismor,
                                            fitdaatiende,
                                            fdctefecalt,
                                            ficteeco,
                                            fiedocivil,
                                            fnlineacred,
                                            fdctefecnac,
                                            fcnocobrador,
                                            fitranno,
                                            fitrannoact,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                   VALUES ( 1,
                                            1,
                                            2024,
                                            1,
                                            2024,
                                            12548,
                                            8,
                                            789654,
                                            'JOSE',
                                            'CAMACHO',
                                            'MACHO',
                                            'AV INSURGENTES',
                                            '5',
                                            '12',
                                            '01140',
                                            'ESCANDON',
                                            'M',
                                            '5563258964',
                                            'CAKL850307AR4',
                                            '1524',
                                            '2024',
                                            '25/04/2019',
                                            40,
                                            1,
                                            115,
                                            '14/01/1980',
                                            'SYS',
                                            555147896,
                                            555147896,
                                            '25/04/2019',
                                            '25/04/2019',
                                            'VENTASTIENDA'
                                            );
                                            
        INSERT INTO SCVENTASTIENDA.TACLIENTES( fipais,
                                            ficanal,
                                            fisucursal,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fiocuid,
                                            fcctenombre,
                                            fccteapaterno,
                                            fccteamaterno,
                                            fcctedircalle,
                                            fcctedirnoext,
                                            fcctedirnoint,
                                            fcctecp,
                                            fcctecolonia,
                                            fcctesexo,
                                            fcctetel,
                                            fccterfc,
                                            fcctefismor,
                                            fitdaatiende,
                                            fdctefecalt,
                                            ficteeco,
                                            fiedocivil,
                                            fnlineacred,
                                            fdctefecnac,
                                            fcnocobrador,
                                            fitranno,
                                            fitrannoact,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                   VALUES ( 1,
                                            1,
                                            2024,
                                            1,
                                            2024,
                                            12549,
                                            8,
                                            789654,
                                            'LUIS',
                                            'LUNA',
                                            'JAVIS',
                                            'AV CORREO',
                                            '5',
                                            '12',
                                            '01140',
                                            'ESCANDON',
                                            'M',
                                            '5563258964',
                                            'CAFE860307AR4',
                                            '1524',
                                            '2024',
                                            '25/04/2019',
                                            40,
                                            1,
                                            115,
                                            '14/01/1980',
                                            'SYS',
                                            555147896,
                                            555147896,
                                            '25/04/2019',
                                            '25/04/2019',
                                            'VENTASTIENDA'
                                            );                                                                                                             
                                            
 SELECT COUNT (1)
         INTO conteoreg
         FROM SCVENTASTIENDA.TACLIENTES
        WHERE TRUNC (fdcreacion) = '25/04/2019';

  ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                         

END SPINSERTA_REG10;                                           
      
--INSERTA EN TAPEDIDOS
PROCEDURE SPINSERTA_REG100 is    
conteoreg number;
       
  BEGIN
     DELETE FROM SCVENTASTIENDA.TAPEDIDOS  WHERE TRUNC(fdcreacion)='25/04/2019';
     
     INSERT INTO SCVENTASTIENDA.TAPEDIDOS(fipais,
                                          ficanal,
                                          fisucursal,
                                          finopedido,
                                          fingcioid,
                                          finotienda,
                                          ficteid,
                                          fidigitover,
                                          fcempnoventa,
                                          fcempnosurte,
                                          fitipoventa,
                                          fdpedfec,
                                          fnpedtotal,
                                          fipedstat,
                                          fdfecsurt,
                                          fnpedsaldo,
                                          fnenganche,
                                          fifolioparam,
                                          fipedfact,
                                          fdfecimpfactura,
                                          fdfechaarribo,
                                          fdcreacion,
                                          fdmodifico,
                                          fcusrmodifico
                                          )
                                   VALUES(1,
                                          1,
                                          2024,
                                          1675119,
                                          1,
                                          2024,
                                          15874,
                                          1,
                                          'SYS',
                                          'SYS',
                                          2,
                                          '25/04/2019',
                                          100,
                                          1,
                                          '25/04/2019',
                                          25,
                                          145,
                                          48947895,
                                          4,
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          'VENTASTIENDA'
                                          );
                                          
                                          
  INSERT INTO SCVENTASTIENDA.TAPEDIDOS(fipais,
                                          ficanal,
                                          fisucursal,
                                          finopedido,
                                          fingcioid,
                                          finotienda,
                                          ficteid,
                                          fidigitover,
                                          fcempnoventa,
                                          fcempnosurte,
                                          fitipoventa,
                                          fdpedfec,
                                          fnpedtotal,
                                          fipedstat,
                                          fdfecsurt,
                                          fnpedsaldo,
                                          fnenganche,
                                          fifolioparam,
                                          fipedfact,
                                          fdfecimpfactura,
                                          fdfechaarribo,
                                          fdcreacion,
                                          fdmodifico,
                                          fcusrmodifico
                                          )
                                   VALUES(1,
                                          1,
                                          2024,
                                          1675125,
                                          1,
                                          2024,
                                          15874,
                                          1,
                                          'SYS',
                                          'SYS',
                                          2,
                                          '25/04/2019',
                                          100,
                                          1,
                                          '25/04/2019',
                                          25,
                                          145,
                                          48947895,
                                          4,
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          'VENTASTIENDA'
                                          );                                        
                                          
                                          
  INSERT INTO SCVENTASTIENDA.TAPEDIDOS(fipais,
                                          ficanal,
                                          fisucursal,
                                          finopedido,
                                          fingcioid,
                                          finotienda,
                                          ficteid,
                                          fidigitover,
                                          fcempnoventa,
                                          fcempnosurte,
                                          fitipoventa,
                                          fdpedfec,
                                          fnpedtotal,
                                          fipedstat,
                                          fdfecsurt,
                                          fnpedsaldo,
                                          fnenganche,
                                          fifolioparam,
                                          fipedfact,
                                          fdfecimpfactura,
                                          fdfechaarribo,
                                          fdcreacion,
                                          fdmodifico,
                                          fcusrmodifico
                                          )
                                   VALUES(1,
                                          1,
                                          2024,
                                          1675124,
                                          1,
                                          2024,
                                          15874,
                                          1,
                                          'SYS',
                                          'SYS',
                                          2,
                                          '25/04/2019',
                                          100,
                                          1,
                                          '25/04/2019',
                                          25,
                                          145,
                                          48947895,
                                          4,
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          'VENTASTIENDA'
                                          );
                                          
                                          
  INSERT INTO SCVENTASTIENDA.TAPEDIDOS(fipais,
                                          ficanal,
                                          fisucursal,
                                          finopedido,
                                          fingcioid,
                                          finotienda,
                                          ficteid,
                                          fidigitover,
                                          fcempnoventa,
                                          fcempnosurte,
                                          fitipoventa,
                                          fdpedfec,
                                          fnpedtotal,
                                          fipedstat,
                                          fdfecsurt,
                                          fnpedsaldo,
                                          fnenganche,
                                          fifolioparam,
                                          fipedfact,
                                          fdfecimpfactura,
                                          fdfechaarribo,
                                          fdcreacion,
                                          fdmodifico,
                                          fcusrmodifico
                                          )
                                   VALUES(1,
                                          1,
                                          2024,
                                          1675120,
                                          1,
                                          2024,
                                          15874,
                                          1,
                                          'SYS',
                                          'SYS',
                                          2,
                                          '25/04/2019',
                                          100,
                                          1,
                                          '25/04/2019',
                                          25,
                                          145,
                                          48947895,
                                          4,
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          '25/04/2019',
                                          'VENTASTIENDA'
                                          );
                                          
                                                                                                                          
  SELECT COUNT (1)
         INTO conteoreg
         FROM SCVENTASTIENDA.TAPEDIDOS
        WHERE TRUNC (fdcreacion) = '25/04/2019';

  ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                                                                                    
END SPINSERTA_REG100;


--INSERTA EN TAMOVPEDIDOS
PROCEDURE SPINSERTA_REG120 is    
conteoreg number;
       
  BEGIN
     DELETE FROM SCVENTASTIENDA.TAMOVPEDIDOS  WHERE TRUNC(fdcreacion)='25/04/2019';
     
     INSERT INTO SCVENTASTIENDA.TAMOVPEDIDOS(fipais,
                              ficanal,
                              fisucursal,
                              finopedido,
                              finomovto,
                              finotransac,
                              fitipoop,
                              fdfecmovtoped,
                              fimovpcarabo,
                              fnmovpimp,
                              fcuserid,
                              fcws,
                              ficoncepmov,
                              fdcreacion,
                              fdmodifico,
                              fcusrmodifico
                              )
                     VALUES (1,
                             1,
                             2024,
                             1675280,
                             2,
                             1521,
                             4,
                             '25/04/2019',
                             2,
                             12.00,
                             'SYS',
                             'BAZ',
                             100,
                             '25/04/2019',
                             '25/04/2019',
                             'VENTASTIENDA');
                             
       INSERT INTO SCVENTASTIENDA.TAMOVPEDIDOS(fipais,
                              ficanal,
                              fisucursal,
                              finopedido,
                              finomovto,
                              finotransac,
                              fitipoop,
                              fdfecmovtoped,
                              fimovpcarabo,
                              fnmovpimp,
                              fcuserid,
                              fcws,
                              ficoncepmov,
                              fdcreacion,
                              fdmodifico,
                              fcusrmodifico
                              )
                     VALUES (1,
                             1,
                             2024,
                             1675281,
                             2,
                             1521,
                             4,
                             '25/04/2019',
                             2,
                             12.00,
                             'SYS',
                             'BAZ',
                             100,
                             '25/04/2019',
                             '25/04/2019',
                             'VENTASTIENDA');
                             
                             
        INSERT INTO SCVENTASTIENDA.TAMOVPEDIDOS(fipais,
                              ficanal,
                              fisucursal,
                              finopedido,
                              finomovto,
                              finotransac,
                              fitipoop,
                              fdfecmovtoped,
                              fimovpcarabo,
                              fnmovpimp,
                              fcuserid,
                              fcws,
                              ficoncepmov,
                              fdcreacion,
                              fdmodifico,
                              fcusrmodifico
                              )
                     VALUES (1,
                             1,
                             2024,
                             1675282,
                             2,
                             1521,
                             4,
                             '25/04/2019',
                             2,
                             12.00,
                             'SYS',
                             'BAZ',
                             100,
                             '25/04/2019',
                             '25/04/2019',
                             'VENTASTIENDA');
                             
       INSERT INTO SCVENTASTIENDA.TAMOVPEDIDOS(fipais,
                              ficanal,
                              fisucursal,
                              finopedido,
                              finomovto,
                              finotransac,
                              fitipoop,
                              fdfecmovtoped,
                              fimovpcarabo,
                              fnmovpimp,
                              fcuserid,
                              fcws,
                              ficoncepmov,
                              fdcreacion,
                              fdmodifico,
                              fcusrmodifico
                              )
                     VALUES (1,
                             1,
                             2024,
                             1675283,
                             2,
                             1521,
                             4,
                             '25/04/2019',
                             2,
                             12.00,
                             'SYS',
                             'BAZ',
                             100,
                             '25/04/2019',
                             '25/04/2019',
                             'VENTASTIENDA');                                                                                
                             
  SELECT COUNT (1)
         INTO conteoreg
         FROM SCVENTASTIENDA.TAMOVPEDIDOS
        WHERE TRUNC (fdcreacion) = '25/04/2019';

  ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                                                                                                                    
  END SPINSERTA_REG120;
  
  --INSERTA EN TAPREPARAME
  PROCEDURE SPINSERTA_REG50 IS
  conteoreg number;
  
    BEGIN
     DELETE FROM SCVENTASTIENDA.TAPREPARAME  WHERE TRUNC(fdcreacion)='25/04/2019';
          
     INSERT INTO SCVENTASTIENDA.TAPREPARAME(fipais,
                                            ficanal,
                                            fisucursal,
                                            fifolioparam,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fitipoventa,
                                            fcempno,
                                            fiplazo,
                                            fiperiodo,
                                            fnpabo,
                                            fnuabo,
                                            fdfecprep,
                                            fiautoriza,
                                            fitranno,
                                            finopedido,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                      VALUES(1,
                                             1,
                                             2024,
                                             1452145,
                                             1,
                                             2024,
                                             12547,
                                             8,
                                             2,
                                             'SYS',
                                             1,
                                             10,
                                             10.20,
                                             20.10,
                                             '25/04/2019',
                                             1,
                                             12547125,
                                             145632,
                                             '25/04/2019',
                                             '25/04/2019',
                                             'SYS');
                                             
    INSERT INTO SCVENTASTIENDA.TAPREPARAME(fipais,
                                            ficanal,
                                            fisucursal,
                                            fifolioparam,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fitipoventa,
                                            fcempno,
                                            fiplazo,
                                            fiperiodo,
                                            fnpabo,
                                            fnuabo,
                                            fdfecprep,
                                            fiautoriza,
                                            fitranno,
                                            finopedido,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                      VALUES(1,
                                             1,
                                             2024,
                                             1452146,
                                             1,
                                             2024,
                                             12547,
                                             8,
                                             2,
                                             'SYS',
                                             1,
                                             10,
                                             10.20,
                                             20.10,
                                             '25/04/2019',
                                             1,
                                             12547125,
                                             145632,
                                             '25/04/2019',
                                             '25/04/2019',
                                             'SYS');
                                             
     INSERT INTO SCVENTASTIENDA.TAPREPARAME(fipais,
                                            ficanal,
                                            fisucursal,
                                            fifolioparam,
                                            fingcioid,
                                            finotienda,
                                            ficteid,
                                            fidigitover,
                                            fitipoventa,
                                            fcempno,
                                            fiplazo,
                                            fiperiodo,
                                            fnpabo,
                                            fnuabo,
                                            fdfecprep,
                                            fiautoriza,
                                            fitranno,
                                            finopedido,
                                            fdcreacion,
                                            fdmodifico,
                                            fcusrmodifico
                                            )
                                      VALUES(1,
                                             1,
                                             2024,
                                             1452147,
                                             1,
                                             2024,
                                             12547,
                                             8,
                                             2,
                                             'SYS',
                                             1,
                                             10,
                                             10.20,
                                             20.10,
                                             '25/04/2019',
                                             1,
                                             12547125,
                                             145632,
                                             '25/04/2019',
                                             '25/04/2019',
                                             'SYS');                                                                                 
                                             
 SELECT COUNT (1)
         INTO conteoreg
         FROM SCVENTASTIENDA.TAPREPARAME
        WHERE TRUNC (fdcreacion) = '25/04/2019';

  ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                                                                                                                    
  END SPINSERTA_REG50;   
  
  
  --INSERTA EN TAPREPARAME
  PROCEDURE SPINSERTA_REG2320 IS
  conteoreg number;
  
    BEGIN
     DELETE FROM SCVENTASTIENDA.CRECTEUNICPED WHERE TRUNC(FDMODIFICACION)='25/04/2019';
          
     INSERT INTO SCVENTASTIENDA.CRECTEUNICPED(
              FIPAIS,
              FICANAL,
              FISUCURSAL,
              FINOPEDIDO,
              FIPAISCU,
              FICANALCU,
              FISUCURSALCU,
              FIFOLIO,
              FIPERIODOPAGO,
              FINOPROMO,
              FITIR,
              FISTSCARTERAVENDIDA,
              FIPAISIDCUADD,
              FICANALCUADD,
              FISUCURSALCUADD,
              FIFOLIOCUADD,
              FISTATUSREGIONAL,
              FDMODIFICACION,
              FCUSRMODIFICACION
             )
      VALUES (1,
              1,
              2024,
              128941,
              1,
              1,
              2024,
              896547,
              1,
              1,
              1,
              1,
              1,
              1,
              2024,
              128941,
              1,
              '25/04/2019',
              'USER'
              );
                                             
    INSERT INTO SCVENTASTIENDA.CRECTEUNICPED (
              FIPAIS,
              FICANAL,
              FISUCURSAL,
              FINOPEDIDO,
              FIPAISCU,
              FICANALCU,
              FISUCURSALCU,
              FIFOLIO,
              FIPERIODOPAGO,
              FINOPROMO,
              FITIR,
              FISTSCARTERAVENDIDA,
              FIPAISIDCUADD,
              FICANALCUADD,
              FISUCURSALCUADD,
              FIFOLIOCUADD,
              FISTATUSREGIONAL,
              FDMODIFICACION,
              FCUSRMODIFICACION
             )
      VALUES (1,
              1,
              2024,
              128942,
              1,
              1,
              2024,
              896547,
              1,
              1,
              1,
              1,
              1,
              1,
              2024,
              128942,
              1,
              '25/04/2019',
              'USER'
              );
                                             
     INSERT INTO SCVENTASTIENDA.CRECTEUNICPED (
              FIPAIS,
              FICANAL,
              FISUCURSAL,
              FINOPEDIDO,
              FIPAISCU,
              FICANALCU,
              FISUCURSALCU,
              FIFOLIO,
              FIPERIODOPAGO,
              FINOPROMO,
              FITIR,
              FISTSCARTERAVENDIDA,
              FIPAISIDCUADD,
              FICANALCUADD,
              FISUCURSALCUADD,
              FIFOLIOCUADD,
              FISTATUSREGIONAL,
              FDMODIFICACION,
              FCUSRMODIFICACION
             )
      VALUES (1,
              1,
              2024,
              128943,
              1,
              1,
              2024,
              896547,
              1,
              1,
              1,
              1,
              1,
              1,
              2024,
              128943,
              1,
              '25/04/2019',
              'USER'
              ) ;                                                                             
                                             
 SELECT COUNT (1)
         INTO conteoreg
         FROM SCVENTASTIENDA.CRECTEUNICPED
        WHERE TRUNC (FDMODIFICACION) = '25/04/2019';

  ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                                                                                                                    
  END SPINSERTA_REG2320;                      

  
  
end TEST_PQPROCESAREG;

/
