--------------------------------------------------------
--  DDL for Table TACATTRANSACCION
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TACATTRANSACCION" 
   (	"FITRANTIPO" NUMBER(5,0), 
	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FCTRAN_DESC" VARCHAR2(320 CHAR), 
	"FITRAN_ESTATUS" NUMBER(2,0) DEFAULT 1, 
	"FCTRAN_COMEN" VARCHAR2(100 CHAR), 
	"FIMOD_SIST" NUMBER(5,0), 
	"FCORA_USR" VARCHAR2(40 CHAR), 
	"FDFECHA_ALTA" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_CATALOGO_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACATTRANSACCION" TO "USRINFFENIX";
