--------------------------------------------------------
--  DDL for Table TACAT_SP
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TACAT_SP" 
   (	"FCSP_NAME" VARCHAR2(30 CHAR), 
	"FCSP_OWNER" VARCHAR2(40 CHAR), 
	"FISP_NUM_EST" NUMBER(3,0), 
	"FISP_TIPO_EST" NUMBER(3,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_CATALOGO_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACAT_SP" TO "USRINFFENIX";
