--------------------------------------------------------
--  DDL for Table TATRNCRDTEHIST
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TATRNCRDTEHIST" 
   (	"ORA_ERR_ROWID" ROWID, 
	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FICONSDETA" NUMBER(10,0), 
	"FITIPOREG" NUMBER(5,0), 
	"FCDATODETA" VARCHAR2(270 CHAR), 
	"FISTS_ERRSOL" NUMBER(2,0) DEFAULT 0, 
	"FDFECHA_ERRSOL" DATE DEFAULT TO_DATE ('1901-01-01', 'YYYY-MM-DD'), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TATRNCRDTE_01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP01_DAT" , 
 PARTITION "TATRNCRDTE_02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP02_DAT" , 
 PARTITION "TATRNCRDTE_03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP03_DAT" , 
 PARTITION "TATRNCRDTE_04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP04_DAT" , 
 PARTITION "TATRNCRDTE_05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRNCRDTE_RP05_DAT" ) ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFFENIX";
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFSISGES";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFSISGES";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFSISGES";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRDTEHIST" TO "USRINFSISGES";
