--------------------------------------------------------
--  DDL for Table TATRNCRCBE
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TATRNCRCBE" 
   (	"ORA_ERR_ROWID" ROWID, 
	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FITRANTIPO" NUMBER(5,0), 
	"FICONSECTIPO" NUMBER(10,0), 
	"FDTRANSFECHR" DATE, 
	"FCTRANWS" VARCHAR2(10 CHAR), 
	"FCTRANUSR" VARCHAR2(10 CHAR), 
	"FITRANNOREG" NUMBER(5,0), 
	"FITRANSMIT" NUMBER(5,0), 
	"FISTS_ERRSOL" NUMBER(2,0) DEFAULT 0, 
	"FDFECHA_ERRSOL" DATE DEFAULT TO_DATE('1901-01-01', 'YYYY-MM-DD'), 
	"FDFECHARECEP" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCAER_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBE" TO "USRINFFENIX";
