--------------------------------------------------------
--  DDL for Table CENLINEACRED
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."CENLINEACRED" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FIPAISGESTOR" NUMBER(5,0), 
	"FICANALGESTOR" NUMBER(5,0), 
	"FISUCURSALGESTORA" NUMBER(5,0), 
	"FISTATUS" NUMBER(5,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FDFECHAACT" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(5,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FISTSCU" NUMBER(5,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICACION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "CLINEACR001"  VALUES LESS THAN (800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP01_DAT" , 
 PARTITION "CLINEACR002"  VALUES LESS THAN (1600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP02_DAT" , 
 PARTITION "CLINEACR003"  VALUES LESS THAN (2400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP03_DAT" , 
 PARTITION "CLINEACR004"  VALUES LESS THAN (3200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP04_DAT" , 
 PARTITION "CLINEACR005"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP05_DAT" , 
 PARTITION "CLINEACR006"  VALUES LESS THAN (4800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP06_DAT" , 
 PARTITION "CLINEACR007"  VALUES LESS THAN (5600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP07_DAT" , 
 PARTITION "CLINEACR008"  VALUES LESS THAN (6400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP08_DAT" , 
 PARTITION "CLINEACR009"  VALUES LESS THAN (7200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP09_DAT" , 
 PARTITION "CLINEACR0010"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP10_DAT" , 
 PARTITION "CLINEACR0011"  VALUES LESS THAN (8800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP11_DAT" , 
 PARTITION "CLINEACR0012"  VALUES LESS THAN (9600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP12_DAT" , 
 PARTITION "CLINEACR0013"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CENLINEACR_RP13_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."CENLINEACRED" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."CENLINEACRED" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."CENLINEACRED" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."CENLINEACRED" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."CENLINEACRED" TO "USRINFSISGES";
