--------------------------------------------------------
--  DDL for Table CRECTEUNICPED
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."CRECTEUNICPED" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FIPAISCU" NUMBER(5,0), 
	"FICANALCU" NUMBER(5,0), 
	"FISUCURSALCU" NUMBER(10,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FIPERIODOPAGO" NUMBER(5,0), 
	"FINOPROMO" NUMBER(5,0), 
	"FITIR" NUMBER(5,0), 
	"FISTSCARTERAVENDIDA" NUMBER(5,0), 
	"FISTATUSREGIONAL" NUMBER(5,0) DEFAULT 1, 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICACION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "CRECTEUNIC01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP01_DAT" , 
 PARTITION "CRECTEUNIC02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP02_DAT" , 
 PARTITION "CRECTEUNIC03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP03_DAT" , 
 PARTITION "CRECTEUNIC04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP04_DAT" , 
 PARTITION "CRECTEUNIC05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP05_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."CRECTEUNICPED" TO "USRINFSISGES";
