--------------------------------------------------------
--  DDL for Table CREDLINEACRED
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."CREDLINEACRED" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FNCAPACIDADPAGO" NUMBER(15,2), 
	"FNCAPACIDADPAGODISP" NUMBER(15,2), 
	"FNMONTOLCR" NUMBER(15,2), 
	"FIPLAZOMAX" NUMBER(5,0), 
	"FNENGANCHE1COMPRA" NUMBER(15,2), 
	"FIDIAPAGOUNICO" NUMBER(5,0), 
	"FISTATUSAUTORIZACION" NUMBER(5,0), 
	"FDFECHAULTACT" DATE, 
	"FDFECHAULTAUT" DATE, 
	"FISTATUS" NUMBER(5,0), 
	"FITRANNO" NUMBER(10,0), 
	"FILISTANEGRA" NUMBER(5,0), 
	"FILOCALIZACION" NUMBER(5,0), 
	"FIRMD" NUMBER(5,0), 
	"FILEGAL" NUMBER(5,0), 
	"FIDIFICILCOBRO" NUMBER(5,0), 
	"FIACEPTAPP" NUMBER(5,0), 
	"FIPCJ" NUMBER(3,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICACION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "CREDLINEACR001"  VALUES LESS THAN (800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP01_DAT" , 
 PARTITION "CREDLINEACR002"  VALUES LESS THAN (1600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP02_DAT" , 
 PARTITION "CREDLINEACR003"  VALUES LESS THAN (2400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP03_DAT" , 
 PARTITION "CREDLINEACR004"  VALUES LESS THAN (3200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP04_DAT" , 
 PARTITION "CREDLINEACR005"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP05_DAT" , 
 PARTITION "CREDLINEACR006"  VALUES LESS THAN (4800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP06_DAT" , 
 PARTITION "CREDLINEACR007"  VALUES LESS THAN (5600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP07_DAT" , 
 PARTITION "CREDLINEACR008"  VALUES LESS THAN (6400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP08_DAT" , 
 PARTITION "CREDLINEACR009"  VALUES LESS THAN (7200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP09_DAT" , 
 PARTITION "CREDLINEACR010"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP10_DAT" , 
 PARTITION "CREDLINEACR011"  VALUES LESS THAN (8800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP11_DAT" , 
 PARTITION "CREDLINEACR012"  VALUES LESS THAN (9600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP12_DAT" , 
 PARTITION "CREDLINEACR013"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CREDLINEAC_RP13_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."CREDLINEACRED" TO "USRINFSISGES";
