--------------------------------------------------------
--  DDL for Table TACENCTETIENDA
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACENCTETIENDA" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(15,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FIFOLIO" NUMBER(15,0), 
	"FIPAISCU" NUMBER(5,0), 
	"FICANALCU" NUMBER(5,0), 
	"FISUCURSALCU" NUMBER(10,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TACTETIENDA_01"  VALUES LESS THAN (1000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP01_DAT" , 
 PARTITION "TACTETIENDA_02"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP02_DAT" , 
 PARTITION "TACTETIENDA_03"  VALUES LESS THAN (3000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP03_DAT" , 
 PARTITION "TACTETIENDA_04"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP04_DAT" , 
 PARTITION "TACTETIENDA_05"  VALUES LESS THAN (5000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP05_DAT" , 
 PARTITION "TACTETIENDA_06"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP06_DAT" , 
 PARTITION "TACTETIENDA_07"  VALUES LESS THAN (7000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP07_DAT" , 
 PARTITION "TACTETIENDA_08"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACTETIENO_RP08_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACENCTETIENDA" TO "USRINFVENTAST";
