--------------------------------------------------------
--  DDL for Table TACREDCTECTEHTR
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDCTECTEHTR" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLICL_RP01_DAT" 
  PARTITION BY RANGE ("FDFECHAALTA") 
 (PARTITION "PTACREDCLIENTESCLIENTES"  VALUES LESS THAN (TO_DATE(' 2019-01-02 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLICL_RP01_DAT" ) ;
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCTECTEHTR" TO "USRINFVENTAST";
