--------------------------------------------------------
--  DDL for Table TACREDSOLICITUD
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDSOLICITUD" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FISOLICITUDID" NUMBER(15,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FITIPOSOLICITUD" NUMBER(5,0), 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FDFECVISITA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FCINFORMANTE" VARCHAR2(100 CHAR), 
	"FISTAT" NUMBER(5,0), 
	"FISUBSTAT" NUMBER(5,0), 
	"FDFECSTAT" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FIRECHAZOID" NUMBER(5,0), 
	"FCEJECUTIVO" VARCHAR2(10 CHAR), 
	"FDFECSOLICITUD" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FITRANNO" NUMBER(15,0), 
	"FIACEPTAPP" NUMBER(5,0), 
	"FITIPOAUTORIZACION" NUMBER(10,0), 
	"FNCAPACIDADPAGO" NUMBER(15,2), 
	"FIPLAZO" NUMBER(10,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACREDSOLI_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDSOLICITUD" TO "USRINFVENTAST";
