--------------------------------------------------------
--  DDL for Table TACREDCLIENTES
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDCLIENTES" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FIIDPERSONA" NUMBER(15,0), 
	"FITIPOCLIENTE" NUMBER(5,0), 
	"FIFISMOR" NUMBER(5,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FITRANNO" NUMBER(15,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TACRECLIENT001"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP01_DAT" , 
 PARTITION "TACRECLIENT002"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP02_DAT" , 
 PARTITION "TACRECLIENT003"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP03_DAT" , 
 PARTITION "TACRECLIENT004"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP04_DAT" , 
 PARTITION "TACRECLIENT005"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRECLIEN_RP05_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCLIENTES" TO "USRINFVENTAST";
