--------------------------------------------------------
--  DDL for Table TADETPREPARAM
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TADETPREPARAM" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FIPRODID" NUMBER(15,0), 
	"FNPRODPRECIOD" NUMBER(10,2), 
	"FICANT" NUMBER(15,0), 
	"FNDESCTO" NUMBER(10,2), 
	"FNDESCTOESP" NUMBER(10,2), 
	"FNSOBREPRECIO" NUMBER(15,4), 
	"FNPORCIVA" NUMBER(10,2), 
	"FNDESCTOMKT" NUMBER(10,2), 
	"FNCOSTOPDCTO" NUMBER(10,2), 
	"FISTATDP" NUMBER(5,0), 
	"FNINTERESES" NUMBER(10,2), 
	"FNENGANCHE" NUMBER(10,2), 
	"FICVEPROM" NUMBER(15,0), 
	"FNCOMISIONV" NUMBER(10,2), 
	"FNCOMISIONG" NUMBER(10,2), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TADETPREPA_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TADETPREPARAM" TO "USRINFVENTAST";
