--------------------------------------------------------
--  DDL for Table TAEST01001_4368
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_4368" 
   (	"FISOLICITUDID" NUMBER(10,0), 
	"FITIPOSOLICITUD" NUMBER(3,0), 
	"FIFOLIOPARAM" NUMBER(10,0), 
	"FDFECVISITA" DATE, 
	"FCINFORMANTE" VARCHAR2(60 CHAR), 
	"FISTAT" NUMBER(3,0), 
	"FISUBSTAT" NUMBER(3,0), 
	"FDFECSTAT" DATE, 
	"FIRECHAZOID" NUMBER(3,0), 
	"FIIDNEGOCIO" NUMBER(3,0), 
	"FIIDTIENDA" NUMBER(5,0), 
	"FIIDCLIENTE" NUMBER(10,0), 
	"FCEJECUTIVO" VARCHAR2(6 CHAR), 
	"FIACEPTAPP" NUMBER(3,0), 
	"FITIPOAUTORIZACION" NUMBER(5,0), 
	"FNCAPACIDADPAGO" NUMBER(9,2), 
	"FIPLAZO" NUMBER(10,0), 
	"FDFECSOLICITUD" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA02_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4368" TO "USRINFVENTAST";
