--------------------------------------------------------
--  DDL for Table TAEST01001_0075
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_0075" 
   (	"FCPOBDESC" VARCHAR2(40 CHAR), 
	"FCEDODESC" VARCHAR2(20 CHAR), 
	"FCCTESEXO" VARCHAR2(1 CHAR), 
	"FCCTETEL" VARCHAR2(15 CHAR), 
	"FCCTERFC" VARCHAR2(14 CHAR), 
	"FCCTEFISMOR" VARCHAR2(2 CHAR), 
	"FIEDOCIVIL" NUMBER(3,0), 
	"FDCTEFECNAC" DATE, 
	"FITDAATIENDE" NUMBER(5,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA01_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0075" TO "USRINFVENTAST";
