--------------------------------------------------------
--  DDL for Table TAEST01001_0185
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_0185" 
   (	"FINEGOCIO" NUMBER(3,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGVERIF" NUMBER(3,0), 
	"FCUSERMARCAV" VARCHAR2(10 CHAR), 
	"FCUSERMARCACAMB" VARCHAR2(10 CHAR), 
	"FCUSERSURTE" VARCHAR2(10 CHAR), 
	"FCFOLIOPARAM" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FIPEDSTAT" NUMBER(3,0), 
	"FDPEDFEC" DATE, 
	"FDFECSURT" DATE, 
	"FDFECCANPED" DATE, 
	"FITIPOCTE" NUMBER(3,0), 
	"FITIPOVENTA" NUMBER(3,0), 
	"FIMCID" NUMBER(5,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA02_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0185" TO "USRINFVENTAST";
