--------------------------------------------------------
--  DDL for Table TAESTSOLICITUD
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAESTSOLICITUD" 
   (	"FIESTATUS" NUMBER(5,0), 
	"FCDESCRIPCION" VARCHAR2(150 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CATALOGO_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAESTSOLICITUD" TO "USRINFFENIX";
