--------------------------------------------------------
--  DDL for Table TAEST01001_4719
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_4719" 
   (	"FIIDPAIS" NUMBER(3,0), 
	"FIIDCANAL" NUMBER(3,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FISTATUS" NUMBER(3,0), 
	"FCFOLIOPARAM" NUMBER(10,0), 
	"FDMARCADA" DATE, 
	"FDSURTIDA" DATE, 
	"FDCANCELADA" DATE, 
	"FCEMPSURTIO" VARCHAR2(6 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA03_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4719" TO "USRINFFENIX";
