--------------------------------------------------------
--  DDL for Table TAPEDIDOS
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAPEDIDOS" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(15,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FCEMPNOVENTA" VARCHAR2(10 CHAR) DEFAULT 0, 
	"FCEMPNOSURTE" VARCHAR2(10 CHAR) DEFAULT 0, 
	"FITIPOVENTA" NUMBER(5,0), 
	"FDPEDFEC" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FNPEDTOTAL" NUMBER(15,2) DEFAULT 0, 
	"FIPEDSTAT" NUMBER(3,0) DEFAULT 0, 
	"FDFECSURT" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FNPEDSALDO" NUMBER(15,2) DEFAULT 0, 
	"FNENGANCHE" NUMBER(15,2) DEFAULT 0, 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FIPEDFACT" NUMBER(15,0) DEFAULT 0, 
	"FDFECIMPFACTURA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FDFECHAARRIBO" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPEDIDOS_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPEDIDOS" TO "USRINFFENIX";
