--------------------------------------------------------
--  DDL for Table TAPREPARAMEHTR
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAPREPARAMEHTR" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(15,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FITIPOVENTA" NUMBER(5,0), 
	"FCEMPNO" VARCHAR2(10 CHAR), 
	"FIPLAZO" NUMBER(10,0), 
	"FIPERIODO" NUMBER(5,0), 
	"FNPABO" NUMBER(10,2), 
	"FNUABO" NUMBER(10,2), 
	"FDFECPREP" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FIAUTORIZA" NUMBER(5,0), 
	"FITRANNO" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPREPARAMEHTR" TO "USRINFFENIX";
