--------------------------------------------------------
--  DDL for Table TATRANSAC_ERROR
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TATRANSAC_ERROR" 
   (	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FITRANTIPO" NUMBER(5,0), 
	"FICONSECTIPO" NUMBER(10,0), 
	"FDTRANSFECHR" DATE, 
	"FCTRANWS" VARCHAR2(15 BYTE), 
	"FCTRANUSR" VARCHAR2(15 BYTE), 
	"FICONSDETA" NUMBER(5,0), 
	"FITIPOREG" NUMBER(5,0), 
	"FCDATODETA" VARCHAR2(4000 BYTE), 
	"FCDESCERROR" VARCHAR2(2000 BYTE), 
	"FISTATUS" NUMBER(1,0), 
	"FDCREACION" DATE, 
	"FDMODIFICO" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TATRANSERR01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP01_DAT" , 
 PARTITION "TATRANSERR02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP02_DAT" , 
 PARTITION "TATRANSERR03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP03_DAT" , 
 PARTITION "TATRANSERR04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP04_DAT" , 
 PARTITION "TATRANSERR05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASACERROR_RP05_DAT" ) ;

   COMMENT ON COLUMN "SCVENTASTIENDA"."TATRANSAC_ERROR"."FITIPOREG" IS 'TIPO DE REGISTRO DE LA TXN';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TATRANSAC_ERROR"."FCDATODETA" IS 'CADENA DEL REGISTRO DE LA TXN';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TATRANSAC_ERROR"."FCDESCERROR" IS 'DESCRIPCION DE ERROR ORA- DE LA TXN';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TATRANSAC_ERROR"."FISTATUS" IS '1=TXN EN ERROR,   2=TXN CORRECTA';
  GRANT DELETE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATRANSAC_ERROR" TO "USRINFSISGES";
