--------------------------------------------------------
--  DDL for Table TCLINEA
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TCLINEA" 
   (	"FNLINEA" NUMBER(3,0), 
	"FCPRDLINDESC" VARCHAR2(50 CHAR), 
	"FNLINEAPROD" NUMBER(2,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CATALOGO_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TCLINEA" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCLINEA" TO "USRINFFENIX";
