--------------------------------------------------------
--  DDL for Index IDX_TIPOBUZDET
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_TIPOBUZDET" ON "SCSISGES"."TABUZONDETALLE" ("FNTIPOREGISTRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TABUZONDET_IDX" ;
