--------------------------------------------------------
--  DDL for Index IDX_TABUZONDET
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCSISGES"."IDX_TABUZONDET" ON "SCSISGES"."TABUZONDETALLE" ("FIBUZONDETID", "FIBUZONID", "FCEMPNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TABUZONDET_IDX" ;
