--------------------------------------------------------
--  DDL for Index IDX_VTASEMJER
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_VTASEMJER" ON "SCSISGES"."TAVENTASEMANAL" ("FIIDTERRITORIO", "FIIDREGION", "FIIDZONA", "FIIDPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "VENTA_SUC_P1" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAVDVTSMNL_RP01_IDX" , 
 PARTITION "VENTA_SUC_P2" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAVDVTSMNL_RP02_IDX" , 
 PARTITION "VENTA_SUC_P3" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAVDVTSMNL_RP03_IDX" , 
 PARTITION "VENTA_SUC_P4" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAVDVTSMNL_RP04_IDX" , 
 PARTITION "VENTA_SUC_P5" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAVDVTSMNL_RP05_IDX" ) ;
