--------------------------------------------------------
--  DDL for Index IDX_OBJTERSEM
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_OBJTERSEM" ON "SCSISGES"."TAOBJETIVOTER" ("FNSEMANA", "FNANIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_IDX" ;
