--------------------------------------------------------
--  DDL for Index IDX_OBJREGGEO
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_OBJREGGEO" ON "SCSISGES"."TAOBJETIVOREG" ("FIIDPAIS", "FIIDTERRITORIO", "FIIDZONA", "FIIDREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_IDX" ;
