--------------------------------------------------------
--  DDL for Index IDX_INACBUZON
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_INACBUZON" ON "SCSISGES"."TABUZON" ("FNINACTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_IDX" ;
