--------------------------------------------------------
--  DDL for Index IDX_INACBUZDET
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_INACBUZDET" ON "SCSISGES"."TABUZONDETALLE" ("FNINACTIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TABUZONDET_IDX" ;
