--------------------------------------------------------
--  DDL for Index IX02OBJETIVOS
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IX02OBJETIVOS" ON "SCSISGES"."TAOBJETIVOS" ("FNCCOSTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_IDX" ;
