--------------------------------------------------------
--  DDL for Index IX_TAPROMOCION02
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IX_TAPROMOCION02" ON "SCSISGES"."TAPROMOCIONES" ("FIESTATUSINTERES", "FCEMPNO", "FDFECHAMOD", "FIIDSUBLINEA", "FDMODIFICO", "FCUSRMODIFICO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_IDX" ;
