--------------------------------------------------------
--  DDL for Package Body PAFXTRUNCAMAPASVT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" is

PROCEDURE SPTRUNCACTETIENDA IS

BEGIN

    --SE TRUNCA LA TABLA DE CLIENTE TIENDA
    EXECUTE IMMEDIATE('TRUNCATE TABLE scventastienda.tacenctetienda');

END SPTRUNCACTETIENDA;
end PAFXTRUNCAMAPASVT;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" TO "SCSISGES";
  GRANT EXECUTE ON "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" TO "USRINFSISGES";
  GRANT EXECUTE ON "SCVENTASTIENDA"."PAFXTRUNCAMAPASVT" TO "USRINFVENTAST";
