--------------------------------------------------------
--  DDL for Package Body TEST_PAAPPLICATION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCVENTASTIENDA"."TEST_PAAPPLICATION" IS

   /* generated by utPLSQL for SQL Developer on 2019-04-12 18:30:52 */

   --
   -- test spqaplication case 1: ...
   --
   csl_0             CONSTANT PLS_INTEGER := 0;
   csl_1          CONSTANT PLS_INTEGER := 1;
   csl_100           CONSTANT PLS_INTEGER := 100;
   csl_usr        CONSTANT VARCHAR2(30):='UNIT_TEST';
    
   PROCEDURE spqaplication IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      -- paapplication.spqaplication;

      -- populate expected
      -- ...

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END spqaplication;

   --
   -- test spdetsols case 1: ...
   --
   PROCEDURE spdetsols IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      -- paapplication.spdetsols;

      -- populate expected
      -- ...

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END spdetsols;

   --
   -- test spcountsolssuperv case 1: ...
   --
   PROCEDURE spcountsolssuperv IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      -- paapplication.spcountsolssuperv;

      -- populate expected
      -- ...

      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END spcountsolssuperv;

   --
   -- test spqaplicationv2 case 1: ...
   --
   PROCEDURE spqaplicationv2
   IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      vlcur_solicitudes typ_solicitud; 
      vl_numDias NUMBER(1) :=0;
      vl_numEmpleado NUMBER :=309078;
      vl_mensaje     VARCHAR2(242);
      vl_coderror    INTEGER;
      vl_deserror    VARCHAR2(242);
   BEGIN
      -- populate actual
      -- paapplication.spqaplicationv2;

      -- populate expected
      -- ...

      -- assert
      
      /*tasolicitudes*/
        vlcur_solicitudes(1).FIPAIS:=  1  ;
        vlcur_solicitudes(1).FICANAL:=  1  ;
        vlcur_solicitudes(1).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(1).FISOLICITUDID:=  82144  ;
        vlcur_solicitudes(1).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(1).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(1).FIIDCLIENTE:=  105805  ;
        vlcur_solicitudes(1).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(1).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(1).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(1).FISUBSTAT:=  0 ;
        vlcur_solicitudes(1).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(1).FIINE:=  1  ;
        vlcur_solicitudes(1).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(1).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(1).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(1).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(1).FIAUTORIZADA:=  0  ;
        vlcur_solicitudes(1).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(1).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(1).FILIBERADA:=  0  ;
        vlcur_solicitudes(1).FNMONTO:=  23400  ;
        vlcur_solicitudes(1).FCOBSERVACIONES:=  null  ;
        vlcur_solicitudes(1).FDCREACION:= SYSDATE ;
    
        
        vlcur_solicitudes(2).FIPAIS:=  1  ;
        vlcur_solicitudes(2).FICANAL:=  1  ;
        vlcur_solicitudes(2).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(2).FISOLICITUDID:=  82443  ;
        vlcur_solicitudes(2).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(2).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(2).FIIDCLIENTE:=  106069  ;
        vlcur_solicitudes(2).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(2).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(2).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(2).FISUBSTAT:=  0  ;
        vlcur_solicitudes(2).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(2).FIINE:=  1  ;
        vlcur_solicitudes(2).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(2).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(2).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(2).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(2).FIAUTORIZADA:=  0  ;
        vlcur_solicitudes(2).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(2).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(2).FILIBERADA:=  0  ;
        vlcur_solicitudes(2).FNMONTO:=  17550  ;
        vlcur_solicitudes(2).FCOBSERVACIONES:= null;
        vlcur_solicitudes(2).FDCREACION:=  SYSDATE ;
    
    
        vlcur_solicitudes(3).FIPAIS:=  1  ;
        vlcur_solicitudes(3).FICANAL:=  1  ;
        vlcur_solicitudes(3).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(3).FISOLICITUDID:=  82561  ;
        vlcur_solicitudes(3).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(3).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(3).FIIDCLIENTE:=  106168  ;
        vlcur_solicitudes(3).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(3).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(3).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(3).FISUBSTAT:=  0  ;
        vlcur_solicitudes(3).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(3).FIINE:=  1  ;
        vlcur_solicitudes(3).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(3).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(3).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(3).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(3).FIAUTORIZADA:=  0  ;
        vlcur_solicitudes(3).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(3).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(3).FILIBERADA:=  0  ;
        vlcur_solicitudes(3).FNMONTO:=  39000  ;
        vlcur_solicitudes(3).FCOBSERVACIONES:= null;
        vlcur_solicitudes(3).FDCREACION:=  SYSDATE ;
    
    
        vlcur_solicitudes(4).FIPAIS:=  1  ;
        vlcur_solicitudes(4).FICANAL:=  1  ;
        vlcur_solicitudes(4).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(4).FISOLICITUDID:=  82560  ;
        vlcur_solicitudes(4).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(4).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(4).FIIDCLIENTE:=  106167  ;
        vlcur_solicitudes(4).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(4).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(4).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(4).FISUBSTAT:=  0  ;
        vlcur_solicitudes(4).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(4).FIINE:=  1  ;
        vlcur_solicitudes(4).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(4).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(4).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(4).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(4).FIAUTORIZADA:=  0  ;
        vlcur_solicitudes(4).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(4).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(4).FILIBERADA:=  0  ;
        vlcur_solicitudes(4).FNMONTO:=  15600  ;
        vlcur_solicitudes(4).FCOBSERVACIONES:=  null  ;
        vlcur_solicitudes(4).FDCREACION:=  SYSDATE ;
    
    
        vlcur_solicitudes(5).FIPAIS:=  1  ;
        vlcur_solicitudes(5).FICANAL:=  1  ;
        vlcur_solicitudes(5).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(5).FISOLICITUDID:=  82555  ;
        vlcur_solicitudes(5).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(5).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(5).FIIDCLIENTE:=  106164  ;
        vlcur_solicitudes(5).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(5).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(5).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(5).FISUBSTAT:=  0  ;
        vlcur_solicitudes(5).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(5).FIINE:=  1  ;
        vlcur_solicitudes(5).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(5).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(5).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(5).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(5).FIAUTORIZADA:=  0  ;
        vlcur_solicitudes(5).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(5).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(5).FILIBERADA:=  0  ;
        vlcur_solicitudes(5).FNMONTO:=  17550  ;
        vlcur_solicitudes(5).FCOBSERVACIONES:=   null ;
        vlcur_solicitudes(5).FDCREACION:=  SYSDATE  ;
    
    
        vlcur_solicitudes(6).FIPAIS:=  1  ;
        vlcur_solicitudes(6).FICANAL:=  1  ;
        vlcur_solicitudes(6).FISUCURSAL:=  2024  ;
        vlcur_solicitudes(6).FISOLICITUDID:=  83382  ;
        vlcur_solicitudes(6).FIIDNEGOCIO:=  1  ;
        vlcur_solicitudes(6).FIIDTIENDA:=  2024  ;
        vlcur_solicitudes(6).FIIDCLIENTE:=  106580  ;
        vlcur_solicitudes(6).FITIPOSOLICITUD:=  8  ;
        vlcur_solicitudes(6).FIFOLIOPARAM:=  0  ;
        vlcur_solicitudes(6).FCEMPNO:=  vl_numEmpleado  ;
        vlcur_solicitudes(6).FISUBSTAT:=  0  ;
        vlcur_solicitudes(6).FISOLCOMPLETA:=  1  ;
        vlcur_solicitudes(6).FIINE:=  1  ;
        vlcur_solicitudes(6).FICOMPDOMICILIO:=  1  ;
        vlcur_solicitudes(6).FICOMPINGRESOS:=  1  ;
        vlcur_solicitudes(6).FIFIRMACONTRATO:=  1  ;
        vlcur_solicitudes(6).FIVISITAJVC:=  1  ;
        vlcur_solicitudes(6).FIAUTORIZADA:=  1  ;
        vlcur_solicitudes(6).FILCRSINTAZ:=  0  ;
        vlcur_solicitudes(6).FILCRCONTAZ:=  0  ;
        vlcur_solicitudes(6).FILIBERADA:=  0  ;
        vlcur_solicitudes(6).FNMONTO:=  17550  ;
        vlcur_solicitudes(6).FCOBSERVACIONES:=   null ;
        vlcur_solicitudes(6).FDCREACION:=	SYSDATE	;
		
		
        vlcur_solicitudes(7).FIPAIS:=	1	;
        vlcur_solicitudes(7).FICANAL:=	1	;
        vlcur_solicitudes(7).FISUCURSAL:=	2024	;
        vlcur_solicitudes(7).FISOLICITUDID:=	84498	;
        vlcur_solicitudes(7).FIIDNEGOCIO:=	1	;
        vlcur_solicitudes(7).FIIDTIENDA:=	2024	;
        vlcur_solicitudes(7).FIIDCLIENTE:=	107009	;
        vlcur_solicitudes(7).FITIPOSOLICITUD:=	8	;
        vlcur_solicitudes(7).FIFOLIOPARAM:=	0	;
        vlcur_solicitudes(7).FCEMPNO:=	vl_numEmpleado	;
        vlcur_solicitudes(7).FISUBSTAT:=	0	;
        vlcur_solicitudes(7).FISOLCOMPLETA:=	1	;
        vlcur_solicitudes(7).FIINE:=	1	;
        vlcur_solicitudes(7).FICOMPDOMICILIO:=	1	;
        vlcur_solicitudes(7).FICOMPINGRESOS:=	1	;
        vlcur_solicitudes(7).FIFIRMACONTRATO:=	1	;
        vlcur_solicitudes(7).FIVISITAJVC:=	1	;
        vlcur_solicitudes(7).FIAUTORIZADA:=	0	;
        vlcur_solicitudes(7).FILCRSINTAZ:=	0	;
        vlcur_solicitudes(7).FILCRCONTAZ:=	0	;
        vlcur_solicitudes(7).FILIBERADA:=	0	;
        vlcur_solicitudes(7).FNMONTO:=	12480	;
        vlcur_solicitudes(7).FCOBSERVACIONES:=	'FAM MISMO DOM CON RMD 0101202614116 INES SALDAÑA';
        vlcur_solicitudes(7).FDCREACION:=	SYSDATE;


        /*TACREDCTECTES*/
        vlcur_solicitudes(1).FINGCIOID:=	1	;
        vlcur_solicitudes(1).FINOTIENDA:=	2325	;
        vlcur_solicitudes(1).FICTEID:=	136860	;
        vlcur_solicitudes(1).FIDIGITOVER:=	1	;
        vlcur_solicitudes(1).FDFECHAALTA:=	NULL	;
                
                
        vlcur_solicitudes(2).FINGCIOID:=	1	;
        vlcur_solicitudes(2).FINOTIENDA:=	2361	;
        vlcur_solicitudes(2).FICTEID:=	105989	;
        vlcur_solicitudes(2).FIDIGITOVER:=	9	;
        vlcur_solicitudes(2).FDFECHAALTA:=	NULL	;
                
        vlcur_solicitudes(3).FINGCIOID:=	1	;
        vlcur_solicitudes(3).FINOTIENDA:=	6224	;
        vlcur_solicitudes(3).FICTEID:=	158379	;
        vlcur_solicitudes(3).FIDIGITOVER:=	3	;
        vlcur_solicitudes(3).FDFECHAALTA:=	NULL;
                
                
        vlcur_solicitudes(4).FINGCIOID:=	1	;
        vlcur_solicitudes(4).FINOTIENDA:=	2066	;
        vlcur_solicitudes(4).FICTEID:=	180701	;
        vlcur_solicitudes(4).FIDIGITOVER:=	5	;
        vlcur_solicitudes(4).FDFECHAALTA:=	NULL;
		
		
        vlcur_solicitudes(5).FINGCIOID:=	1	;
        vlcur_solicitudes(5).FINOTIENDA:=	2024	;
        vlcur_solicitudes(5).FICTEID:=	400672	;
        vlcur_solicitudes(5).FIDIGITOVER:=	1	;
        vlcur_solicitudes(5).FDFECHAALTA:=	NULL;
                
                
        vlcur_solicitudes(6).FINGCIOID:=	1	;
        vlcur_solicitudes(6).FINOTIENDA:=	4323	;
        vlcur_solicitudes(6).FICTEID:=	208617	;
        vlcur_solicitudes(6).FIDIGITOVER:=	1	;
        vlcur_solicitudes(6).FDFECHAALTA:=	NULL;
                
                
        vlcur_solicitudes(7).FINGCIOID:=	1	;
        vlcur_solicitudes(7).FINOTIENDA:=	2024	;
        vlcur_solicitudes(7).FICTEID:=	402674	;
        vlcur_solicitudes(7).FIDIGITOVER:=	5	;
        vlcur_solicitudes(7).FDFECHAALTA:=	NULL;
        
        /*TACENCTETIENDA*/
        vlcur_solicitudes(1).FIFOLIO:=	101058;
        vlcur_solicitudes(1).FIPAISCU:=	1	;
        vlcur_solicitudes(1).FICANALCU:=	1	;
        vlcur_solicitudes(1).FISUCURSALCU:=	2325	;
                
                
        vlcur_solicitudes(2).FIFOLIO:=	113632	;
        vlcur_solicitudes(2).FIPAISCU:=	1	;
        vlcur_solicitudes(2).FICANALCU:=	20	;
        vlcur_solicitudes(2).FISUCURSALCU:=	2361	;
		
		
        vlcur_solicitudes(3).FIFOLIO:=	114523	;
        vlcur_solicitudes(3).FIPAISCU:=	1	;
        vlcur_solicitudes(3).FICANALCU:=	1	;
        vlcur_solicitudes(3).FISUCURSALCU:=	6224	;
                
                
        vlcur_solicitudes(4).FIFOLIO:=	121733	;
        vlcur_solicitudes(4).FIPAISCU:=	1	;
        vlcur_solicitudes(4).FICANALCU:=	1	;
        vlcur_solicitudes(4).FISUCURSALCU:=	2066	;
                
                
        vlcur_solicitudes(5).FIFOLIO:=	123456	;
        vlcur_solicitudes(5).FIPAISCU:=	1	;
        vlcur_solicitudes(5).FICANALCU:=	1	;
        vlcur_solicitudes(5).FISUCURSALCU:=	2024	;
                
                
        vlcur_solicitudes(6).FIFOLIO:=	125478	;
        vlcur_solicitudes(6).FIPAISCU:=	1	;
        vlcur_solicitudes(6).FICANALCU:=	1	;
        vlcur_solicitudes(6).FISUCURSALCU:=	4323	;
                
                
        vlcur_solicitudes(7).FIFOLIO:=	158963	;
        vlcur_solicitudes(7).FIPAISCU:=	1	;
        vlcur_solicitudes(7).FICANALCU:=	1	;
        vlcur_solicitudes(7).FISUCURSALCU:=	2024	;
        
        /*TACLIENTES*/
        vlcur_solicitudes(1).FIOCUID:=	104	;
        vlcur_solicitudes(1).FCCTENOMBRE:=	'Shannel'	;
        vlcur_solicitudes(1).FCCTEAPATERNO:=	'Shinne'	;
        vlcur_solicitudes(1).FCCTEAMATERNO:=	'Shinne'	;
        vlcur_solicitudes(1).FCCTEDIRNOEXT:=	'M 7'	;
        vlcur_solicitudes(1).FCCTEDIRNOINT:=	'L 43A'	;
        vlcur_solicitudes(1).FCCTECP:=	14734	;
        vlcur_solicitudes(1).FCCTECOLONIA:=	'ZACATON'	;
        vlcur_solicitudes(1).FCCTESEXO:=	'F'	;
        vlcur_solicitudes(1).FCCTETEL:=	5581277878	;
        vlcur_solicitudes(1).FCCTERFC:=	'LEPP800403LX6'	;
        vlcur_solicitudes(1).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(1).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(1).FDCTEFECALT:=	SYSDATE;
        vlcur_solicitudes(1).FICTEECO:=		NULL;
        vlcur_solicitudes(1).FIEDOCIVIL:=	3	;
        vlcur_solicitudes(1).FNLINEACRED:=	0	;
        vlcur_solicitudes(1).FDCTEFECNAC:=	NULL;
        vlcur_solicitudes(1).FCNOCOBRADOR:=		NULL;
        vlcur_solicitudes(1).FITRANNO:=	39724408	;
        vlcur_solicitudes(1).FITRANNOACT:=	39724407	;
                
                
        vlcur_solicitudes(2).FIOCUID:=	108	;
        vlcur_solicitudes(2).FCCTENOMBRE:=	'Henry'	;
        vlcur_solicitudes(2).FCCTEAPATERNO:=	'Johnson'	;
        vlcur_solicitudes(2).FCCTEAMATERNO:=	'Hann'	;
        vlcur_solicitudes(2).FCCTEDIRCALLE:=	'2DA CDA DE LA CRUZ'	;
        vlcur_solicitudes(2).FCCTEDIRNOEXT:=	'M 18'	;
        vlcur_solicitudes(2).FCCTEDIRNOINT:=	'L 5'	;
        vlcur_solicitudes(2).FCCTECP:=	1857	;
        vlcur_solicitudes(2).FCCTECOLONIA:=	'LOMAS DE CHAMONTOYA'	;
        vlcur_solicitudes(2).FCCTESEXO:=	'F'	;
        vlcur_solicitudes(2).FCCTETEL:=	5574961104	;
        vlcur_solicitudes(2).FCCTERFC:=	'FOSA830607GL2'	;
        vlcur_solicitudes(2).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(2).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(2).FDCTEFECALT:=	SYSDATE;
        vlcur_solicitudes(2).FICTEECO:=	NULL	;
        vlcur_solicitudes(2).FIEDOCIVIL:=	1	;
        vlcur_solicitudes(2).FNLINEACRED:=	0	;
        vlcur_solicitudes(2).FDCTEFECNAC:=	NULL;
        vlcur_solicitudes(2).FCNOCOBRADOR:=NULL		;
        vlcur_solicitudes(2).FITRANNO:=	40103019	;
        vlcur_solicitudes(2).FITRANNOACT:=	40103018	;
                
                
        vlcur_solicitudes(3).FIOCUID:=	70	;
        vlcur_solicitudes(3).FCCTENOMBRE:=	'Barney'	;
        vlcur_solicitudes(3).FCCTEAPATERNO:=	'Gomez'	;
        vlcur_solicitudes(3).FCCTEAMATERNO:=	'J.'	;
        vlcur_solicitudes(3).FCCTEDIRCALLE:=	'PIEDRA CUADRARA'	;
        vlcur_solicitudes(3).FCCTEDIRNOEXT:=	'M 14'	;
        vlcur_solicitudes(3).FCCTEDIRNOINT:=	'L 5'	;
        vlcur_solicitudes(3).FCCTECP:=	1490	;
        vlcur_solicitudes(3).FCCTECOLONIA:=	'LA CASCADA'	;
        vlcur_solicitudes(3).FCCTESEXO:=	'M'	;
        vlcur_solicitudes(3).FCCTETEL:=	5587267500	;
        vlcur_solicitudes(3).FCCTERFC:=	'SARM550314JD0'	;
        vlcur_solicitudes(3).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(3).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(3).FDCTEFECALT:=	SYSDATE	;
        vlcur_solicitudes(3).FICTEECO:=		NULL;
        vlcur_solicitudes(3).FIEDOCIVIL:=	2	;
        vlcur_solicitudes(3).FNLINEACRED:=	0	;
        vlcur_solicitudes(3).FDCTEFECNAC:=NULL;
        vlcur_solicitudes(3).FCNOCOBRADOR:=	NULL	;
        vlcur_solicitudes(3).FITRANNO:=	40224016	;
        vlcur_solicitudes(3).FITRANNOACT:=	40224015	;
            
                
        vlcur_solicitudes(4).FIOCUID:=	108	;
        vlcur_solicitudes(4).FCCTENOMBRE:=	'Donkey'	;
        vlcur_solicitudes(4).FCCTEAPATERNO:=	'Kong'	;
        vlcur_solicitudes(4).FCCTEAMATERNO:=	'Jr'	;
        vlcur_solicitudes(4).FCCTEDIRCALLE:=	'PROL MERCADELA'	;
        vlcur_solicitudes(4).FCCTEDIRNOEXT:=	'M 21'	;
        vlcur_solicitudes(4).FCCTEDIRNOINT:=	'L 15'	;
        vlcur_solicitudes(4).FCCTECP:=	1840	;
        vlcur_solicitudes(4).FCCTECOLONIA:=	'TORRES DE POTRERO'	;
        vlcur_solicitudes(4).FCCTESEXO:=	'F'	;
        vlcur_solicitudes(4).FCCTETEL:=	5516859298	;
        vlcur_solicitudes(4).FCCTERFC:=	'GASN541206AJ2'	;
        vlcur_solicitudes(4).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(4).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(4).FDCTEFECALT:=	SYSDATE;
        vlcur_solicitudes(4).FICTEECO:=	NULL	;
        vlcur_solicitudes(4).FIEDOCIVIL:=	2	;
        vlcur_solicitudes(4).FNLINEACRED:=	0	;
        vlcur_solicitudes(4).FDCTEFECNAC:=	NULL	;
        vlcur_solicitudes(4).FCNOCOBRADOR:=	NULL	;
        vlcur_solicitudes(4).FITRANNO:=	40223684	;
        vlcur_solicitudes(4).FITRANNOACT:=	40223683	;
                
                
        vlcur_solicitudes(5).FIOCUID:=	70	;
        vlcur_solicitudes(5).FCCTENOMBRE:=	'Naomi'	;
        vlcur_solicitudes(5).FCCTEAPATERNO:=	'Campbell'	;
        vlcur_solicitudes(5).FCCTEAMATERNO:=	'Sexx'	;
        vlcur_solicitudes(5).FCCTEDIRCALLE:=	'C HOLCA'	;
        vlcur_solicitudes(5).FCCTEDIRNOEXT:=	'M 856'	;
        vlcur_solicitudes(5).FCCTEDIRNOINT:=	'L 13'	;
        vlcur_solicitudes(5).FCCTECP:=	14100	;
        vlcur_solicitudes(5).FCCTECOLONIA:=	'PEDREGAL DE SAN NICOLAS'	;
        vlcur_solicitudes(5).FCCTESEXO:=	'F'	;
        vlcur_solicitudes(5).FCCTETEL:=	5518423581	;
        vlcur_solicitudes(5).FCCTERFC:=	'SAMK940430KH3'	;
        vlcur_solicitudes(5).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(5).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(5).FDCTEFECALT:=	SYSDATE	;
        vlcur_solicitudes(5).FICTEECO:=NULL		;
        vlcur_solicitudes(5).FIEDOCIVIL:=	1	;
        vlcur_solicitudes(5).FNLINEACRED:=	0	;
        vlcur_solicitudes(5).FDCTEFECNAC:=	NULL	;
        vlcur_solicitudes(5).FCNOCOBRADOR:= NULL		;
        vlcur_solicitudes(5).FITRANNO:=	40222118	;
        vlcur_solicitudes(5).FITRANNOACT:=	40222117	;
                
                
        vlcur_solicitudes(6).FIOCUID:=	108	;
        vlcur_solicitudes(6).FCCTENOMBRE:=	'Adolfo'	;
        vlcur_solicitudes(6).FCCTEAPATERNO:=	'Hutlas'	;
        vlcur_solicitudes(6).FCCTEAMATERNO:=	'Hutlas'	;
        vlcur_solicitudes(6).FCCTEDIRCALLE:=	'AV SAN ISIDRO ALTO LERMA'	;
        vlcur_solicitudes(6).FCCTEDIRNOEXT:=	6	;
        vlcur_solicitudes(6).FCCTEDIRNOINT:=	'LOCA6'	;
        vlcur_solicitudes(6).FCCTECP:=	1530	;
        vlcur_solicitudes(6).FCCTECOLONIA:=	'CORPUS CHRISTY'	;
        vlcur_solicitudes(6).FCCTESEXO:=	'M'	;
        vlcur_solicitudes(6).FCCTETEL:=		NULL;
        vlcur_solicitudes(6).FCCTERFC:=	'FOPJ920829'	;
        vlcur_solicitudes(6).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(6).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(6).FDCTEFECALT:=	SYSDATE	;
        vlcur_solicitudes(6).FICTEECO:=		NULL;
        vlcur_solicitudes(6).FIEDOCIVIL:=	1	;
        vlcur_solicitudes(6).FNLINEACRED:=	0	;
        vlcur_solicitudes(6).FDCTEFECNAC:=	NULL	;
        vlcur_solicitudes(6).FCNOCOBRADOR:=	NULL	;
        vlcur_solicitudes(6).FITRANNO:=	40612231	;
        vlcur_solicitudes(6).FITRANNOACT:=	40642524	;
                
                
        vlcur_solicitudes(7).FIOCUID:=	108	;
        vlcur_solicitudes(7).FCCTENOMBRE:=	'Lucy'	;
        vlcur_solicitudes(7).FCCTEAPATERNO:=	'Sams'	;
        vlcur_solicitudes(7).FCCTEAMATERNO:=	'Loretta'	;
        vlcur_solicitudes(7).FCCTEDIRCALLE:=	'C 3'	;
        vlcur_solicitudes(7).FCCTEDIRNOEXT:=	'M 3'	;
        vlcur_solicitudes(7).FCCTEDIRNOINT:=	'L 33'	;
        vlcur_solicitudes(7).FCCTECP:=	1790	;
        vlcur_solicitudes(7).FCCTECOLONIA:=	'LOMAS DE TETELPAN'	;
        vlcur_solicitudes(7).FCCTESEXO:=	'F'	;
        vlcur_solicitudes(7).FCCTETEL:=	5583293235	;
        vlcur_solicitudes(7).FCCTERFC:=	'MASL0002035S2'	;
        vlcur_solicitudes(7).FCCTEFISMOR:=	'FI'	;
        vlcur_solicitudes(7).FITDAATIENDE:=	2024	;
        vlcur_solicitudes(7).FDCTEFECALT:=	SYSDATE	;
        vlcur_solicitudes(7).FICTEECO:=	NULL	;
        vlcur_solicitudes(7).FIEDOCIVIL:=	4	;
        vlcur_solicitudes(7).FNLINEACRED:=	0	;
        vlcur_solicitudes(7).FDCTEFECNAC:=	NULL	;
        vlcur_solicitudes(7).FCNOCOBRADOR:=		NULL;
        vlcur_solicitudes(7).FITRANNO:=	41094303	;
        vlcur_solicitudes(7).FITRANNOACT:=	41094302	;
        
        
        /*TACREDSOLICITUD*/
        
        --generar un numero aleatorio para dias de la fecha status
        vl_numDias:=DBMS_RANDOM.value(1,7);   
        
        vlcur_solicitudes(1).FDFECVISITA:=	SYSDATE-	vl_numDias	; --CHECAR
        vlcur_solicitudes(1).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(1).FISTAT:=	5	;
        vlcur_solicitudes(1).FDFECSTAT:=	SYSDATE-vl_numDias	;--CHECAR
        vlcur_solicitudes(1).FIRECHAZOID:=	0	;
        vlcur_solicitudes(1).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(1).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);--CHECAR
        vlcur_solicitudes(1).FIACEPTAPP:=	0	;
        vlcur_solicitudes(1).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(1).FNCAPACIDADPAGO:=	300	;
        vlcur_solicitudes(1).FIPLAZO:=	80	;
                
        vl_numDias:=DBMS_RANDOM.value(1,7);   
        vlcur_solicitudes(2).FDFECVISITA:=	SYSDATE-	vl_numDias	;
        vlcur_solicitudes(2).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(2).FISTAT:=	30	;
        vlcur_solicitudes(2).FDFECSTAT:=	SYSDATE -	vl_numDias;
        vlcur_solicitudes(2).FIRECHAZOID:=	0	;
        vlcur_solicitudes(2).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(2).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);
        vlcur_solicitudes(2).FIACEPTAPP:=	0	;
        vlcur_solicitudes(2).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(2).FNCAPACIDADPAGO:=	225	;
        vlcur_solicitudes(2).FIPLAZO:=	52	;
                
        vl_numDias:=DBMS_RANDOM.value(1,7);   		
        vlcur_solicitudes(3).FDFECVISITA:=	SYSDATE-	vl_numDias	;
        vlcur_solicitudes(3).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(3).FISTAT:=	5	;
        vlcur_solicitudes(3).FDFECSTAT:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(3).FIRECHAZOID:=	0	;
        vlcur_solicitudes(3).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(3).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);
        vlcur_solicitudes(3).FIACEPTAPP:=	0	;
        vlcur_solicitudes(3).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(3).FNCAPACIDADPAGO:=	500	;
        vlcur_solicitudes(3).FIPLAZO:=	52	;
                
        vl_numDias:=DBMS_RANDOM.value(1,7);   	
        vlcur_solicitudes(4).FDFECVISITA:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(4).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(4).FISTAT:=	5	;
        vlcur_solicitudes(4).FDFECSTAT:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(4).FIRECHAZOID:=	0	;
        vlcur_solicitudes(4).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(4).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);
        vlcur_solicitudes(4).FIACEPTAPP:=	0	;
        vlcur_solicitudes(4).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(4).FNCAPACIDADPAGO:=	200	;
        vlcur_solicitudes(4).FIPLAZO:=	100	;
                
         vl_numDias:=DBMS_RANDOM.value(1,7);   		
        vlcur_solicitudes(5).FDFECVISITA:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(5).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(5).FISTAT:=	5	;
        vlcur_solicitudes(5).FDFECSTAT:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(5).FIRECHAZOID:=	0	;
        vlcur_solicitudes(5).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(5).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);
        vlcur_solicitudes(5).FIACEPTAPP:=	0	;
        vlcur_solicitudes(5).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(5).FNCAPACIDADPAGO:=	225	;
        vlcur_solicitudes(5).FIPLAZO:=	100	;
                
         vl_numDias:=DBMS_RANDOM.value(1,7);   		
        vlcur_solicitudes(6).FDFECVISITA:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(6).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(6).FISTAT:=	6	;
        vlcur_solicitudes(6).FDFECSTAT:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(6).FIRECHAZOID:=	0	;
        vlcur_solicitudes(6).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(6).FDFECSOLICITUD:=	SYSDATE	-(vl_numDias+2);
        vlcur_solicitudes(6).FIACEPTAPP:=	0	;
        vlcur_solicitudes(6).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(6).FNCAPACIDADPAGO:=	0	;
        vlcur_solicitudes(6).FIPLAZO:=	100	;
                
        vl_numDias:=DBMS_RANDOM.value(1,7);   		
        vlcur_solicitudes(7).FDFECVISITA:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(7).FCINFORMANTE:=	'CLIENTE'	;
        vlcur_solicitudes(7).FISTAT:=	9	;
        vlcur_solicitudes(7).FDFECSTAT:=	SYSDATE	-	vl_numDias;
        vlcur_solicitudes(7).FIRECHAZOID:=	24	;
        vlcur_solicitudes(7).FCEJECUTIVO:=	189564	;
        vlcur_solicitudes(7).FDFECSOLICITUD:=	SYSDATE-(vl_numDias+2)	;
        vlcur_solicitudes(7).FIACEPTAPP:=	0	;
        vlcur_solicitudes(7).FITIPOAUTORIZACION:=	1	;
        vlcur_solicitudes(7).FNCAPACIDADPAGO:=	160	;
        vlcur_solicitudes(7).FIPLAZO:=	0	;
        
        SCVENTASTIENDA.TEST_PAAPPLICATION.SPINSERTSOLI( vlcur_solicitudes, vl_coderror, vl_deserror);
        
        ut.expect(l_actual).to_equal(l_expected);
        
    EXCEPTION
        WHEN OTHERS THEN
            vl_coderror := sqlcode;
            vl_deserror := substr(sqlerrm,csl_0,csl_100);
            vl_mensaje := 'OCURRIO UN ERROR AL INSERTAR SOLICITUDES';
      
   END spqaplicationv2;
   
   
   PROCEDURE SPINSERTSOLI(
        pa_collectionsol IN SCVENTASTIENDA.TEST_PAAPPLICATION.typ_solicitud,
        pa_coderror       OUT INTEGER,
        pa_deserror       OUT VARCHAR2) 
    IS
         VL_EXISTECRED NUMBER:=0;
    BEGIN
        
      FOR VICONTADOR IN pa_collectionsol.FIRST .. pa_collectionsol.LAST
        LOOP
          SELECT COUNT(1)
             INTO VL_EXISTECRED
             FROM SCVENTASTIENDA.TACREDSOLICITUD T
             WHERE  T.fipais=pa_collectionsol(VICONTADOR).FIPAIS
               AND      T.ficanal=pa_collectionsol(VICONTADOR).FICANAL
               AND      T.fisucursal=pa_collectionsol(VICONTADOR).FISUCURSAL
               AND      T.fisolicitudid=pa_collectionsol(VICONTADOR).fisolicitudid;
             
          IF    VL_EXISTECRED=0 THEN    
            INSERT INTO SCVENTASTIENDA.TACREDSOLICITUD(
              fipais, 
              ficanal, 
              fisucursal, 
              fisolicitudid, 
              fiidnegocio, 
              fiidtienda, 
              fiidcliente, 
              fitiposolicitud, 
              fifolioparam, 
              fdfecvisita, 
              fcinformante, 
              fistat, 
              fisubstat, 
              fdfecstat, 
              firechazoid, 
              fcejecutivo, 
              fdfecsolicitud, 
              fitranno, 
              fiaceptapp, 
              fitipoautorizacion, 
              fncapacidadpago, 
              fiplazo, 
              fdcreacion, 
              fdmodifico, 
              fcusrmodifico   
            )VALUES(
              pa_collectionsol(VICONTADOR).fipais, 
              pa_collectionsol(VICONTADOR).ficanal, 
              pa_collectionsol(VICONTADOR).fisucursal, 
              pa_collectionsol(VICONTADOR).fisolicitudid, 
              pa_collectionsol(VICONTADOR).fiidnegocio, 
              pa_collectionsol(VICONTADOR).fiidtienda, 
              pa_collectionsol(VICONTADOR).fiidcliente, 
              pa_collectionsol(VICONTADOR).fitiposolicitud, 
              pa_collectionsol(VICONTADOR).fifolioparam, 
              pa_collectionsol(VICONTADOR).fdfecvisita, 
              pa_collectionsol(VICONTADOR).fcinformante, 
              pa_collectionsol(VICONTADOR).fistat, 
              pa_collectionsol(VICONTADOR).fisubstat, 
              pa_collectionsol(VICONTADOR).fdfecstat, 
              pa_collectionsol(VICONTADOR).firechazoid, 
              pa_collectionsol(VICONTADOR).fcejecutivo, 
              pa_collectionsol(VICONTADOR).fdfecsolicitud, 
              pa_collectionsol(VICONTADOR).fitranno, 
              pa_collectionsol(VICONTADOR).fiaceptapp, 
              pa_collectionsol(VICONTADOR).fitipoautorizacion, 
              pa_collectionsol(VICONTADOR).fncapacidadpago, 
              pa_collectionsol(VICONTADOR).fiplazo, 
              pa_collectionsol(VICONTADOR).fdcreacion, 
               SYSDATE ,
                CSL_USR
            );
          END IF;
          
          SELECT COUNT(1)
             INTO VL_EXISTECRED
             FROM SCVENTASTIENDA.TASOLICITUDES T
             WHERE  T.fipais=pa_collectionsol(VICONTADOR).FIPAIS
               AND      T.ficanal=pa_collectionsol(VICONTADOR).FICANAL
               AND      T.fisucursal=pa_collectionsol(VICONTADOR).FISUCURSAL
               AND      T.fisolicitudid=pa_collectionsol(VICONTADOR).fisolicitudid;
               
          IF VL_EXISTECRED=0 THEN     
      
            INSERT INTO SCVENTASTIENDA.TASOLICITUDES(
              fipais, 
              ficanal, 
              fisucursal, 
              fisolicitudid, 
              fiidnegocio, 
              fiidtienda, 
              fiidcliente, 
              fitiposolicitud, 
              fifolioparam, 
              fcempno, 
              fisubstat, 
              fisolcompleta, 
              fiine, 
              ficompdomicilio, 
              ficompingresos, 
              fifirmacontrato, 
              fivisitajvc, 
              fiautorizada, 
              filcrsintaz, 
              filcrcontaz, 
              filiberada, 
              fnmonto, 
              fcobservaciones, 
              fdcreacion, 
              fdmodifico, 
              fcusrmodifico
            )VALUES(
              pa_collectionsol(VICONTADOR).fipais, 
              pa_collectionsol(VICONTADOR).ficanal, 
              pa_collectionsol(VICONTADOR).fisucursal, 
              pa_collectionsol(VICONTADOR).fisolicitudid, 
              pa_collectionsol(VICONTADOR).fiidnegocio, 
              pa_collectionsol(VICONTADOR).fiidtienda, 
              pa_collectionsol(VICONTADOR).fiidcliente, 
              pa_collectionsol(VICONTADOR).fitiposolicitud, 
              pa_collectionsol(VICONTADOR).fifolioparam, 
              pa_collectionsol(VICONTADOR).fcempno, 
              pa_collectionsol(VICONTADOR).fisubstat, 
              pa_collectionsol(VICONTADOR).fisolcompleta, 
              pa_collectionsol(VICONTADOR).fiine, 
              pa_collectionsol(VICONTADOR).ficompdomicilio, 
              pa_collectionsol(VICONTADOR).ficompingresos, 
              pa_collectionsol(VICONTADOR).fifirmacontrato, 
              pa_collectionsol(VICONTADOR).fivisitajvc, 
              pa_collectionsol(VICONTADOR).fiautorizada, 
              pa_collectionsol(VICONTADOR).filcrsintaz, 
              pa_collectionsol(VICONTADOR).filcrcontaz, 
              pa_collectionsol(VICONTADOR).filiberada, 
              pa_collectionsol(VICONTADOR).fnmonto, 
              pa_collectionsol(VICONTADOR).fcobservaciones, 
              pa_collectionsol(VICONTADOR).fdcreacion, 
              SYSDATE ,
              CSL_USR
          
            );
          END IF; 
          
          INSERT INTO SCVENTASTIENDA.TACREDCTECTES(
                fipais, 
                ficanal, 
                fisucursal, 
                fiidnegocio, 
                fiidtienda, 
                fiidcliente, 
                fingcioid, 
                finotienda, 
                ficteid, 
                fidigitover, 
               -- fdfechaalta, 
                fdcreacion, 
                fdmodifico, 
                fcusrmodifico
          )VALUES(
                pa_collectionsol(VICONTADOR).fipais, 
                pa_collectionsol(VICONTADOR).ficanal, 
                pa_collectionsol(VICONTADOR).fisucursal, 
                pa_collectionsol(VICONTADOR).fiidnegocio, 
                pa_collectionsol(VICONTADOR).fiidtienda, 
                pa_collectionsol(VICONTADOR).fiidcliente, 
                pa_collectionsol(VICONTADOR).fingcioid, 
                pa_collectionsol(VICONTADOR).finotienda, 
                pa_collectionsol(VICONTADOR).ficteid, 
                pa_collectionsol(VICONTADOR).fidigitover, 
               -- pa_collectionsol(VICONTADOR).fdfechaalta, 
                pa_collectionsol(VICONTADOR).fdcreacion, 
                SYSDATE ,
                CSL_USR
          );
       
          SELECT COUNT(1)
             INTO VL_EXISTECRED
             FROM SCVENTASTIENDA.TACENCTETIENDA T
             WHERE  T.fipais=pa_collectionsol(VICONTADOR).FIPAIS
               AND      T.ficanal=pa_collectionsol(VICONTADOR).FICANAL
               AND      T.fisucursal=pa_collectionsol(VICONTADOR).FISUCURSAL
               AND      T.fifolio=pa_collectionsol(VICONTADOR).fifolio;
           
          
          IF   VL_EXISTECRED=0 THEN
          
            INSERT INTO SCVENTASTIENDA.TACENCTETIENDA(
                fipais, 
                ficanal, 
                fisucursal, 
                fingcioid, 
                finotienda, 
                ficteid, 
                fidigitover, 
                fifolio, 
                fipaiscu, 
                ficanalcu, 
                fisucursalcu, 
               -- fdfechaalta, 
                fdcreacion, 
                fdmodifico, 
                fcusrmodifico
            )VALUES(
                pa_collectionsol(VICONTADOR).fipais, 
                pa_collectionsol(VICONTADOR).ficanal, 
                pa_collectionsol(VICONTADOR).fisucursal, 
                pa_collectionsol(VICONTADOR).fingcioid, 
                pa_collectionsol(VICONTADOR).finotienda, 
                pa_collectionsol(VICONTADOR).ficteid, 
                pa_collectionsol(VICONTADOR).fidigitover, 
                pa_collectionsol(VICONTADOR).fifolio, 
                pa_collectionsol(VICONTADOR).fipaiscu, 
                pa_collectionsol(VICONTADOR).ficanalcu, 
                pa_collectionsol(VICONTADOR).fisucursalcu, 
               -- pa_collectionsol(VICONTADOR).fdfechaalta, 
                pa_collectionsol(VICONTADOR).fdcreacion, 
                SYSDATE ,
                CSL_USR
            );
          ELSE 
            UPDATE SCVENTASTIENDA.TACENCTETIENDA T
               SET  fingcioid=pa_collectionsol(VICONTADOR).fingcioid, 
                    finotienda=pa_collectionsol(VICONTADOR).finotienda, 
                    ficteid=pa_collectionsol(VICONTADOR).ficteid, 
                    fidigitover=pa_collectionsol(VICONTADOR).fidigitover, 
                    fipaiscu=pa_collectionsol(VICONTADOR).fipaiscu, 
                    ficanalcu=pa_collectionsol(VICONTADOR).ficanalcu, 
                    fisucursalcu=pa_collectionsol(VICONTADOR).fisucursalcu
             WHERE   T.fipais=pa_collectionsol(VICONTADOR).FIPAIS
               AND      T.ficanal=pa_collectionsol(VICONTADOR).FICANAL
               AND      T.fisucursal=pa_collectionsol(VICONTADOR).FISUCURSAL
               AND      T.fifolio=pa_collectionsol(VICONTADOR).fifolio;
           
         
          END IF;
      
          SELECT COUNT(1)
             INTO VL_EXISTECRED
             FROM SCVENTASTIENDA.TACLIENTES T
             WHERE FIPAIS=pa_collectionsol(VICONTADOR).FIPAIS
              AND  FICANAL=pa_collectionsol(VICONTADOR).FICANAL
              AND  FISUCURSAL=pa_collectionsol(VICONTADOR).FISUCURSAL
              AND  FINGCIOID =pa_collectionsol(VICONTADOR).FINGCIOID
              AND  FINOTIENDA=pa_collectionsol(VICONTADOR).FINOTIENDA
              AND  FICTEID=pa_collectionsol(VICONTADOR).FICTEID
              AND  FIDIGITOVER=pa_collectionsol(VICONTADOR).FIDIGITOVER;
            
          IF  VL_EXISTECRED = 0 THEN
          
            INSERT INTO SCVENTASTIENDA.TACLIENTES(
              fipais, 
              ficanal, 
              fisucursal, 
              fingcioid, 
              finotienda, 
              ficteid, 
              fidigitover, 
              fiocuid, 
              fcctenombre, 
              fccteapaterno, 
              fccteamaterno, 
              fcctedircalle, 
              fcctedirnoext, 
              fcctedirnoint, 
              fcctecp, 
              fcctecolonia, 
              fcctesexo, 
              fcctetel, 
              fccterfc, 
              fcctefismor, 
              fitdaatiende, 
              --  fdctefecalt, 
              ficteeco, 
              fiedocivil, 
              fnlineacred, 
               -- fdctefecnac, 
              fcnocobrador, 
              fitranno, 
              fitrannoact, 
              fdcreacion, 
              fdmodifico, 
              fcusrmodifico
            )VALUES(
              pa_collectionsol(VICONTADOR).fipais, 
              pa_collectionsol(VICONTADOR).ficanal, 
              pa_collectionsol(VICONTADOR).fisucursal, 
              pa_collectionsol(VICONTADOR).fingcioid, 
              pa_collectionsol(VICONTADOR).finotienda, 
              pa_collectionsol(VICONTADOR).ficteid, 
              pa_collectionsol(VICONTADOR).fidigitover, 
              pa_collectionsol(VICONTADOR).fiocuid, 
              pa_collectionsol(VICONTADOR).fcctenombre, 
              pa_collectionsol(VICONTADOR).fccteapaterno, 
              pa_collectionsol(VICONTADOR).fccteamaterno, 
              pa_collectionsol(VICONTADOR).fcctedircalle, 
              pa_collectionsol(VICONTADOR).fcctedirnoext, 
              pa_collectionsol(VICONTADOR).fcctedirnoint, 
              pa_collectionsol(VICONTADOR).fcctecp, 
              pa_collectionsol(VICONTADOR).fcctecolonia, 
              pa_collectionsol(VICONTADOR).fcctesexo, 
              pa_collectionsol(VICONTADOR).fcctetel, 
              pa_collectionsol(VICONTADOR).fccterfc, 
              pa_collectionsol(VICONTADOR).fcctefismor, 
              pa_collectionsol(VICONTADOR).fitdaatiende, 
             -- pa_collectionsol(VICONTADOR).fdctefecalt, 
              pa_collectionsol(VICONTADOR).ficteeco, 
              pa_collectionsol(VICONTADOR).fiedocivil, 
              pa_collectionsol(VICONTADOR).fnlineacred, 
             -- pa_collectionsol(VICONTADOR).fdctefecnac, 
              pa_collectionsol(VICONTADOR).fcnocobrador, 
              pa_collectionsol(VICONTADOR).fitranno, 
              pa_collectionsol(VICONTADOR).fitrannoact, 
              pa_collectionsol(VICONTADOR).fdcreacion, 
              SYSDATE ,
              CSL_USR
            );
          END IF;
          
      END LOOP;
      COMMIT;  
    
    EXCEPTION
        WHEN OTHERS THEN
          ROLLBACK;
            pa_coderror := sqlcode;
            pa_deserror := substr(sqlerrm,csl_0,csl_100);    
        
    END SPINSERTSOLI;
   
   --
   -- test spresqaplicationv2 case 1: ...
   --
   PROCEDURE spresqaplicationv2 IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      -- paapplication.spqresaplicationv2;

      -- populate expected
      -- ...

      -- assert
      DELETE FROM SCVENTASTIENDA.TASOLICITUDES T
      WHERE T.FCUSRMODIFICO=csl_usr;

      DELETE FROM SCVENTASTIENDA.TACREDSOLICITUD T
      WHERE T.FCUSRMODIFICO=csl_usr;

      DELETE FROM SCVENTASTIENDA.TACREDCTECTES T
      WHERE T.FCUSRMODIFICO=csl_usr;

      DELETE FROM SCVENTASTIENDA.TACENCTETIENDA T
      WHERE T.FCUSRMODIFICO=csl_usr;

      DELETE FROM SCVENTASTIENDA.TACLIENTES T
      WHERE T.FCUSRMODIFICO=csl_usr;

      ut.expect(l_actual).to_equal(l_expected);
   END spresqaplicationv2;

END test_paapplication;

/
