--------------------------------------------------------
--  DDL for Table TACATESTRUCTURA
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TACATESTRUCTURA" 
   (	"FCEST_NOMBRE" VARCHAR2(30 CHAR), 
	"FCEST_OWNER" VARCHAR2(40 CHAR), 
	"FCSP_NAME" VARCHAR2(30 CHAR), 
	"FIEST_LENGTH" NUMBER(5,0), 
	"FIEST_PAIS" NUMBER(5,0), 
	"FIEST_CANAL" NUMBER(5,0), 
	"FIEST_TIPO_REG" NUMBER(5,0), 
	"FCEST_TIPO_EST" VARCHAR2(5 CHAR), 
	"FARRESTRUC_ARRAY" "SCACTUALIZADORVT"."ARR_ESTRUCTURA_TAEST" , 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACATESTRU_DAT" 
 VARRAY "FARRESTRUC_ARRAY" STORE AS SECUREFILE LOB 
  ( TABLESPACE "SCACT_TACATESTRU_DAT" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACATESTRUCTURA" TO "USRINFFENIX";
