--------------------------------------------------------
--  DDL for Table TACTRLERRORES
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TACTRLERRORES" 
   (	"FITIPOAPLICACION" NUMBER(5,0), 
	"FICONSEC" NUMBER(5,0), 
	"FDFECHASURGIO" DATE, 
	"FCORIGINO" VARCHAR2(100 CHAR), 
	"FINUMERO" NUMBER(5,0), 
	"FCMENSAJE" VARCHAR2(500 CHAR), 
	"FCCAUSA" VARCHAR2(3600 CHAR), 
	"FISTATUS" NUMBER(5,0), 
	"FDERRORSOL" DATE DEFAULT TO_DATE('1901-01-01', 'YYYY-MM-DD'), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLERRO_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACTRLERRORES" TO "USRINFFENIX";
