--------------------------------------------------------
--  DDL for Table TACTRLTIPTRANS
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TACTRLTIPTRANS" 
   (	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FITRANTIPO" NUMBER(5,0), 
	"FICONSECTIPO" NUMBER(10,0), 
	"FDFEC_ULT_DISP" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "PTACTRL_CONSEC_TIPTRAN1"  VALUES LESS THAN (218) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP01_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN2"  VALUES LESS THAN (596) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP02_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN3"  VALUES LESS THAN (988) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP03_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN4"  VALUES LESS THAN (1388) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP04_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN5"  VALUES LESS THAN (1714) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP05_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN6"  VALUES LESS THAN (2049) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP06_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN7"  VALUES LESS THAN (2190) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP07_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN8"  VALUES LESS THAN (2533) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP08_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN9"  VALUES LESS THAN (3061) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP09_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN10"  VALUES LESS THAN (3422) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP10_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN11"  VALUES LESS THAN (3885) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP11_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN12"  VALUES LESS THAN (4609) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP12_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN13"  VALUES LESS THAN (5117) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP13_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN14"  VALUES LESS THAN (5695) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP14_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN15"  VALUES LESS THAN (6212) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP15_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN16"  VALUES LESS THAN (6937) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP16_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN17"  VALUES LESS THAN (7444) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP17_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN18"  VALUES LESS THAN (8337) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP18_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN19"  VALUES LESS THAN (8964) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP19_DAT" , 
 PARTITION "PTACTRL_CONSEC_TIPTRAN20"  VALUES LESS THAN (10000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TACTRLCONS_RP20_DAT" ) ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TACTRLTIPTRANS" TO "USRINFFENIX";
