--------------------------------------------------------
--  DDL for Table TAREGISTRO
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TAREGISTRO" 
   (	"FITIPOREG" NUMBER(5,0), 
	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FCREG_DESC" VARCHAR2(100 CHAR), 
	"FIREG_ESTATUS" NUMBER(1,0) DEFAULT 1, 
	"FIREG_ACCION" NUMBER(1,0) DEFAULT 1, 
	"FCREG_SP_NAME" VARCHAR2(30 CHAR), 
	"FCREG_COMEN" VARCHAR2(100 CHAR), 
	"FCSTOREPROC" VARCHAR2(40 CHAR), 
	"FCORA_USR" VARCHAR2(40 CHAR), 
	"FDFECHA_ALTA" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TAREGISTRO_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TAREGISTRO" TO "USRINFFENIX";
