--------------------------------------------------------
--  DDL for Table TATRNCRCBH
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TATRNCRCBH" 
   (	"FIPAISID" NUMBER(5,0) DEFAULT 1, 
	"FICANAL" NUMBER(5,0) DEFAULT 1, 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FITRANTIPO" NUMBER(5,0), 
	"FICONSECTIPO" NUMBER(10,0), 
	"FDTRANSFECHR" DATE, 
	"FCTRANWS" VARCHAR2(10 CHAR), 
	"FCTRANUSR" VARCHAR2(10 CHAR), 
	"FITRANNOREG" NUMBER(5,0), 
	"FITRANSMIT" NUMBER(5,0), 
	"FDFECHARECEP" DATE DEFAULT SYSDATE, 
	"FDFECHAPROCESA" DATE DEFAULT SYSDATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "PTATRANCRECABHIST1"  VALUES LESS THAN (218) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP01_DAT" , 
 PARTITION "PTATRANCRECABHIST2"  VALUES LESS THAN (596) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP02_DAT" , 
 PARTITION "PTATRANCRECABHIST3"  VALUES LESS THAN (988) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP03_DAT" , 
 PARTITION "PTATRANCRECABHIST4"  VALUES LESS THAN (1388) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP04_DAT" , 
 PARTITION "PTATRANCRECABHIST5"  VALUES LESS THAN (1714) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP05_DAT" , 
 PARTITION "PTATRANCRECABHIST6"  VALUES LESS THAN (2049) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP06_DAT" , 
 PARTITION "PTATRANCRECABHIST7"  VALUES LESS THAN (2190) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP07_DAT" , 
 PARTITION "PTATRANCRECABHIST8"  VALUES LESS THAN (2533) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP08_DAT" , 
 PARTITION "PTATRANCRECABHIST9"  VALUES LESS THAN (3061) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP09_DAT" , 
 PARTITION "PTATRANCRECABHIST10"  VALUES LESS THAN (3422) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP10_DAT" , 
 PARTITION "PTATRANCRECABHIST11"  VALUES LESS THAN (3885) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP11_DAT" , 
 PARTITION "PTATRANCRECABHIST12"  VALUES LESS THAN (4609) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP12_DAT" , 
 PARTITION "PTATRANCRECABHIST13"  VALUES LESS THAN (5117) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP13_DAT" , 
 PARTITION "PTATRANCRECABHIST14"  VALUES LESS THAN (5695) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP14_DAT" , 
 PARTITION "PTATRANCRECABHIST15"  VALUES LESS THAN (6212) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP15_DAT" , 
 PARTITION "PTATRANCRECABHIST16"  VALUES LESS THAN (6937) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP16_DAT" , 
 PARTITION "PTATRANCRECABHIST17"  VALUES LESS THAN (7444) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP17_DAT" , 
 PARTITION "PTATRANCRECABHIST18"  VALUES LESS THAN (8337) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP18_DAT" , 
 PARTITION "PTATRANCRECABHIST19"  VALUES LESS THAN (8964) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP19_DAT" , 
 PARTITION "PTATRANCRECABHIST20"  VALUES LESS THAN (10000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TATRANCABH_RP20_DAT" ) ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBH" TO "USRINFFENIX";
