--------------------------------------------------------
--  DDL for Table TATRNCRCBHL
--------------------------------------------------------

  CREATE TABLE "SCACTUALIZADORVT"."TATRNCRCBHL" 
   (	"ORA_ERR_NUMBER$" NUMBER, 
	"ORA_ERR_MESG$" VARCHAR2(2000 CHAR), 
	"ORA_ERR_ROWID$" UROWID (4000), 
	"ORA_ERR_OPTYP$" VARCHAR2(2 CHAR), 
	"ORA_ERR_TAG$" VARCHAR2(2000 CHAR), 
	"FIPAISID" VARCHAR2(4000 CHAR), 
	"FICANAL" VARCHAR2(4000 CHAR), 
	"FISUCURSAL" VARCHAR2(4000 CHAR), 
	"FITRANNO" VARCHAR2(4000 CHAR), 
	"FITRANTIPO" VARCHAR2(4000 CHAR), 
	"FICONSECTIPO" VARCHAR2(4000 CHAR), 
	"FDTRANSFECHR" VARCHAR2(4000 CHAR), 
	"FCTRANWS" VARCHAR2(4000 CHAR), 
	"FCTRANUSR" VARCHAR2(4000 CHAR), 
	"FITRANNOREG" VARCHAR2(4000 CHAR), 
	"FLTRANSMIT" VARCHAR2(4000 CHAR), 
	"FDFECHARECEP" VARCHAR2(4000 CHAR), 
	"FDFECHAPROCESA" VARCHAR2(4000 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCACT_TRANCHISLO_DAT" ;
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFACTVT";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFACTVT";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFACTVT";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFACTVT";
  GRANT DELETE ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFFENIX";
  GRANT INSERT ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFFENIX";
  GRANT SELECT ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFFENIX";
  GRANT UPDATE ON "SCACTUALIZADORVT"."TATRNCRCBHL" TO "USRINFFENIX";
