--------------------------------------------------------
--  DDL for Type ARR_ESTRUCTURA_TAEST
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."ARR_ESTRUCTURA_TAEST" AS VARRAY (99) OF SCACTUALIZADORVT.TYP_ESTRUCTURA_TAEST;

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."ARR_ESTRUCTURA_TAEST" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."ARR_ESTRUCTURA_TAEST" TO "USRINFFENIX";
