--------------------------------------------------------
--  DDL for Type TB_STRUC_TAEST
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TB_STRUC_TAEST" 
    AS TABLE OF SCACTUALIZADORVT.TYP_ESTRUCTURA_TAEST

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TB_STRUC_TAEST" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TB_STRUC_TAEST" TO "USRINFFENIX";
