--------------------------------------------------------
--  DDL for Type TBTRANCREDET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TBTRANCREDET" 
AS TABLE OF TYPTRANDETALLE

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TBTRANCREDET" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TBTRANCREDET" TO "USRINFFENIX";
