--------------------------------------------------------
--  DDL for Type TYP_TRANCREDET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TYP_TRANCREDET" AS OBJECT (
  FIPAISID   NUMBER(5),
  FICANAL    NUMBER(5),
  FISUCURSAL NUMBER(10),
  FITRANNO   NUMBER(10),
  FICONSDETA NUMBER(10),
  FITIPOREG  NUMBER(5),
  FCDATODETA VARCHAR2(270 CHAR));

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYP_TRANCREDET" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYP_TRANCREDET" TO "USRINFFENIX";
