--------------------------------------------------------
--  DDL for Type TYPTRANCREDET
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TYPTRANCREDET" AS OBJECT (
  FIPAISID   NUMBER(5),
  FICANAL    NUMBER(5),
  FISUCURSAL NUMBER(10),
  FITRANNO   NUMBER(10),
  FICONSDETA NUMBER(10),
  FITIPOREG  NUMBER(5),
  FCDATODETA VARCHAR2(270 CHAR));

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANCREDET" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANCREDET" TO "USRINFFENIX";
