--------------------------------------------------------
--  DDL for Type TYPTRANDETALLE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCACTUALIZADORVT"."TYPTRANDETALLE" AS OBJECT (
  FICONSDETA NUMBER(10),
  FITIPOREG  NUMBER(5),
  FCDATODETA VARCHAR2(270 CHAR));

/

  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANDETALLE" TO "USRACTVT";
  GRANT EXECUTE ON "SCACTUALIZADORVT"."TYPTRANDETALLE" TO "USRINFFENIX";
