--------------------------------------------------------
--  DDL for Package PQFXJOBCECOGEOGRAFIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."PQFXJOBCECOGEOGRAFIA" 
IS
    -- Author  : CCAMPOS
    -- Created : 08/08/2018 04:58:32 p. m.
    -- Purpose : PROCESO QUE TRUNCARA LA TABLA TEMPORAL DE LA GEOGRAFIA


    PROCEDURE SPFXTRUNCATBGEO;

    PROCEDURE SPFXDDEPURATBGEO;
END PQFXJOBCECOGEOGRAFIA;

/

  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRINFSISGES";
  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRSISGES";
