--------------------------------------------------------
--  DDL for Package TEST_PABUZONQYS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PABUZONQYS" IS

   /* generated by utPLSQL for SQL Developer on 2019-03-20 11:49:09 */

   --%suite(test_pabuzonqys)
   --%suitepath(alltests)

   --%test
   PROCEDURE spguardabuzon;

   --%test
   PROCEDURE spobtienecatbuz;

END test_pabuzonqys;

/
