--------------------------------------------------------
--  DDL for Package TEST_PQPLANTILLAEMPLEADOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PQPLANTILLAEMPLEADOS" IS

   /* generated by utPLSQL for SQL Developer on 2019-03-20 17:58:41 */

   --%suite(test_pqplantillaempleados)
   --%suitepath(alltests)

   
   --%test
   -- %displayname(Inserta datos de plantilla)
   PROCEDURE spinsertplantilla;
   
   --%test
   -- %displayname(Consulta la plantilla exitosamente)
   PROCEDURE spcargaplantilla;

END test_pqplantillaempleados;

/
