--------------------------------------------------------
--  DDL for Package TEST_PAFXGESTIONDIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCSISGES"."TEST_PAFXGESTIONDIA" IS

   /* generated by utPLSQL for SQL Developer on 2019-05-09 17:25:56 */

   PROCEDURE deleteDatos;
   
   PROCEDURE insertDatos;

   --%suite(test_pafxgestiondia)
   --%suitepath(alltests)
   
   
   --%test
   PROCEDURE spnumgestionesxniv;


END test_pafxgestiondia;

/
