--------------------------------------------------------
--  DDL for Package PASUPERVISION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "SCVENTASTIENDA"."PASUPERVISION" is
 
  -- Author  : B643963
  -- Created : 08/08/2018 09:15:08 a.m.
  -- Purpose : Paquete para stored de administraci�n de consultas de supervisor

  PROCEDURE SPCONTPEDSUPERV(
   PA_FCNOEMPLEADO IN VARCHAR2
  ,PA_FISUCURSAL IN INTEGER
  ,PA_CONTEO     OUT NUMBER
  ,PA_MENSAJE    OUT VARCHAR2
  ,PA_CODERROR      OUT INTEGER
  ,PA_DESERROR     OUT VARCHAR2);

  PROCEDURE SPCONTPRESUPSUPERV(
   PA_FCNOEMPLEADO IN VARCHAR2
  ,PA_FISUCURSAL IN INTEGER
  ,PA_DIAS IN INTEGER
  ,PA_CONTEO     OUT NUMBER
  ,PA_MENSAJE    OUT VARCHAR2
  ,PA_CODERROR      OUT INTEGER
  ,PA_DESERROR     OUT VARCHAR2);

end PASUPERVISION;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."PASUPERVISION" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."PASUPERVISION" TO "SCSISGES";
