--------------------------------------------------------
--  DDL for Table TAALERTA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAALERTA" 
   (	"FIALERTAID" NUMBER, 
	"FCTIPOALERTA" VARCHAR2(10 BYTE), 
	"FCALERTADESC" VARCHAR2(160 BYTE), 
	"FDFECINICIAL" DATE, 
	"FDFECTERMINO" DATE, 
	"FISTATUS" NUMBER(2,0), 
	"FDMODIFICACION" DATE, 
	"USRMODIFICO" VARCHAR2(30 BYTE), 
	"FICANALID" NUMBER(38,0), 
	"FCTITULO" VARCHAR2(160 BYTE), 
	"FIALCANCEID" NUMBER(38,0), 
	"FIUSUARIOID" NUMBER(38,0), 
	"FDCREACION" DATE, 
	"FIROLID" NUMBER(38,0), 
	"FIALERTDESTINO" NUMBER(2,0), 
	"FNSTATALERT" NUMBER(2,0) DEFAULT 1, 
	"FITIPOALERTA" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TAALERTA"."FIUSUARIOID" IS 'CAMPO PARA GUARDAR USUARIO QUE LA CREO';
   COMMENT ON COLUMN "SCSISGES"."TAALERTA"."FIROLID" IS 'ROL DE EMPLEADO';
  GRANT DELETE ON "SCSISGES"."TAALERTA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAALERTA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAALERTA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAALERTA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAALERTA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAALERTA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAALERTA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAALERTA" TO "USRINFSISGES";
