--------------------------------------------------------
--  DDL for Table TABUZON
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TABUZON" 
   (	"FIBUZONID" NUMBER, 
	"FCEMPNUM" NUMBER(10,0), 
	"FISUCURSAL" NUMBER(6,0), 
	"FICATBUZONID" NUMBER(2,0), 
	"FIESTBUZONID" NUMBER(2,0), 
	"FCTEXTOBUZON" VARCHAR2(300 BYTE), 
	"FNTELEFONO" NUMBER(10,0), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMOFIDICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TABUZON" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TABUZON" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TABUZON" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TABUZON" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TABUZON" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TABUZON" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TABUZON" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TABUZON" TO "USRINFSISGES";
