--------------------------------------------------------
--  DDL for Table TACECOGEOGRAFIA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACECOGEOGRAFIA" 
   (	"FCIDCANAL" NUMBER, 
	"FCCANAL" VARCHAR2(50 CHAR), 
	"FIIDPAIS" NUMBER(3,0), 
	"FCPAIS" VARCHAR2(30 BYTE), 
	"FIIDCCBISABUELO" NUMBER(10,0), 
	"FCNOMBREBISABUELO" VARCHAR2(100 BYTE), 
	"FIIDCCABUELO" NUMBER(10,0), 
	"FCNOMBREABUELO" VARCHAR2(100 BYTE), 
	"FIIDCCPADRE" NUMBER(10,0), 
	"FCNOMBREPADRE" VARCHAR2(100 BYTE), 
	"FINUMECO" NUMBER(10,0), 
	"FCNOMECO" VARCHAR2(100 BYTE), 
	"FCSTATUS_DESC" VARCHAR2(15 BYTE), 
	"FDFECHAAPACT" DATE, 
	"FDFECHACIERRE" DATE, 
	"FCTIPOOP" VARCHAR2(15 BYTE), 
	"FIIDENTIDAD" NUMBER(10,0), 
	"FCNOMBREENTIDAD" VARCHAR2(100 BYTE), 
	"FCCALLE" VARCHAR2(100 BYTE), 
	"FCNUMEXT" VARCHAR2(20 BYTE), 
	"FCNUMINT" VARCHAR2(20 BYTE), 
	"FCCOLONIA" VARCHAR2(100 BYTE), 
	"FCMUNICIPIO" VARCHAR2(100 BYTE), 
	"FCESTADO" VARCHAR2(30 BYTE), 
	"FICP" NUMBER(10,0), 
	"FIIVA" NUMBER(5,2), 
	"ULTIMA_MODIFICACION" DATE, 
	"USUARIO_MODIFICO" VARCHAR2(30 BYTE), 
	"IDTIPOOP" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TEMPORAL_DAT" ;
  GRANT DELETE ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACECOGEOGRAFIA" TO "USRINFSISGES";
