--------------------------------------------------------
--  DDL for Table TACGESOPTMEDIOS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACGESOPTMEDIOS" 
   (	"FIGESOPCIONID" NUMBER(38,0), 
	"FIMEDIOGESTIONID" NUMBER(10,0), 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACGESOPTMEDIOS"."FIGESOPCIONID" IS 'ID DEL CATALOGO TACGESOPCIONES';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTMEDIOS"."FIMEDIOGESTIONID" IS 'ID DEL CATALOGO TCMEDIOGESTION';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTMEDIOS"."FISTATUS" IS 'BORRADO LOGICO, USAR 0 PARA BORRADO';
  GRANT DELETE ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTMEDIOS" TO "USRINFSISGES";
