--------------------------------------------------------
--  DDL for Table TACGESOPTCAMBA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACGESOPTCAMBA" 
   (	"FIGESOPCIONID" NUMBER(38,0), 
	"FICAMBACEOID" NUMBER(10,0), 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACGESOPTCAMBA"."FIGESOPCIONID" IS 'ID DEL CATALOGO TACGESOPCIONES';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTCAMBA"."FICAMBACEOID" IS 'ID DEL CATALOGO TCCATCAMBACEO';
  GRANT DELETE ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTCAMBA" TO "USRINFSISGES";
