--------------------------------------------------------
--  DDL for Table TACGESNIVELGEO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACGESNIVELGEO" 
   (	"FINIVELID" NUMBER(2,0), 
	"FCDESCRIPCION" VARCHAR2(100 BYTE), 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACGESNIVELGEO"."FINIVELID" IS 'ID DEL NIVEL DE LA GEOGRAFIA: EJ. 1';
   COMMENT ON COLUMN "SCSISGES"."TACGESNIVELGEO"."FCDESCRIPCION" IS 'DESCRIPCION DE LA GEOGRAFIA: EJ. PAIS';
   COMMENT ON COLUMN "SCSISGES"."TACGESNIVELGEO"."FISTATUS" IS 'BORRADO LOGICO, USAR 0 PARA BORRADO';
  GRANT DELETE ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACGESNIVELGEO" TO "USRINFSISGES";
