--------------------------------------------------------
--  DDL for Table TACLIENTEFINADO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACLIENTEFINADO" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FNEMPNUM" NUMBER(10,0), 
	"FDALTA" DATE DEFAULT SYSDATE, 
	"FNSTATUS" NUMBER(1,0) DEFAULT 0, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACLIENTEFINADO"."FNSTATUS" IS '0: SINCONFIRMAR | 1: CONFIRMADO | 2: NOCONFIRMADO';
  GRANT DELETE ON "SCSISGES"."TACLIENTEFINADO" TO "SCVENTASTIENDA";
  GRANT INSERT ON "SCSISGES"."TACLIENTEFINADO" TO "SCVENTASTIENDA";
  GRANT SELECT ON "SCSISGES"."TACLIENTEFINADO" TO "SCVENTASTIENDA";
  GRANT UPDATE ON "SCSISGES"."TACLIENTEFINADO" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACLIENTEFINADO" TO "USRINFSISGES";
