--------------------------------------------------------
--  DDL for Table TAEMPLEADOSEM
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAEMPLEADOSEM" 
   (	"FNCC" NUMBER, 
	"FNPLANTILLA" NUMBER, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDULTIMAMODIFICACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAEMPLEADOSEM" TO "USRINFSISGES";
