--------------------------------------------------------
--  DDL for Table TAFXCLIENTESPF
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXCLIENTESPF" 
   (	"FIIDCLIENTE" NUMBER(*,0), 
	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FIIDORIGEN" NUMBER, 
	"FIPAISGESTOR" NUMBER(5,0), 
	"FICANALGESTOR" NUMBER(5,0), 
	"FISUCURSALGESTORA" NUMBER(5,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(5,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSALGESTORA") 
 (PARTITION "TAFXCTESPF_01"  VALUES LESS THAN (1000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP01_DAT" , 
 PARTITION "TAFXCTESPF_02"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP02_DAT" , 
 PARTITION "TAFXCTESPF_03"  VALUES LESS THAN (3000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP03_DAT" , 
 PARTITION "TAFXCTESPF_04"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP04_DAT" , 
 PARTITION "TAFXCTESPF_05"  VALUES LESS THAN (5000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP05_DAT" , 
 PARTITION "TAFXCTESPF_06"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP06_DAT" , 
 PARTITION "TAFXCTESPF_07"  VALUES LESS THAN (7000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP07_DAT" , 
 PARTITION "TAFXCTESPF_08"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP08_DAT" , 
 PARTITION "TAFXCTESPF_09"  VALUES LESS THAN (9000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP09_DAT" , 
 PARTITION "TAFXCTESPF_10"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCLIENT_RP10_DAT" ) ;
  GRANT DELETE ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXCLIENTESPF" TO "USRINFSISGES";
