--------------------------------------------------------
--  DDL for Table TAFXUSUARIOSPF
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXUSUARIOSPF" 
   (	"FIIDUSUARIO" NUMBER(10,0), 
	"FIIDROL" NUMBER(10,0), 
	"FIIDROLSAP" NUMBER(10,0), 
	"FIESTATUS" NUMBER(3,0), 
	"FDFECACTUALSYS" DATE, 
	"FDFECACTUALSAP" DATE, 
	"FDFECALTA" DATE, 
	"FIIDPUESTO" NUMBER(10,0), 
	"FIIDSUCURSAL" NUMBER(5,0), 
	"FIFUNCION" NUMBER(*,0), 
	"FIPOSICION" NUMBER(*,0), 
	"FCCC" VARCHAR2(20 BYTE), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXUSUARIOSPF" TO "USRINFSISGES";
