--------------------------------------------------------
--  DDL for Table TALIGAS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TALIGAS" 
   (	"FIIDLIGA" NUMBER(38,0), 
	"FCDESCRIPCION" VARCHAR2(20 BYTE), 
	"FCURL" VARCHAR2(255 BYTE), 
	"FIESTATUS" NUMBER(38,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;
  GRANT DELETE ON "SCSISGES"."TALIGAS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TALIGAS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TALIGAS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TALIGAS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TALIGAS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TALIGAS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TALIGAS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TALIGAS" TO "USRINFSISGES";
