--------------------------------------------------------
--  DDL for Table TAOBJETIVOSUC
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAOBJETIVOSUC" 
   (	"FIIDSUCURSAL" NUMBER(5,0), 
	"FCNOMBRESUC" VARCHAR2(100 BYTE), 
	"FIIDREGION" NUMBER(6,0), 
	"FCDESCREGION" VARCHAR2(100 BYTE), 
	"FIIDZONA" NUMBER(6,0), 
	"FCDESCZONA" VARCHAR2(100 BYTE), 
	"FIIDTERRITORIO" NUMBER(6,0), 
	"FCDESCTERRITORIO" VARCHAR2(100 BYTE), 
	"FIIDPAIS" NUMBER(3,0), 
	"FDFECHA" VARCHAR2(8 BYTE), 
	"FNLINEA" NUMBER(10,0), 
	"FCLINEADESC" VARCHAR2(50 BYTE), 
	"FNSUBLINEA" NUMBER(10,0), 
	"FNCLASE" NUMBER(10,0), 
	"FNSEMANA" NUMBER(2,0), 
	"FNANIO" NUMBER(4,0), 
	"FNMONTOCREDITO" NUMBER(18,2), 
	"FNMONTOCONTADO" NUMBER(18,2), 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP01_DAT" 
  PARTITION BY RANGE ("FIIDSUCURSAL") 
 (PARTITION "OBJETIVOSUC_01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP01_DAT" , 
 PARTITION "OBJETIVOSUC_02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP02_DAT" , 
 PARTITION "OBJETIVOSUC_03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP03_DAT" , 
 PARTITION "OBJETIVOSUC_04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP04_DAT" , 
 PARTITION "OBJETIVOSUC_05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAOBJETSUC_RP05_DAT" ) ;
  GRANT DELETE ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAOBJETIVOSUC" TO "USRINFSISGES";
