--------------------------------------------------------
--  DDL for Table TAOBJETIVOS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAOBJETIVOS" 
   (	"FDFECHA" VARCHAR2(8 BYTE), 
	"FNCCOSTO" VARCHAR2(6 BYTE), 
	"FNPRODUCTO" NUMBER(10,0), 
	"FCIDCONCEPTO" VARCHAR2(10 BYTE), 
	"FNTIPOGTO" NUMBER(10,2), 
	"FNMONTOPESOS" NUMBER(12,2), 
	"FNMONTOLOCAL" NUMBER(12,2), 
	"FDFECHAARRIBO" DATE, 
	"FDFECHAACTUALIZA" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FDFECHA" IS 'FECHA';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FNCCOSTO" IS 'CENTRO DE COSTOS';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FNPRODUCTO" IS 'PRODUCTO';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FCIDCONCEPTO" IS 'CONCEPTO (CREDITO, CONTADO)';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FNTIPOGTO" IS 'SOCIEDAD QUE GENER� EL GASTO';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FNMONTOPESOS" IS 'MONTO PESOS';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FNMONTOLOCAL" IS 'MONTO MONEDA LOCAL';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FDFECHAARRIBO" IS 'FECHA DE ARRIBO DE LA INFORMACI�N';
   COMMENT ON COLUMN "SCSISGES"."TAOBJETIVOS"."FDFECHAACTUALIZA" IS 'FECHA AL HACER LA CARGA DE INFORMACION';
  GRANT DELETE ON "SCSISGES"."TAOBJETIVOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAOBJETIVOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAOBJETIVOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAOBJETIVOS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAOBJETIVOS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAOBJETIVOS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAOBJETIVOS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAOBJETIVOS" TO "USRINFSISGES";
