--------------------------------------------------------
--  DDL for Table TAPERFALERTA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAPERFALERTA" 
   (	"FIALERTAID" NUMBER(*,0), 
	"FIPERFILID" NUMBER(*,0), 
	"FNINACTIVO" NUMBER(1,0), 
	"FDCREACION" DATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE), 
	"FDMODIFICO" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAPERFALERTA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAPERFALERTA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAPERFALERTA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAPERFALERTA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAPERFALERTA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAPERFALERTA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAPERFALERTA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAPERFALERTA" TO "USRINFSISGES";
