--------------------------------------------------------
--  DDL for Table TAPROMOCIONPASO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAPROMOCIONPASO" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIO" NUMBER(15,0), 
	"FCDESCPROD" VARCHAR2(100 CHAR), 
	"FIPRIORIDAD" NUMBER(5,0), 
	"FIIDSUBLINEA" NUMBER(10,0), 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(35 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSASFNX";
  GRANT INSERT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSASFNXPRE";
  GRANT DELETE ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAPROMOCIONPASO" TO "USRINFSISGES";
