--------------------------------------------------------
--  DDL for Table TATELEFONOS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TATELEFONOS" 
   (	"FIIDTELEFONO" NUMBER(*,0), 
	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FNTELEFONO" NUMBER(10,0), 
	"FISTATUS" NUMBER(1,0), 
	"FIIDTIPO" NUMBER(1,0), 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TATELEFONOS"."FIIDTELEFONO" IS 'ID UNICO DEL TELEFONO';
   COMMENT ON COLUMN "SCSISGES"."TATELEFONOS"."FNTELEFONO" IS 'TELEFONO DEL CLIENTE';
   COMMENT ON COLUMN "SCSISGES"."TATELEFONOS"."FISTATUS" IS 'ESTATUS DEL TELEFONO 0: POR VALIDAR | 1: VALIDO | 2: NO VALIDO';
   COMMENT ON COLUMN "SCSISGES"."TATELEFONOS"."FIIDTIPO" IS 'TIPO DE TELEFONO, SE OBTIENE DEL CATALOGO TCTIPOTELEFONOS';
  GRANT DELETE ON "SCSISGES"."TATELEFONOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TATELEFONOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TATELEFONOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TATELEFONOS" TO "USRINFFENIX";
