--------------------------------------------------------
--  DDL for Table TCDESCGESTION
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCDESCGESTION" 
   (	"FITIPOGESTION" NUMBER, 
	"FIMEDIOGESTION" NUMBER, 
	"FIRESULGESTION" NUMBER, 
	"FIDESCGESTION" NUMBER, 
	"FCDESCGESTION" VARCHAR2(200 BYTE), 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCDESCGESTION" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCDESCGESTION" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCDESCGESTION" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCDESCGESTION" TO "USRINFFENIX";
