--------------------------------------------------------
--  DDL for Table TCESTATUSBUZON
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCESTATUSBUZON" 
   (	"FIESTBUZONID" NUMBER(2,0), 
	"FCDESCRIPCION" VARCHAR2(50 BYTE), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCESTATUSBUZON" TO "USRINFSISGES";
