--------------------------------------------------------
--  DDL for Table TCEVENTO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCEVENTO" 
   (	"FIEVENTO" NUMBER DEFAULT "SCSISGES"."SEQCEVENTO".nextval, 
	"FCEVENTO" VARCHAR2(50 BYTE), 
	"FCESTATUS" VARCHAR2(1 BYTE), 
	"FCCOLORPRI" VARCHAR2(7 BYTE), 
	"FCCOLORSEC" VARCHAR2(7 BYTE), 
	"FCDESCEVENTO" VARCHAR2(50 BYTE), 
	"FCICONO" VARCHAR2(10 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCEVENTO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCEVENTO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCEVENTO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCEVENTO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCEVENTO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCEVENTO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCEVENTO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCEVENTO" TO "USRINFSISGES";
