--------------------------------------------------------
--  DDL for Table TCLABORADESC
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCLABORADESC" 
   (	"FIIDLABORA" NUMBER(3,0), 
	"FCLABORADESC" VARCHAR2(100 BYTE), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCLABORADESC" TO "SCVENTASTIENDA";
  GRANT INSERT ON "SCSISGES"."TCLABORADESC" TO "SCVENTASTIENDA";
  GRANT SELECT ON "SCSISGES"."TCLABORADESC" TO "SCVENTASTIENDA";
  GRANT UPDATE ON "SCSISGES"."TCLABORADESC" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TCLABORADESC" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCLABORADESC" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCLABORADESC" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCLABORADESC" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCLABORADESC" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCLABORADESC" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCLABORADESC" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCLABORADESC" TO "USRINFSISGES";
  GRANT DELETE ON "SCSISGES"."TCLABORADESC" TO "USRSISGES";
  GRANT INSERT ON "SCSISGES"."TCLABORADESC" TO "USRSISGES";
  GRANT SELECT ON "SCSISGES"."TCLABORADESC" TO "USRSISGES";
  GRANT UPDATE ON "SCSISGES"."TCLABORADESC" TO "USRSISGES";
