--------------------------------------------------------
--  DDL for Table TCMODULO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCMODULO" 
   (	"FIMODULOID" NUMBER(2,0), 
	"FCDESCMODULO" VARCHAR2(100 BYTE), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCMODULO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCMODULO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCMODULO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCMODULO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCMODULO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCMODULO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCMODULO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCMODULO" TO "USRINFSISGES";
  GRANT DELETE ON "SCSISGES"."TCMODULO" TO "USRSISGES";
  GRANT INSERT ON "SCSISGES"."TCMODULO" TO "USRSISGES";
  GRANT SELECT ON "SCSISGES"."TCMODULO" TO "USRSISGES";
  GRANT UPDATE ON "SCSISGES"."TCMODULO" TO "USRSISGES";
