--------------------------------------------------------
--  DDL for Table TCPERFILESEMP
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCPERFILESEMP" 
   (	"FIIDPERFIL" NUMBER(3,0), 
	"FNFUNCIONSAP" NUMBER(10,0), 
	"FCNOMBREPERFIL" VARCHAR2(70 BYTE), 
	"FCDESCRIPCION" VARCHAR2(200 BYTE), 
	"FNTIPOPERFIL" NUMBER(1,0), 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE), 
	"FDMODIFICACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TCPERFILESEMP"."FIIDPERFIL" IS 'ID CREADO PARA MANEJAR DE FORMA CLASIFICADA LAS FUNCIONES';
   COMMENT ON COLUMN "SCSISGES"."TCPERFILESEMP"."FNFUNCIONSAP" IS 'FUNCION SAP QUE CARACTERIZA AL EMPLEADO';
   COMMENT ON COLUMN "SCSISGES"."TCPERFILESEMP"."FCNOMBREPERFIL" IS 'NOMBRE CORTO DEL PERFIL';
   COMMENT ON COLUMN "SCSISGES"."TCPERFILESEMP"."FCDESCRIPCION" IS 'OPCIONAL, DESCRIPCION AMPLIA DEL PERFIL';
   COMMENT ON COLUMN "SCSISGES"."TCPERFILESEMP"."FNTIPOPERFIL" IS '1: PERFIL ELEKTRA | 2: PERFIL BANCO AZTECA';
  GRANT DELETE ON "SCSISGES"."TCPERFILESEMP" TO "SCVENTASTIENDA";
  GRANT INSERT ON "SCSISGES"."TCPERFILESEMP" TO "SCVENTASTIENDA";
  GRANT SELECT ON "SCSISGES"."TCPERFILESEMP" TO "SCVENTASTIENDA";
  GRANT UPDATE ON "SCSISGES"."TCPERFILESEMP" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TCPERFILESEMP" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCPERFILESEMP" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCPERFILESEMP" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCPERFILESEMP" TO "USRINFFENIX";
