--------------------------------------------------------
--  DDL for Table TCUSUARIOADMIN
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCUSUARIOADMIN" 
   (	"FIUSRID" NUMBER, 
	"FITIPOUSRID" NUMBER(3,0), 
	"FCNOMBREUSR" VARCHAR2(100 BYTE), 
	"FCPWDUSR" VARCHAR2(100 BYTE), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRINFSISGES";
  GRANT DELETE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRSISGES";
  GRANT INSERT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRSISGES";
  GRANT SELECT ON "SCSISGES"."TCUSUARIOADMIN" TO "USRSISGES";
  GRANT UPDATE ON "SCSISGES"."TCUSUARIOADMIN" TO "USRSISGES";
