--------------------------------------------------------
--  DDL for Package Body PAREPORTES0001
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."PAREPORTES0001" 
AS

    PROCEDURE SPSGESTIONES(
        PA_FECHAINICIO   IN  DATE,
        PA_FECHAFIN      IN  DATE,
        PA_GESTIONES     OUT SCSISGES.PATYPES.RCGCURSOR,
        PA_CODIGO        OUT NUMBER,
        PA_MENSAJE       OUT VARCHAR2,
        PA_MENSAJEERROR  OUT VARCHAR2
    ) AS
    BEGIN
        OPEN PA_GESTIONES FOR
        SELECT
            SCSISGES.PAREPORTES0001.FNSUCEMPLEADO(TO_NUMBER(GESTION.FCEMPNUM)) sucursal
            ,GESTION.FCEMPNUM NO_EMPLEADO
            ,SCSISGES.PAREPORTES0001.FNNOMBREEMPLEADO(TO_NUMBER(GESTION.FCEMPNUM)) EMPLEADO
            ,GESTION.FIPAISCU||'-'||GESTION.FICANALCU||'-'||GESTION.FISUCURSALCU||'-'||GESTION.FIFOLIOCU CLIENTE_UNICO
            ,SCSISGES.PAREPORTES0001.FNDESCTIPOGESTION(GESTION.FITIPOGESTIONID) TIPO_GESTION
            ,SCSISGES.PAREPORTES0001.FNDESCMEDIO(GESTION.FIMEDIOGESTIONID) COMO_CONTACTE
            ,SCSISGES.PAREPORTES0001.FNDESCRESULTADO(GESTION.FIRESULTGESTIONID) RESULTADO
            ,GESTION.FCNOTAS NOTAS
            ,TO_CHAR(GESTION.FDCREACION,'DD/MM/YYYY HH24:MI:SS') FECHA_GESTION
            ,SCSISGES.PAREPORTES0001.FNDESCEVENTO(GESTION.FIGESTIONID) AGENDA
            ,SCSISGES.PAREPORTES0001.FNFECHAEVENTO(GESTION.FIGESTIONID) FECHA_AGENDA
        FROM
            SCSISGES.TAGESTION GESTION 
        WHERE TRUNC(GESTION.FDCREACION) BETWEEN TRUNC(PA_FECHAINICIO) AND TRUNC(PA_FECHAFIN)
        ORDER BY 1,9;

        PA_CODIGO := 0;
        PA_MENSAJE := 'OK';
    EXCEPTION WHEN OTHERS THEN
        OPEN PA_GESTIONES FOR
        SELECT
            NULL sucursal
            ,NULL NO_EMPLEADO
            ,NULL EMPLEADO
            ,NULL CLIENTE_UNICO
            ,NULL TIPO_GESTION
            ,NULL COMO_CONTACTE
            ,NULL RESULTADO
            ,NULL NOTAS
            ,NULL FECHA_GESTION
            ,NULL AGENDA
            ,NULL FECHA_AGENDA
        FROM DUAL;
        PA_CODIGO := 1;
        PA_MENSAJE := 'Ocurri� un error al ejecutar la consulta';
        PA_MENSAJEERROR := DBMS_UTILITY.FORMAT_ERROR_BACKTRACE();
    END;

    FUNCTION FNSUCEMPLEADO(
      PA_FIIDUSUARIO IN SCSISGES.TCUSUARIO.FIIDUSUARIO%TYPE  
    ) RETURN VARCHAR2 AS
        VL_SUCURSAL SCSISGES.TCUSUARIO.FIIDSUCURSAL%TYPE;
    BEGIN

        SELECT FIIDSUCURSAL INTO VL_SUCURSAL
        FROM SCSISGES.TCUSUARIO
        WHERE FIIDUSUARIO = PA_FIIDUSUARIO;

        RETURN VL_SUCURSAL;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

    FUNCTION FNNOMBREEMPLEADO(
      PA_FIIDUSUARIO IN SCSISGES.TCUSUARIO.FIIDUSUARIO%TYPE  
    ) RETURN VARCHAR2 AS
        VL_NOMBRE VARCHAR2(400);
    BEGIN

        SELECT FCNOMBRE||' '||FCAPPATERNO||' '||FCAPMATERNO INTO VL_NOMBRE
        FROM SCSISGES.TCUSUARIO
        WHERE FIIDUSUARIO = PA_FIIDUSUARIO;

        RETURN VL_NOMBRE;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

    FUNCTION FNDESCTIPOGESTION(
      PA_FITIPOGESTIONID IN SCSISGES.TCTIPOGESTION.FITIPOGESTIONID%TYPE  
    ) RETURN VARCHAR2 AS
        VL_DESCRIPCION SCSISGES.TCTIPOGESTION.FCTIPOGESTIONDESC%TYPE;
    BEGIN

        SELECT FCTIPOGESTIONDESC INTO VL_DESCRIPCION
        FROM SCSISGES.TCTIPOGESTION
        WHERE FITIPOGESTIONID = PA_FITIPOGESTIONID;

        RETURN VL_DESCRIPCION;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

    FUNCTION FNDESCMEDIO(
      PA_FIMEDIOGESTIONID IN SCSISGES.TCMEDIOGESTION.FIMEDIOGESTIONID%TYPE  
    ) RETURN VARCHAR2 AS
        VL_DESCRIPCION SCSISGES.TCMEDIOGESTION.FCMEDIOSGESTIONDESC%TYPE;
    BEGIN

        SELECT FCMEDIOSGESTIONDESC INTO VL_DESCRIPCION
        FROM SCSISGES.TCMEDIOGESTION
        WHERE FIMEDIOGESTIONID = PA_FIMEDIOGESTIONID;

        RETURN VL_DESCRIPCION;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

    FUNCTION FNDESCRESULTADO(
      PA_FIRESULTGESTIONID IN SCSISGES.TCRESULTGESTION.FIRESULTGESTIONID%TYPE
    ) RETURN VARCHAR2 AS
        VL_DESCRIPCION SCSISGES.TCRESULTGESTION.FCRESULTGESTIONDESC%TYPE;
    BEGIN

        SELECT FCRESULTGESTIONDESC INTO VL_DESCRIPCION
        FROM SCSISGES.TCRESULTGESTION
        WHERE FIRESULTGESTIONID = PA_FIRESULTGESTIONID;

        RETURN VL_DESCRIPCION;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

    FUNCTION FNDESCEVENTO(
        PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE
    ) RETURN VARCHAR2 AS
        VL_DESCRIPCION SCSISGES.TCEVENTO.FCEVENTO%TYPE;
        VL_FIUSUARIOID SCSISGES.TAEVENTGEST.FIUSUARIOID%TYPE;
        VL_FIEVENTOID SCSISGES.TAEVENTGEST.FIEVENTOID%TYPE;
        VL_FICLIENTE SCSISGES.TAEVENTGEST.FICLIENTE%TYPE;
        VL_FIEVENTO SCSISGES.TAEVENTO.FIEVENTO%TYPE;
    BEGIN

        SCSISGES.PAREPORTES0001.SPSEVENTO(
            PA_FIGESTIONID,
            VL_FIUSUARIOID,
            VL_FIEVENTOID,
            VL_FICLIENTE);

        SELECT FIEVENTO INTO VL_FIEVENTO
        FROM SCSISGES.TAEVENTO 
        WHERE FIUSUARIOID = VL_FIUSUARIOID AND
              FIIDEVENTO = VL_FIEVENTOID AND
              FICLIENTE = VL_FICLIENTE;

        SELECT FCEVENTO INTO VL_DESCRIPCION
        FROM SCSISGES.TCEVENTO
        WHERE FIEVENTO = VL_FIEVENTO;

        RETURN VL_DESCRIPCION;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;


    PROCEDURE SPSEVENTO(
        PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE,
        PA_FIUSUARIOID OUT SCSISGES.TAEVENTGEST.FIUSUARIOID%TYPE,
        PA_FIEVENTOID OUT SCSISGES.TAEVENTGEST.FIEVENTOID%TYPE,
        PA_FICLIENTE OUT SCSISGES.TAEVENTGEST.FICLIENTE%TYPE
    )AS
    BEGIN
        SELECT FIUSUARIOID, FIEVENTOID, FICLIENTE 
            INTO PA_FIUSUARIOID, PA_FIEVENTOID, PA_FICLIENTE
        FROM SCSISGES.TAEVENTGEST
        WHERE FIGESTIONID = PA_FIGESTIONID;
    EXCEPTION WHEN OTHERS THEN
        PA_FIUSUARIOID := NULL;
        PA_FIEVENTOID := NULL;
        PA_FICLIENTE := NULL;
    END;

    FUNCTION FNFECHAEVENTO(
         PA_FIGESTIONID IN SCSISGES.TAGESTION.FIGESTIONID%TYPE
    ) RETURN VARCHAR2 AS
        VL_FECHA VARCHAR2(30);
        VL_FIUSUARIOID SCSISGES.TAEVENTGEST.FIUSUARIOID%TYPE;
        VL_FIEVENTOID SCSISGES.TAEVENTGEST.FIEVENTOID%TYPE;
        VL_FICLIENTE SCSISGES.TAEVENTGEST.FICLIENTE%TYPE;
    BEGIN

        SCSISGES.PAREPORTES0001.SPSEVENTO(
                PA_FIGESTIONID,
                VL_FIUSUARIOID,
                VL_FIEVENTOID,
                VL_FICLIENTE);

        SELECT TO_CHAR(FDHORAINICIO,'DD/MM/YYYY HH24:MI:SS') INTO VL_FECHA
        FROM SCSISGES.TAEVENTO 
        WHERE FIUSUARIOID = VL_FIUSUARIOID AND
              FIIDEVENTO = VL_FIEVENTOID AND
              FICLIENTE = VL_FICLIENTE;

        RETURN VL_FECHA;
    EXCEPTION WHEN OTHERS THEN
        RETURN NULL;
    END;

END PAREPORTES0001;

/

  GRANT EXECUTE ON "SCSISGES"."PAREPORTES0001" TO "USRSISGES";
