--------------------------------------------------------
--  DDL for Package Body TEST_PQPLANTILLAEMPLEADOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PQPLANTILLAEMPLEADOS" 
IS
   /* generated by utPLSQL for SQL Developer on 2019-03-20 17:58:41 */

   --
   -- test spcargaplantilla case 1: ...
   --
   PROCEDURE spinsertplantilla
   IS
      conteoreg   NUMBER;
   BEGIN
      DELETE FROM scsisges.TAEMPLEADOPF;

      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
                             VALUES (89671,
                                     'LUIS FERNANDO',
                                     'HERNANDEZ',
                                     'DE LA ROSA',
                                     8067,
                                     141361,
                                     528581,
                                     'EKT',
                                     1,
                                     '25/03/2019',
                                     '25/03/2019',
                                     '12/10/2014',
                                     1,
                                     8581,
                                     1,
                                     1);


      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (877687,
                   'MANUEL',
                   'TORRES',
                   'MORALES',
                   8035,
                   165506,
                   528830,
                   'EKT',
                   1,
                   '25/03/2019',
                   '25/03/2019',
                   '12/05/2014',
                   1,
                   8830,
                   3,
                   1);

      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (800088,
                   'ELVIA ALEJANDRA',
                   'VARGAS',
                   'LARA',
                   8067,
                   174145,
                   525649,
                   'EKT',
                   1,
                   '25/03/2019',
                   '25/03/2019',
                   '12/11/2015',
                   1,
                   5649,
                   1,
                   1);


      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (84384,
                   'EVELLYN',
                   'ROMERO',
                   'BALLESTEROS',
                   8067,
                   174145,
                   525649,
                   'EKT',
                   1,
                   '25/03/2019',
                   '25/03/2019',
                   '05/11/2015',
                   1,
                   5649,
                   1,
                   1);


      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (89984,
                   'NICOLAS EDILBERTO',
                   'MENDEZ',
                   'SOLIS',
                   8067,
                   177252,
                   527579,
                   'EKT',
                   1,
                   '25/03/2019',
                   '25/03/2019',
                   '08/10/2015',
                   1,
                   7579,
                   1,
                   1);

      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (84771,
                   'JOELLY GISSEL',
                   'GONGORA',
                   'BRICEÑO',
                   8067,
                   918385,
                   524958,
                   'EKT',
                   1,
                   '12/03/2019',
                   '12/03/2019',
                   '01/10/2013',
                   1,
                   4958,
                   1,
                   1);

      INSERT INTO SCSISGES.TAEMPLEADOPF (fnempleado,
                                         fcnombre,
                                         fcapaterno,
                                         fcamaterno,
                                         fnfuncionsap,
                                         fnempleadojefe,
                                         fncc,
                                         fcnegocio,
                                         fiidlabora,
                                         fdultimamodificacion,
                                         fdbaja,
                                         fdalta,
                                         fisituacion,
                                         fiidsucursal,
                                         fiidperfil,
                                         fnorigen)
           VALUES (886618,
                   'BLANCA GLORIA',
                   'CRUZ',
                   'MARTINEZ',
                   8034,
                   180755,
                   522012,
                   'EKT',
                   1,
                   '12/03/2019',
                   '12/03/2019',
                   '01/10/2013',
                   1,
                   2012,
                   2,
                   1);


      SELECT COUNT (1)
        INTO conteoreg
        FROM SCSISGES.TAEMPLEADOPF
       WHERE TRUNC (FDCREACION) = TRUNC (SYSDATE);

      ut.expect (conteoreg, 'El numero de registros es mayor a 0').to_ (
         be_greater_than (0));
   END spinsertplantilla;



   --
   -- test spcargaplantilla case 2: ...
   --
   PROCEDURE spcargaplantilla
   IS
      pa_fnnegocio    VARCHAR2 (4);
      pa_fncoderror   NUMBER;
      pa_fcdeserror   VARCHAR2 (200);
   BEGIN
      pa_fnnegocio := 'EKT';
      -- populate actual
      -- pqplantillaempleados.spcargaplantilla;
      pqplantillaempleados.spcargaplantilla (pa_fnnegocio    => pa_fnnegocio,
                                             pa_fncoderror   => pa_fncoderror,
                                             pa_fcdeserror   => pa_fcdeserror);

      -- populate expected
      -- ...

      -- assert
      ut.expect (pa_fncoderror, 'Código de salida no es 1').to_ (equal (1));
      ut.expect (pa_fcdeserror, 'Mensaje de salida no es igual a OK').to_ (
         equal ('OK'));
   END spcargaplantilla;
END test_pqplantillaempleados;

/
