--------------------------------------------------------
--  DDL for Package Body TEST_PAGETCAMPANAS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PAGETCAMPANAS" IS
    /* generated by utPLSQL for SQL Developer on 2019-04-08 19:15:12 */

    --
    -- test spcampanasclte case 1: ...
    --

    PROCEDURE addctescampanas IS
        numctescampana   SMALLINT;
        numcampanas      SMALLINT;
    BEGIN
        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999990,
            'UNITTEST00',
            'UNIT TEST 00',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999991,
            'UNITTEST01',
            'UNIT TEST 01',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999992,
            'UNITTEST02',
            'UNIT TEST 02',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999993,
            'UNITTEST03',
            'UNIT TEST 03',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999994,
            'UNITTEST04',
            'UNIT TEST 04',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999995,
            'UNITTEST05',
            'UNIT TEST 05',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999996,
            'UNITTEST06',
            'UNIT TEST 06',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999997,
            'UNITTEST07',
            'UNIT TEST 07',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999998,
            'UNITTEST08',
            'UNIT TEST 08',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        INSERT INTO tccampanamkt (
            fiidcampana,
            fccampana,
            fcdesccampana,
            fiidtipo,
            fiidnegocio,
            fiidpais,
            fcusrmodifico,
            fdmodificacion
        ) VALUES (
            99999999,
            'UNITTEST09',
            'UNIT TEST 09',
            1,
            1,
            1,
            'SCSISGES',
            SYSDATE
        );

        SELECT
            COUNT(*)
        INTO
            numcampanas
        FROM
            tccampanamkt
        WHERE
            fiidcampana >= 99999990;

        ut.expect(
            numcampanas,
            'Número de campañas'
        ).to_(be_greater_than(0) );
        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999990,
            99990,
            1,
            1,
            99999999999999999990,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999991,
            99991,
            1,
            1,
            99999999999999999991,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999992,
            99993,
            1,
            1,
            99999999999999999992,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999993,
            99993,
            1,
            1,
            99999999999999999993,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999994,
            99994,
            1,
            1,
            99999999999999999994,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999995,
            99995,
            1,
            1,
            99999999999999999995,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999996,
            99996,
            1,
            1,
            99999999999999999996,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999997,
            99997,
            1,
            1,
            99999999999999999997,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999998,
            99998,
            1,
            1,
            99999999999999999998,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        INSERT INTO tacampanacte (
            fiidcampana,
            fipais,
            ficanal,
            fisucursal,
            fifolio,
            fiidempleado,
            fnstatuscte,
            fiidpais,
            fiidterritorio,
            fiidzona,
            fiidregion,
            fiidsucursal,
            fdmodificacion,
            fcusrmodifico
        ) VALUES (
            99999999,
            99999,
            1,
            1,
            99999999999999999999,
            6189,
            1,
            1,
            186336,
            186926,
            186585,
            1,
            SYSDATE,
            'SCSISGES'
        );

        SELECT
            COUNT(*)
        INTO
            numctescampana
        FROM
            tacampanacte
        WHERE
            fiidcampana >= 99999990;

        ut.expect(
            numctescampana,
            'Número de clientes en campaña'
        ).to_(be_greater_than(0) );
    END addctescampanas;

    PROCEDURE spcampanasclte IS

        pa_fipais       INTEGER := 99990;
        pa_ficanal      INTEGER := 1;
        pa_fisucursal   INTEGER := 1;
        pa_fifolio      INTEGER := 99999999999999999990;
        pa_curdatos     SYS_REFCURSOR;
        pa_mensaje      VARCHAR2(200);
        pa_coderror     INTEGER;
        pa_deserror     VARCHAR2(200);
    BEGIN
        pagetcampanas.spcampanasclte(
            pa_fipais       => pa_fipais,
            pa_ficanal      => pa_ficanal,
            pa_fisucursal   => pa_fisucursal,
            pa_fifolio      => pa_fifolio,
            pa_curdatos     => pa_curdatos,
            pa_mensaje      => pa_mensaje,
            pa_coderror     => pa_coderror,
            pa_deserror     => pa_deserror
        );

        ut.expect(
            pa_curdatos,
            'La ejecución de spcampanasclte terminó incorrectamente'
        ).to_be_not_null ();
        ut.expect(
            pa_coderror,
            'Código de salida 200'
        ).to_(equal(1) );
        ut.expect(
            pa_mensaje,
            'Mensaje de salida incorrecto'
        ).to_(equal('CONSULTA REALIZADA CORRECTAMENTE') );
    END spcampanasclte;

    --
    -- test spconteoctescamp case 1: ...
    --

    PROCEDURE spconteoctescamp IS

        pa_fcempleado   VARCHAR2(200);
        pa_fisucursal   NUMBER := 1;
        pa_fipais       NUMBER := 99990;
        pa_curscamp     SYS_REFCURSOR;
        pa_mensaje      VARCHAR2(200);
        pa_coderror     INTEGER;
        pa_deserror     VARCHAR2(200);
    BEGIN
        -- populate actual
        -- pagetcampanas.spconteoctescamp;
        scsisges.pagetcampanas.spconteoctescamp(
            pa_fcempleado   => pa_fcempleado,
            pa_fisucursal   => pa_fisucursal,
            pa_fipais       => pa_fipais,
            pa_curscamp     => pa_curscamp,
            pa_mensaje      => pa_mensaje,
            pa_coderror     => pa_coderror,
            pa_deserror     => pa_deserror
        );

        ut.expect(
            pa_curscamp,
            'La ejecución de SPCONTEOCTESCAMP terminó incorrectamente'
        ).to_be_not_null ();
        ut.expect(
            pa_coderror,
            'Código de salida 200'
        ).to_(equal(1) );
        ut.expect(
            pa_mensaje,
            'Mensaje de salida incorrecto'
        ).to_(equal('CONSULTA REALIZADA CORRECTAMENTE') );
    END spconteoctescamp;

    --
    -- test spctescampanas case 1: ...
    --

    PROCEDURE spctescampanas IS

        pa_fcempleado   VARCHAR2(5) := '6189';
        pa_fisucursal   NUMBER := 1;
        pa_curscamp     SYS_REFCURSOR;
        pa_mensaje      VARCHAR2(200);
        pa_coderror     INTEGER;
        pa_deserror     VARCHAR2(200);
    BEGIN
        scsisges.pagetcampanas.spctescampanas(
            pa_fcempleado   => pa_fcempleado,
            pa_curscamp     => pa_curscamp,
            pa_fisucursal   => pa_fisucursal,
            pa_mensaje      => pa_mensaje,
            pa_coderror     => pa_coderror,
            pa_deserror     => pa_deserror
        );

        ut.expect(
            pa_curscamp,
            'La ejecución de SPCTESCAMPANAS terminó incorrectamente'
        ).to_be_not_null ();
        ut.expect(
            pa_coderror,
            'Código de salida 200'
        ).to_(equal(1) );
        ut.expect(
            pa_mensaje,
            'Mensaje de salida incorrecto'
        ).to_(equal('CONSULTA REALIZADA CORRECTAMENTE') );

        -- ...
        DELETE tacampanacte WHERE
                fiidcampana >= 99999990
            AND
                fifolio >= 99999999999999999990;

        DELETE tccampanamkt WHERE
            fiidcampana >= 99999990;
    -- assert

    END spctescampanas;

    --
    -- test spcampanasact case 1: ...
    --

    PROCEDURE spcampanasact IS
        pa_curscampact   SYS_REFCURSOR;
        pa_mensaje       VARCHAR(200);
        pa_coderror      INTEGER;
        pa_deserror      VARCHAR(200);
    BEGIN
        pagetcampanas.spcampanasact(
            pa_curscampact   => pa_curscampact,
            pa_mensaje       => pa_mensaje,
            pa_coderror      => pa_coderror,
            pa_deserror      => pa_deserror
        );
      -- populate actual
      -- pagetcampanas.spcampanasact;

      -- populate expected
      -- ...

      -- assert

        DELETE tccampanamkt WHERE
            fiidcampana >= 99999990;

        DELETE tacampanacte WHERE
            fiidcampana >= 99999990;

        ut.expect(
            pa_curscampact,
            'La consulta no regreso ningun dato'
        ).to_be_not_null ();
        ut.expect(
            pa_mensaje,
            'El cursor esta vacio'
        ).to_be_not_null ();
        ut.expect(
            pa_coderror,
            'Código de salida 200'
        ).to_(equal(1) );
        ut.expect(
            pa_deserror,
            'El mensaje de error no es null'
        ).to_(equal('') );
    END spcampanasact;

END test_pagetcampanas;

/
