--------------------------------------------------------
--  DDL for Package Body TEST_PAOBJETIVOS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PAOBJETIVOS" IS

   /* generated by utPLSQL for SQL Developer on 2019-05-13 15:54:43 */

   --
   -- test spobjetivodiaemp case 1: ...
   --
   PROCEDURE spobjetivodiaemp IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivoemp where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivoemp (
        fnempleado,
        fiidsucursal,
        fcnombresuc,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        186584,
        'hola',
        186342,
        'hola',
        186336,
        'hola',
        1,
        '20190515',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        9000,
        5000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivoemp
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivodiaemp;

   --
   -- test spobjetivosememp case 1: ...
   --
   PROCEDURE spobjetivosememp IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivoemp where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
     INSERT INTO scsisges.taobjetivoemp (
        fnempleado,
        fiidsucursal,
        fcnombresuc,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        186584,
        'hola',
        186342,
        'hola',
        186336,
        'hola',
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
    
    delete from scsisges.tavendvtasemanal where fcusrcreacion = 'PRUEBASUNITARIAS';
    
    INSERT INTO scsisges.tavendvtasemanal (
        fnempleado,
        fcnombreemp,
        fiidsucursal,
        fcnombresuc,
        finumcecosuc,
        fiidpais,
        fcpais,
        ficanal,
        fccanal,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fntipoventa,
        fnlinea,
        fnmontototal,
        fisemana,
        fianio,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        'JOSE EMMANUEL GALVAN CASTAÑEDA',
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        520199,
        1,
        'MEXICO',
        1,
        'ELEKTRA',
        186584,
        'REGIONAL TIENDAS EKT GUANAJUATO CENTRO 6',
        186342,
        'ZONA GUANAJUATO CENTRO 6',
        186336,
        1,
        500,
        2350,
        20,
        2019,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivoemp
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivosememp;

   --
   -- test spobjetivodiasuc case 1: ...
   --
   PROCEDURE spobjetivodiasuc IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivosuc where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivosuc (
        fiidsucursal,
        fcnombresuc,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        186584,
        'g',
        186342,
        'b',
        186336,
        'v',
        1,
        '20190515',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        9000,
        5000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivosuc
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivodiasuc;

   --
   -- test spobjetivosemsuc case 1: ...
   --
   PROCEDURE spobjetivosemsuc IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivosuc where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivosuc (
        fiidsucursal,
        fcnombresuc,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        186584,
        'hola',
        186342,
        'hola',
        186336,
        'hola',
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    )
    ;
    delete from scsisges.tavendvtasemanal where fcusrcreacion = 'PRUEBASUNITARIAS';
    
    INSERT INTO scsisges.tavendvtasemanal (
        fnempleado,
        fcnombreemp,
        fiidsucursal,
        fcnombresuc,
        finumcecosuc,
        fiidpais,
        fcpais,
        ficanal,
        fccanal,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fntipoventa,
        fnlinea,
        fnmontototal,
        fisemana,
        fianio,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        'JOSE EMMANUEL GALVAN CASTAÑEDA',
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        520199,
        1,
        'MEXICO',
        1,
        'ELEKTRA',
        186584,
        'REGIONAL TIENDAS EKT GUANAJUATO CENTRO 6',
        186342,
        'ZONA GUANAJUATO CENTRO 6',
        186336,
        1,
        500,
        2350,
        20,
        2019,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivosuc
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivosemsuc;

   --
   -- test spobjetivodiareg case 1: ...
   --
   PROCEDURE spobjetivodiareg IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivoreg where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivoreg (
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        186584,
        'hola',
        186342,
        'hola',
        186336,
        'hola',
        1,
        '20190515',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        9000,
        5000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivoreg
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivodiareg;

   --
   -- test spobjetivosemreg case 1: ...
   --
   PROCEDURE spobjetivosemreg IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivoreg where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivoreg (
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        186584,
        'hola',
        186342,
        'hola',
        186336,
        'hola',
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
    
    delete from scsisges.tavendvtasemanal where fcusrcreacion = 'PRUEBASUNITARIAS';
    
    INSERT INTO scsisges.tavendvtasemanal (
        fnempleado,
        fcnombreemp,
        fiidsucursal,
        fcnombresuc,
        finumcecosuc,
        fiidpais,
        fcpais,
        ficanal,
        fccanal,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fntipoventa,
        fnlinea,
        fnmontototal,
        fisemana,
        fianio,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        'JOSE EMMANUEL GALVAN CASTAÑEDA',
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        520199,
        1,
        'MEXICO',
        1,
        'ELEKTRA',
        186584,
        'REGIONAL TIENDAS EKT GUANAJUATO CENTRO 6',
        186342,
        'ZONA GUANAJUATO CENTRO 6',
        186336,
        1,
        500,
        2350,
        20,
        2019,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivoreg
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivosemreg;

   --
   -- test spobjetivodiazon case 1: ...
   --
   PROCEDURE spobjetivodiazon IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivozon where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivozon (
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        186342,
        'hola',
        186336,
        'hola',
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivozon
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivodiazon;

   --
   -- test spobjetivosemzon case 1: ...
   --
   PROCEDURE spobjetivosemzon IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivozon where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivozon (
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fcdescterrirorio,
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        186342,
        'hola',
        186336,
        'hola',
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
    
    delete from scsisges.tavendvtasemanal where fcusrcreacion = 'PRUEBASUNITARIAS';
    
    INSERT INTO scsisges.tavendvtasemanal (
        fnempleado,
        fcnombreemp,
        fiidsucursal,
        fcnombresuc,
        finumcecosuc,
        fiidpais,
        fcpais,
        ficanal,
        fccanal,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fntipoventa,
        fnlinea,
        fnmontototal,
        fisemana,
        fianio,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        'JOSE EMMANUEL GALVAN CASTAÑEDA',
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        520199,
        1,
        'MEXICO',
        1,
        'ELEKTRA',
        186584,
        'REGIONAL TIENDAS EKT GUANAJUATO CENTRO 6',
        186342,
        'ZONA GUANAJUATO CENTRO 6',
        186336,
        1,
        500,
        2350,
        20,
        2019,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivozon
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivosemzon;

   --
   -- test spobjetivodiapais case 1: ...
   --
   PROCEDURE spobjetivodiapais IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivopais where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivopais (
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivopais
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivodiapais;

   --
   -- test spobjetivosempais case 1: ...
   --
   PROCEDURE spobjetivosempais IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.taobjetivopais where FCUSRCREACION = 'PRUEBASUNITARIAS';
   
   INSERT INTO scsisges.taobjetivopais (
        fiidpais,
        fdfecha,
        fnlinea,
        fclineadesc,
        fnsublinea,
        fnclase,
        fnsemana,
        fnanio,
        fnmontocredito,
        fnmontocontado,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        1,
        'hola',
        500,
        'TELEFONIA',
        501,
        530,
        20,
        2019,
        20000,
        15000,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
    
    delete from scsisges.tavendvtasemanal where fcusrcreacion = 'PRUEBASUNITARIAS';
    
  INSERT INTO scsisges.tavendvtasemanal (
        fnempleado,
        fcnombreemp,
        fiidsucursal,
        fcnombresuc,
        finumcecosuc,
        fiidpais,
        fcpais,
        ficanal,
        fccanal,
        fiidregion,
        fcdescregion,
        fiidzona,
        fcdesczonas,
        fiidterritorio,
        fntipoventa,
        fnlinea,
        fnmontototal,
        fisemana,
        fianio,
        fcusrcreacion,
        fcusrmodifico
    ) VALUES (
        255472,
        'JOSE EMMANUEL GALVAN CASTAÑEDA',
        199,
        'EKT IRAPUATO 4 LEANDRO VALLE',
        520199,
        1,
        'MEXICO',
        1,
        'ELEKTRA',
        186584,
        'REGIONAL TIENDAS EKT GUANAJUATO CENTRO 6',
        186342,
        'ZONA GUANAJUATO CENTRO 6',
        186336,
        1,
        500,
        2350,
        20,
        2019,
        'PRUEBASUNITARIAS',
        'PRUEBASUNITARIAS'
    );
                                         
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.taobjetivopais
           WHERE TRUNC (FDCREACION) = TRUNC (sysdate);
    
          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));
   END spobjetivosempais;

END test_paobjetivos;

/
