--------------------------------------------------------
--  DDL for Package Body TEST_PAREPORTES0002
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PAREPORTES0002" AS
    
  PROCEDURE spInsertGestiones AS
    numRegistros SMALLINT;
  BEGIN
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078,	
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,	
                   'CLIENTES PARA QUE COMPREN MAS',1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81,
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 254789, 309078, 
                   1, 1, 5, 'Le interesa una laptop hp modelo x', SYSDATE-1, 1,
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 33, 
                   'CLIENTES CON SUPER DESCUENTO', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 995214, 309078, 
                   1, 1, 5, 'Le interesa una impresora HP modelo xp2', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 79, 
                   'CLIENTES CON CDP DISPONIBLE', 0);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    INSERT INTO SCSISGES.TAGESTION(FIGESTIONID, FIPAISCU, FICANALCU, FISUCURSALCU, FIFOLIOCU, FCEMPNUM, 
                    FIMEDIOGESTIONID, FIRESULTGESTIONID, FITIPOGESTIONID, FCNOTAS, FDCREACION, FISTATUS, 
                    FDMODIFICACION, USRMODIFICO, FIPAISEMP, FICANALEMP, FISUCURSALEMP, FICAMPANAID, 
                    FCDESCCAMPANA, FIDESCGESTION)
            VALUES(SCSISGES.SEQGESTION.NEXTVAL, 1, 1, 2024, 558936, 309078, 
                   1, 2, 5, 'Test', SYSDATE-1, 1, 
                   SYSDATE-1, 'SCSISGES', 1, 1, 2024, 81, 
                   'CLIENTES PARA QUE COMPREN MAS', 1);
    COMMIT;               
    
    SELECT COUNT(*) INTO numRegistros FROM SCSISGES.TAGESTION WHERE  TRUNC(FDCREACION) = TRUNC(SYSDATE - 1);
    
    ut.expect(numRegistros, 'El numero de registros es mayor a 0').to_(be_greater_than(0));
    
    
  END spInsertGestiones;

  PROCEDURE spgestionesExitosa AS
  
    PA_DATA SYS_REFCURSOR;
    PA_CODE NUMBER;
    PA_MESSAGE VARCHAR2(200);
    PA_DETAIL VARCHAR2(200);

  
  BEGIN
    SCSISGES.PAREPORTES0002.SPGESTIONES(
        PA_DATA, PA_CODE, PA_MESSAGE, PA_DETAIL
    );
    
    ut.expect(PA_CODE,'Código de salida no es 0').to_(equal(0));
    ut.expect(PA_MESSAGE,'Mensaje de salida no es igual OK').to_(equal('OK'));
    
  END spgestionesExitosa;

  PROCEDURE spgestionesv2Exitosa AS
     PA_DATA SYS_REFCURSOR;
     PA_CODE NUMBER;
     PA_MESSAGE VARCHAR2(200);
     PA_DETAIL VARCHAR2(200);
  BEGIN
    SCSISGES.PAREPORTES0002.SPGESTIONESV2(
        PA_DATA, PA_CODE, PA_MESSAGE, PA_DETAIL
    );
    
    ut.expect(PA_CODE,'Código de salida no es 0').to_(equal(0));
    ut.expect(PA_MESSAGE,'Mensaje de salida no es igual OK').to_(equal('OK'));
  END spgestionesv2Exitosa;
  
  PROCEDURE spDeleteGestiones AS
    numRegistros SMALLINT;
  BEGIN
  
    DELETE FROM SCSISGES.TAGESTION WHERE TRUNC(FDCREACION) = TRUNC(SYSDATE - 1);
    
    COMMIT;
    
    SELECT COUNT(*) INTO numRegistros FROM SCSISGES.TAGESTION WHERE  TRUNC(FDCREACION) = TRUNC(SYSDATE - 1);
    
    ut.expect(numRegistros, 'El numero de registros no es 0').to_(equal(0));
    
  END spDeleteGestiones;
  
  PROCEDURE spgestionesNoExiste AS
    PA_DATA SYS_REFCURSOR;
    PA_CODE NUMBER;
    PA_MESSAGE VARCHAR2(200);
    PA_DETAIL VARCHAR2(200);
  BEGIN
     SCSISGES.PAREPORTES0002.SPGESTIONES(
        PA_DATA, PA_CODE, PA_MESSAGE, PA_DETAIL
    );
    
    ut.expect(PA_CODE,'Código de salida es '||PA_CODE).to_(equal(0));
  END spgestionesNoExiste;

END TEST_PAREPORTES0002;

/
