--------------------------------------------------------
--  DDL for Index IDX_TCESTCATBUZ
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCSISGES"."IDX_TCESTCATBUZ" ON "SCSISGES"."TCESTATUSCATBUZ" ("FIESTBUZONID", "FICATBUZONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_IDX" ;
