--------------------------------------------------------
--  DDL for Index IDX_VENFECHIST
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IDX_VENFECHIST" ON "SCSISGES"."TAVENTASACUMHIST" ("FDFECHAVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_IDX" ;
