--------------------------------------------------------
--  DDL for Index IX03TCAMPANACTE
--------------------------------------------------------

  CREATE INDEX "SCSISGES"."IX03TCAMPANACTE" ON "SCSISGES"."TTCAMPANACTE" ("FIIDPAIS", "FIIDTERRITORIO", "FIIDZONA", "FIIDREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TEMPORAL_IDX" ;
