--------------------------------------------------------
--  DDL for Package Body PQFXJOBCECOGEOGRAFIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."PQFXJOBCECOGEOGRAFIA" 
IS
    -- Author  : CCAMPOS
    -- Created : 02/08/2018
    -- Purpose : PROCESO QUE TRUNCARA LA TABLA TEMPORAL DE LA GEOGRAFIA

    CSL_0   CONSTANT INTEGER := 0;

    PROCEDURE SPFXTRUNCATBGEO
    IS
    BEGIN
        --SE TRUNCA LA TABLA DE LA GEOGRAFIA
        EXECUTE IMMEDIATE ('TRUNCATE TABLE SCSISGES.TACECOGEOGRAFIA');
    EXCEPTION
        WHEN OTHERS
        THEN
            SCSISGES.SPERRORES (SYSDATE,
                                SQLCODE,
                                SUBSTR (SQLERRM, 0, 200),
                                'PQFXJOBCECOGEOGRAFIA.SPFXTRUNCATBGEO');
    END SPFXTRUNCATBGEO;

    --PROCESO PARA HACER DELETE EN LA TABLA DE DESCARGA DE LA GEOGRAFIA
    PROCEDURE SPFXDDEPURATBGEO
    IS
    BEGIN
        DELETE SCSISGES.TACECOGEOGRAFIA
         WHERE FIIDPAIS > CSL_0;

        COMMIT;
    EXCEPTION
        WHEN OTHERS
        THEN
            ROLLBACK;
            SCSISGES.SPERRORES (SYSDATE,
                                SQLCODE,
                                SUBSTR (SQLERRM, 0, 200),
                                'PQFXJOBCECOGEOGRAFIA.SPFXDDEPURATBGEO');
    END SPFXDDEPURATBGEO;
END PQFXJOBCECOGEOGRAFIA;

/

  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRINFSISGES";
  GRANT EXECUTE ON "SCSISGES"."PQFXJOBCECOGEOGRAFIA" TO "USRSISGES";
