--------------------------------------------------------
--  DDL for Package Body TEST_PABUZONQYS
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PABUZONQYS" IS

   /* generated by utPLSQL for SQL Developer on 2019-03-20 11:49:09 */

   --
   -- test spguardabuzon case 1: ...
   --
   PROCEDURE spguardabuzon IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
      PA_CODE NUMBER;
      PA_MESSAGE VARCHAR2(10);
      i_tablename VARCHAR2(10);
      PA_CODIGO NUMBER;
      PA_MENSAJE VARCHAR2(200);
      PA_MENSAJEERROR VARCHAR2(200);
      v_count_real integer;
      v_count_max integer;
      pa_FCEMPNUM NUMBER;
      pa_FISUCURSAL NUMBER;
      pa_FICATBUZONID NUMBER;
      pa_FIESTBUZONID NUMBER;
      pa_FCTEXTOBUZON VARCHAR2(100);
      pa_FNTELEFONO VARCHAR2(10);
   BEGIN
      -- populate actual
    i_tablename := 'TABUZON';
    PA_FCEMPNUM := 309078;
    PA_FISUCURSAL := 2024;
    PA_FICATBUZONID := 1;
    PA_FIESTBUZONID := 1;
    PA_FCTEXTOBUZON := 'TEST';
    PA_FNTELEFONO := NULL;
      -- pabuzonqys.spguardabuzon;

    execute immediate 'select count(*) from TABUZON' into v_count_real;

  PABUZONQYS.SPGUARDABUZON(
    PA_FCEMPNUM => PA_FCEMPNUM,
    PA_FISUCURSAL => PA_FISUCURSAL,
    PA_FICATBUZONID => PA_FICATBUZONID,
    PA_FIESTBUZONID => PA_FIESTBUZONID,
    PA_FCTEXTOBUZON => PA_FCTEXTOBUZON,
    PA_FNTELEFONO => PA_FNTELEFONO,
    PA_CODIGO => PA_CODIGO,
    PA_MENSAJE => PA_MENSAJE,
    PA_MENSAJEERROR => PA_MENSAJEERROR );

      -- populate expected

      -- assert

    ut.expect(PA_CODE,'PA_CODE no es 0').to_(equal(0));
    ut.expect(v_count_real,'v_count_real no es 0').to_(equal(31));
    ut.expect(PA_MESSAGE,'PA_MESSAGE no es igual OK').to_(equal('OK'));

   END spguardabuzon;

   --
   -- test spobtienecatbuz case 1: ...
   --
   PROCEDURE spobtienecatbuz IS
      l_actual   INTEGER := 0;
      l_expected INTEGER := 1;
   BEGIN
      -- populate actual
      -- pabuzonqys.spobtienecatbuz;

      -- populate expected


      -- assert
      ut.expect(l_actual).to_equal(l_expected);
   END spobtienecatbuz;

END test_pabuzonqys;

/
