--------------------------------------------------------
--  DDL for Package Body TEST_PAVTASSEMANALES
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_PAVTASSEMANALES" IS
    /* generated by utPLSQL for SQL Developer on 2019-05-13 17:20:00 */

    --
    -- test spcampanasclte case 1: ...
    --

    PROCEDURE SPPROCESAVTASSEMVEND IS
    
    VL_VEND NUMBER := 0;
    VL_LINEAS NUMBER := 0;
    BEGIN
    
    SELECT COUNT(1) INTO VL_VEND FROM SCSISGES.TAVENDVTASEMANAL;
    SELECT COUNT(1) INTO VL_LINEAS FROM SCSISGES.TAVENDVTASEMANAL TV
    WHERE TV.FNLINEA NOT IN (SELECT TL.FNLINEA FROM SCSISGES.TCLINEA TL);
    
    ut.expect(
            VL_VEND,
            'Numero de registros en tabla procesada'
        ).to_(be_less_than(0));
    ut.expect(
            VL_LINEAS,
            'Numero de registros con una linea que no se encuentra en el catalogo TCLINEA'
        ).to_(be_greater_than(0));
    
    END SPPROCESAVTASSEMVEND;
    
    
    PROCEDURE SPPROCESAHISTORICO IS
    
    VL_VENTASHISTORICAS NUMBER := 0;
    VL_FECHAMAXIMAREG VARCHAR2(50) := '';
    VL_FECHAMINIMAREG VARCHAR2(50) := '';
    VL_FECHARULEMAX VARCHAR2(50) := '';
    VL_FECHARULEMIN VARCHAR2(50) := '';
    BEGIN
    
    SELECT COUNT(1) INTO VL_VENTASHISTORICAS FROM SCSISGES.TAVENTASACUMHIST;
    SELECT MAX(TO_CHAR(TH.FDFECHAVENTA,'DD-MM-YYYY')) INTO VL_FECHAMAXIMAREG FROM SCSISGES.TAVENTASACUMHIST TH;
    SELECT MIN(TO_CHAR(TH.FDFECHAVENTA,'DD-MM-YYYY')) INTO VL_FECHAMINIMAREG FROM SCSISGES.TAVENTASACUMHIST TH;
    SELECT TO_CHAR((SYSDATE-16),'DD-MM-YYYY') INTO VL_FECHARULEMAX FROM DUAL;
    SELECT MIN(TCC.FDFECHA) INTO VL_FECHARULEMIN FROM SCSISGES.TCCALENDARIOEKT TCC WHERE TCC.FIANIO = TO_CHAR(SYSDATE,'YYYY')-1;
    ut.expect(
            VL_VENTASHISTORICAS,
            'Numero de ventas en tabla historica'
        ).to_(be_less_than(0));
    ut.expect(
            VL_FECHAMAXIMAREG,
            'Fecha Maxima para tabla historica'
        ).to_equal(VL_FECHARULEMAX);
    ut.expect(
            VL_FECHAMINIMAREG,
            'Fecha Minima para la tabla historica'
        ).to_equal(VL_FECHARULEMIN);
    END SPPROCESAHISTORICO;
    
    
    PROCEDURE SPPROCESAOPERATIVO IS
    
    VL_VENTASPRODUCTIVAS NUMBER := 0;
    VL_FECHAMINIMA VARCHAR2(50) := '';
    VL_FECHA VARCHAR2(50) := '';
    VL_CONTEODIAS NUMBER := 0;
    BEGIN
    
    SELECT COUNT(1) INTO VL_VENTASPRODUCTIVAS FROM SCSISGES.TAVENTASACUMOPE;
    SELECT MIN(TO_CHAR(OPE.FDFECHAVENTA,'DD-MM-YYYY')) INTO VL_FECHAMINIMA FROM SCSISGES.TAVENTASACUMOPE OPE;
    SELECT TO_CHAR((SYSDATE-15),'DD-MM-YYYY') INTO VL_FECHA FROM DUAL;
    SELECT COUNT(DISTINCT TOPE.FDFECHAVENTA) INTO VL_CONTEODIAS FROM SCSISGES.TAVENTASACUMOPE TOPE WHERE TOPE.FDFECHAVENTA BETWEEN SYSDATE-16 AND SYSDATE-1;
    ut.expect(
            VL_VENTASPRODUCTIVAS,
            'Numero de ventas en tabla productiva'
        ).to_(be_less_than(0));
    ut.expect(
            VL_FECHAMINIMA,
            'Fecha MINIMA para tabla productiva'
        ).to_equal(VL_FECHA);
    ut.expect(
            VL_CONTEODIAS,
            'Cantidad de dias que guarda la tabla operativa'
        ).to_equal(15);
    END SPPROCESAOPERATIVO;
    
END TEST_PAVTASSEMANALES;

/
