--------------------------------------------------------
--  DDL for Package Body TEST_GOALSDAILYANDWEEKLY
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE BODY "SCSISGES"."TEST_GOALSDAILYANDWEEKLY" IS

   /* generated by utPLSQL for SQL Developer on 2019-03-19 15:41:26 */
   
   
   PROCEDURE spinserta_TAOBJETIVOS is  
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.TAOBJETIVOS t where TRUNC (FDCREACION) = '25/03/2019';
                                                                                                                                                                                                                                                                    
       INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000100',
                                       3.00,
                                       1.59,
                                       1.59,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');
                                       
      INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000101',
                                       3.00,
                                       1.22,
                                       1.22,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');  
                                       
            INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000100',
                                       3.00,
                                       1.02,
                                       1.02,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');
                                       
         INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520110',
                                       -530,
                                       '4000000101',
                                       3.00,
                                       1.04,
                                       1.04,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');                              
                                        
                                       
        INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520110',
                                       -730,
                                       '4000000100',
                                       3.00,
                                       .96,
                                       .96,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');
                                       
SELECT COUNT (1)
        INTO conteoreg
        FROM SCSISGES.Taobjetivos
       WHERE TRUNC (FDCREACION) = '25/03/2019';

      ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                                    
      
   end spinsertA_TAOBJETIVOS;   
      
            
   PROCEDURE spinserta_TCLINEA is  
   conteoreg   NUMBER;
   
   BEGIN        
      delete from scsisges.TCLINEA t where TRUNC (FDCREACION) = '25/03/2019';  
                                            
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(400,
                                    'COMPUTO',
                                    13,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
     INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(530,
                                    'ACCESORIOS',
                                    31,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(100,
                                    'ELECTRONICA',
                                    10,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(200,
                                    'LINEA BLANCA',
                                    11,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(520,
                                    'ENTRETENIMIENTO',
                                    30,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
       INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(500,
                                    'TELEFONIA',
                                    14,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);                                   
                                                                                                                                                                                                                                                                               
    SELECT COUNT (1)
            INTO conteoreg
            FROM SCSISGES.TCLINEA
           WHERE TRUNC (fdmodifico) = '25/03/2019';

          ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0)); 
  end spinserta_TCLINEA;                                                                                                  
 

    PROCEDURE spinserta_SUCURSAL is     
    conteoreg   NUMBER;
   
   BEGIN        
      delete from scsisges.TCFXSUCURSAL t where TRUNC (fdmodificacion) = '25/03/2019'; 
      
      insert into scsisges.tcfxsucursal(fiidpais,
                                        fiidterritorio,
                                        fiidzona,
                                        fiidregion,
                                        fiidsucursal,
                                        fiidcanal,
                                        finumcecosuc,
                                        fcnombresuc,
                                        fdfecactual,
                                        fctipo,
                                        fdiniciooperaciones,
                                        fniva,
                                        fiestatus,
                                        fiiddivision,
                                        fccalle,
                                        fcnumext,
                                        fcnumint,
                                        fccolonia,
                                        fcmunicipio,
                                        fcestado,
                                        fccp,
                                        fiidentidad,
                                        fdmodificacion,
                                        fcusrmodifico)
                                 VALUES(1,
                                        186336,
                                        186338,
                                        186385,
                                        9998,
                                        1,
                                        529998,
                                        'EKT ZARAGOZA',
                                        SYSDATE,
                                        'TIENDA',
                                        SYSDATE,
                                        0.1600,
                                        1,
                                        NULL,
                                        'AV 16 DE SEPTIEMBRE',
                                        '115',
                                        '5',
                                        'PASEO DE SANTA MARIA',
                                        'CUAUTITLAN',
                                        'MEXICO',
                                        '54800',
                                        1,
                                        '25/03/2019',
                                        'SCSISGES');
                                        
      insert into scsisges.tcfxsucursal(fiidpais,
                                        fiidterritorio,
                                        fiidzona,
                                        fiidregion,
                                        fiidsucursal,
                                        fiidcanal,
                                        finumcecosuc,
                                        fcnombresuc,
                                        fdfecactual,
                                        fctipo,
                                        fdiniciooperaciones,
                                        fniva,
                                        fiestatus,
                                        fiiddivision,
                                        fccalle,
                                        fcnumext,
                                        fcnumint,
                                        fccolonia,
                                        fcmunicipio,
                                        fcestado,
                                        fccp,
                                        fiidentidad,
                                        fdmodificacion,
                                        fcusrmodifico)
                                 VALUES(1,
                                        186336,
                                        186338,
                                        186385,
                                        9999,
                                        1,
                                        529999,
                                        'EKT ZARAGOZA',
                                        SYSDATE,
                                        'TIENDA',
                                        SYSDATE,
                                        0.1600,
                                        1,
                                        NULL,
                                        'AV 19 DE SEPTIEMBRE',
                                        '115',
                                        '5',
                                        'PASEO DE SANTA MONICA',
                                        'IZCALLI',
                                        'MEXICO',
                                        '55800',
                                        1,
                                        '25/03/2019',
                                        'SCSISGES');                                  
                                        
                                        
          SELECT COUNT (1)
                  INTO conteoreg
                  FROM SCSISGES.tcfxsucursal
                 WHERE TRUNC (fdmodificacion) = '25/03/2019';

              ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0)); 
 end spinserta_SUCURSAL;                                    

   --
   -- test spobjetivosemanal case 1: ...
   --
   PROCEDURE spobjetivodiario_consulta IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := 186387;
    PA_FCFECHA := 20190313;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivodiario_consulta;

   --
   -- test spobjetivosemanal case 2.1: ...
   --
   PROCEDURE spobjetivodiario_CDFE IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := 186387;
    PA_FCFECHA := 30190313;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivodiario_CDFE;

   --
   -- test spobjetivosemanal case 2.2: ...
   --
   PROCEDURE spobjetivodiario_CCNE IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := 186388;
    PA_FCFECHA := 20190313;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivodiario_CCNE;

   --
   -- test spobjetivosemanal case 3.1: ...
   --
   PROCEDURE spobjetivodiario_CCN IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := NULL;
    PA_FCFECHA := 20190313;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivodiario_CCN;

   --
   -- test spobjetivosemanal case 3.2: ...
   --
   PROCEDURE spobjetivodiario_CFN IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := 186387;
    PA_FCFECHA := NULL;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivodiario_CFN;

   --
   -- test spobjetivosemanal case 4: ...
   --
   PROCEDURE spobjetivodiario_CCVD IS
    PA_NUMCECO NUMBER;
    PA_FCFECHA VARCHAR2(200);
    PA_CURDATOS SYS_REFCURSOR;
    PA_FNCODERROR NUMBER;
    PA_FCDESERROR VARCHAR2(200);
   BEGIN
    PA_NUMCECO := 'Hola';
    PA_FCFECHA := 20190313;

      -- populate actual
      -- pafxregionalmod.spobjetivodiario;
    PAFXREGIONALMOD.SPOBJETIVODIARIO(
        PA_NUMCECO => PA_NUMCECO,
        PA_FCFECHA => PA_FCFECHA,
        PA_CURDATOS => PA_CURDATOS,
        PA_FNCODERROR => PA_FNCODERROR,
        PA_FCDESERROR => PA_FCDESERROR
    );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_not_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_not_null();
   END spobjetivodiario_CCVD;

   -----------------------------------------------------------------------------

    PROCEDURE spinserta_TCLINEAOBJSEM IS 
    conteoreg   NUMBER;
   
   BEGIN        
      delete from scsisges.TCLINEA t where TRUNC (FDCREACION) = '25/03/2019'; 
      
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(400,
                                    'COMPUTO',
                                    13,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
     INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(530,
                                    'ACCESORIOS',
                                    31,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(100,
                                    'ELECTRONICA',
                                    10,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);
                                    
      INSERT INTO SCSISGES.TCLINEA (fnlinea,
                                    fcprdlindesc,
                                    fnlineaprod,
                                    fdcreacion,
                                    fdmodifico,
                                    fcusrmodifico,
                                    fnestatus)
                             VALUES(200,
                                    'LINEA BLANCA',
                                    11,
                                    sysdate,
                                    '25/03/2019',
                                    'USERS',
                                    1);

  SELECT COUNT (1)
          INTO conteoreg
          FROM SCSISGES.TCLINEA
         WHERE TRUNC (fdmodifico) = '25/03/2019';

      ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0)); 
  end spinserta_TCLINEAOBJSEM;
  
  
  PROCEDURE spinserta_SUCURSALOBJSEM is 
     conteoreg   NUMBER;
   
   BEGIN        
      delete from scsisges.TCFXSUCURSAL t where TRUNC (fdmodificacion) = '25/03/2019'; 
      
      insert into scsisges.tcfxsucursal(fiidpais,
                                        fiidterritorio,
                                        fiidzona,
                                        fiidregion,
                                        fiidsucursal,
                                        fiidcanal,
                                        finumcecosuc,
                                        fcnombresuc,
                                        fdfecactual,
                                        fctipo,
                                        fdiniciooperaciones,
                                        fniva,
                                        fiestatus,
                                        fiiddivision,
                                        fccalle,
                                        fcnumext,
                                        fcnumint,
                                        fccolonia,
                                        fcmunicipio,
                                        fcestado,
                                        fccp,
                                        fiidentidad,
                                        fdmodificacion,
                                        fcusrmodifico)
                                 VALUES(1,
                                        186336,
                                        186338,
                                        186385,
                                        9998,
                                        1,
                                        529998,
                                        'EKT ZARAGOZA',
                                        SYSDATE,
                                        'TIENDA',
                                        SYSDATE,
                                        0.1600,
                                        1,
                                        NULL,
                                        'AV 16 DE SEPTIEMBRE',
                                        '115',
                                        '5',
                                        'PASEO DE SANTA MARIA',
                                        'CUAUTITLAN',
                                        'MEXICO',
                                        '54800',
                                        1,
                                        '25/03/2019',
                                        'SCSISGES');
                                        
      insert into scsisges.tcfxsucursal(fiidpais,
                                        fiidterritorio,
                                        fiidzona,
                                        fiidregion,
                                        fiidsucursal,
                                        fiidcanal,
                                        finumcecosuc,
                                        fcnombresuc,
                                        fdfecactual,
                                        fctipo,
                                        fdiniciooperaciones,
                                        fniva,
                                        fiestatus,
                                        fiiddivision,
                                        fccalle,
                                        fcnumext,
                                        fcnumint,
                                        fccolonia,
                                        fcmunicipio,
                                        fcestado,
                                        fccp,
                                        fiidentidad,
                                        fdmodificacion,
                                        fcusrmodifico)
                                 VALUES(1,
                                        186336,
                                        186338,
                                        186385,
                                        9999,
                                        1,
                                        529999,
                                        'EKT ZARAGOZA',
                                        SYSDATE,
                                        'TIENDA',
                                        SYSDATE,
                                        0.1600,
                                        1,
                                        NULL,
                                        'AV 19 DE SEPTIEMBRE',
                                        '115',
                                        '5',
                                        'PASEO DE SANTA MONICA',
                                        'IZCALLI',
                                        'MEXICO',
                                        '55800',
                                        1,
                                        '25/03/2019',
                                        'SCSISGES');                                  
                                        
                                        
          SELECT COUNT (1)
                  INTO conteoreg
                  FROM SCSISGES.tcfxsucursal
                 WHERE TRUNC (fdmodificacion) = '25/03/2019';

     ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0)); 
 end spinserta_sucursalobjsem;
  
 
 PROCEDURE spinserta_OBJETIVOSSEM IS
   conteoreg   NUMBER;
   
   BEGIN        
   delete from scsisges.TAOBJETIVOS t where TRUNC (FDCREACION) = '25/03/2019';
                                                                                                                                                                                                                                                                    
       INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000100',
                                       3.00,
                                       1.59,
                                       1.59,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');
                                       
      INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000101',
                                       3.00,
                                       1.22,
                                       1.22,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');  
                                       
            INSERT INTO SCSISGES.TAOBJETIVOS(fdfecha,
                                        fnccosto,
                                        fnproducto,
                                        fcidconcepto,
                                        fntipogto,
                                        fnmontopesos,
                                        fnmontolocal,
                                        fdfechaarribo,
                                        fdfechaactualiza,
                                        FDCREACION,
                                        FDMODIFICO,
                                        FCUSRMODIFICO)
                               VALUES( '20190325',
                                       '520107',
                                       -530,
                                       '4000000100',
                                       3.00,
                                       1.02,
                                       1.02,
                                       '10/01/2019',
                                       '15/01/2019',
                                       '25/03/2019',
                                       '25/01/2019',
                                       'USER');
                                       
   SELECT COUNT (1)
        INTO conteoreg
        FROM SCSISGES.Taobjetivos
       WHERE TRUNC (FDCREACION) = '25/03/2019';

      ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0)); 
      
   END spinserta_OBJETIVOSSEM;
      
   PROCEDURE spinserta_PERFILES IS
     conteoreg NUMBER;
     BEGIN
       
     INSERT INTO TCPERFILESEMP (fiidperfil,
                                fnfuncionsap,
                                fcnombreperfil,
                                fcdescripcion,
                                fcusrmodifico,
                                fdmodificacion,
                                fntipoperfil)
                         VALUES(5,
                                8071,
                                'Vendedor QA',
                                'Socio vendedor QA',
                                'SISGES',
                                '25/03/2019',
                                1);
                                
      INSERT INTO TCPERFILESEMP (fiidperfil,
                                fnfuncionsap,
                                fcnombreperfil,
                                fcdescripcion,
                                fcusrmodifico,
                                fdmodificacion,
                                fntipoperfil)
                         VALUES(4,
                                8070,
                                'Vendedor SC',
                                'Socio vendedor SC',
                                'SISGES',
                                '25/03/2019',
                                1);                          
                                
      SELECT COUNT (1)
        INTO conteoreg
        FROM SCSISGES.TCPERFILESEMP
       WHERE TRUNC (fdmodificacion) = '25/03/2019';

      ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));       
      END spinserta_PERFILES;                                 
     
     
     PROCEDURE spinserta_TAEMPLEADOPF IS
     conteoreg number;
       
     BEGIN
     DELETE FROM TAEMPLEADOPF T WHERE TRUNC(T.FDULTIMAMODIFICACION)='25/03/2019';
     
     insert into TAEMPLEADOPF(fnempleado,
                              fcnombre,
                              fcapaterno,
                              fcamaterno,
                              fnfuncionsap,
                              fnempleadojefe,
                              fncc,
                              fcnegocio,
                              fiidlabora,
                              fdultimamodificacion,
                              fdbaja,
                              fdalta,
                              fisituacion,
                              fiidsucursal,
                              fiidperfil,
                              fnorigen,
                              fcusrcreacion,
                              fdcreacion,
                              fcusrmodifico,
                              fdmodifico
                              )
                      VALUES(999921,
                             'MIGUEL DE JESUS',
                             'ANGEL',
                             'LOPEZ',
                             8035,
                             677095,
                             529796,
                             'EKT',
                             1,
                             '25/03/2019',
                             '01/01/1901',
                             '04/04/2018',
                             1,
                             9796,
                             3,
                             1,
                             'SCSISGES',
                             '25/03/2019',
                             'SCSISGES',
                             '25/03/2019');
                             
    insert into TAEMPLEADOPF(fnempleado,
                              fcnombre,
                              fcapaterno,
                              fcamaterno,
                              fnfuncionsap,
                              fnempleadojefe,
                              fncc,
                              fcnegocio,
                              fiidlabora,
                              fdultimamodificacion,
                              fdbaja,
                              fdalta,
                              fisituacion,
                              fiidsucursal,
                              fiidperfil,
                              fnorigen,
                              fcusrcreacion,
                              fdcreacion,
                              fcusrmodifico,
                              fdmodifico
                              )
                      VALUES(888896,
                             'LUIS FERNANDO',
                             'SAGASTE',
                             'ESPINOZA',
                             8067,
                             826117,
                             524182,
                             'EKT',
                             1,
                             '25/03/2019',
                             '01/01/1901',
                             '04/04/2018',
                             1,
                             4182,
                             1,
                             1,
                             'SCSISGES',
                             '25/03/2019',
                             'SCSISGES',
                             '25/03/2019');
        insert into TAEMPLEADOPF(fnempleado,
                              fcnombre,
                              fcapaterno,
                              fcamaterno,
                              fnfuncionsap,
                              fnempleadojefe,
                              fncc,
                              fcnegocio,
                              fiidlabora,
                              fdultimamodificacion,
                              fdbaja,
                              fdalta,
                              fisituacion,
                              fiidsucursal,
                              fiidperfil,
                              fnorigen,
                              fcusrcreacion,
                              fdcreacion,
                              fcusrmodifico,
                              fdmodifico
                              )
                      VALUES(177772,
                             'DOROTEA',
                             'RAMOS',
                             'SALDAÑA',
                             8067,
                             876531,
                             522649,
                             'EKT',
                             2,
                             '25/03/2019',
                             '01/01/1901',
                             '04/04/2018',
                             1,
                             2649,
                             1,
                             1,
                             'SCSISGES',
                             '25/03/2019',
                             'SCSISGES',
                             '25/03/2019');
                             
       insert into TAEMPLEADOPF(fnempleado,
                              fcnombre,
                              fcapaterno,
                              fcamaterno,
                              fnfuncionsap,
                              fnempleadojefe,
                              fncc,
                              fcnegocio,
                              fiidlabora,
                              fdultimamodificacion,
                              fdbaja,
                              fdalta,
                              fisituacion,
                              fiidsucursal,
                              fiidperfil,
                              fnorigen,
                              fcusrcreacion,
                              fdcreacion,
                              fcusrmodifico,
                              fdmodifico
                              )
                      VALUES(399925,
                             'NICANOR',
                             'HERNANDEZ',
                             'CARBALLIDO',
                             8067,
                             876786,
                             529702,
                             'EKT',
                             1,
                             '25/03/2019',
                             '01/01/1901',
                             '04/04/2018',
                             1,
                             9702,
                             1,
                             1,
                             'SCSISGES',
                             '25/03/2019',
                             'SCSISGES',
                             '25/03/2019');                                                                                          
    
   SELECT COUNT (1)
        INTO conteoreg
        FROM SCSISGES.TAEMPLEADOPF
       WHERE TRUNC (fdultimamodificacion) = '25/03/2019';

      ut.expect (conteoreg, 'El numero de registros es igual a 0').to_(be_greater_than (0));                         
     END spinserta_TAEMPLEADOPF;                            
   --
   -- test spobjetivosemanal case 1: ...
   --
   PROCEDURE spobjetivosemanal_consulta IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 186387;
      PA_FISEMANA := 11;
      PA_FIANIO := 2019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
   );

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_consulta;

   --
   -- test spobjetivosemanal case 2.1: ...
   --
   PROCEDURE spobjetivosemanal_CDNE IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 186387;
      PA_FISEMANA := 10;
      PA_FIANIO := 3019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_CDNE;

   --
   -- test spobjetivosemanal case 2.2: ...
   --
   PROCEDURE spobjetivosemanal_CCNE IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 186388;
      PA_FISEMANA := 11;
      PA_FIANIO := 2019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_CCNE;

   --
   -- test spobjetivosemanal case 3.1: ...
   --
   PROCEDURE spobjetivosemanal_CCN IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := NULL;
      PA_FISEMANA := 11;
      PA_FIANIO := 2019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_CCN;

   --
   -- test spobjetivosemanal case 3.2: ...
   --
   PROCEDURE spobjetivosemanal_CSN IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 186387;
      PA_FISEMANA := NULL;
      PA_FIANIO := 2019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_CSN;

   --
   -- test spobjetivosemanal case 3.3: ...
   --
   PROCEDURE spobjetivosemanal_CAN IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 186387;
      PA_FISEMANA := 11;
      PA_FIANIO := NULL;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_not_null();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_null();
   END spobjetivosemanal_CAN;

   --
   -- test spobjetivosemanal case 4: ...
   --
   PROCEDURE spobjetivosemanal_CCVD IS
      PA_NUMCECO NUMBER;
      PA_FISEMANA NUMBER;
      PA_FIANIO NUMBER;
      PA_CURDATOS SYS_REFCURSOR;
      PA_FNCODERROR NUMBER;
      PA_FCDESERROR VARCHAR2(200);
   BEGIN
      PA_NUMCECO := 'Hola';
      PA_FISEMANA := 11;
      PA_FIANIO := 2019;

   PAFXREGIONALMOD.SPOBJETIVOSEMANAL(
       PA_NUMCECO => PA_NUMCECO,
       PA_FISEMANA => PA_FISEMANA,
       PA_FIANIO => PA_FIANIO,
       PA_CURDATOS => PA_CURDATOS,
       PA_FNCODERROR => PA_FNCODERROR,
       PA_FCDESERROR => PA_FCDESERROR
  );
      -- populate actual
      -- pafxregionalmod.spobjetivosemanal;

      -- populate expected
      -- ...

      -- assert
   ut.expect(PA_CURDATOS,'El cursor esta vacio').to_be_empty();
   ut.expect(PA_FNCODERROR,'El codigo de error no es null').to_be_not_null();
   ut.expect(PA_FCDESERROR,'El mensaje de error no es null').to_be_not_null();
   END spobjetivosemanal_CCVD;

END test_goalsdailyandweekly;

/
