--------------------------------------------------------
--  DDL for Index IDX_CRECTEPD03
--------------------------------------------------------

  CREATE UNIQUE INDEX "SCVENTASTIENDA"."IDX_CRECTEPD03" ON "SCVENTASTIENDA"."CRECTEUNICPED" ("FINOPEDIDO", "FISUCURSAL", "FICANAL", "FIPAIS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT) LOCAL
 (PARTITION "CRECTEUNIC01" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP01_IDX" , 
 PARTITION "CRECTEUNIC02" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP02_IDX" , 
 PARTITION "CRECTEUNIC03" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP03_IDX" , 
 PARTITION "CRECTEUNIC04" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP04_IDX" , 
 PARTITION "CRECTEUNIC05" 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CRECTEUNICP_RP05_IDX" ) ;
