--------------------------------------------------------
--  DDL for Index IX_CTETIENDAH03
--------------------------------------------------------

  CREATE INDEX "SCVENTASTIENDA"."IX_CTETIENDAH03" ON "SCVENTASTIENDA"."TACTETIENDAHIST" ("FIPAIS", "FICANAL", "FISUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACENCLITI_RP01_IDX" ;
