--------------------------------------------------------
--  DDL for Table PEDIDOS_CREDITO
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."PEDIDOS_CREDITO" 
   (	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(5,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FDFECHASURT" DATE, 
	"FDINIPER" DATE, 
	"FNIMPORTEABONO" NUMBER(15,2), 
	"FDULTPAGO" DATE, 
	"FNIMPORTEULTPAGO" NUMBER(15,2), 
	"FIPLAZO" NUMBER(5,0), 
	"FIPERIODO" NUMBER(5,0), 
	"FNENGANCHE" NUMBER(15,2), 
	"FNSALDO" NUMBER(15,2), 
	"FNMORATORIOS" NUMBER(15,2), 
	"FNSALDOATRASADO" NUMBER(15,2), 
	"FIPERVENCIDOS" NUMBER(5,0), 
	"FIPERINACTIVIDAD" NUMBER(5,0), 
	"FIPERATRASO" NUMBER(5,0), 
	"FIPERATRAACUM" NUMBER(5,0), 
	"FICLASIFCUENTA" NUMBER(5,0), 
	"FINOGESTIONES" NUMBER(5,0), 
	"FIGESTSINCOBRO" NUMBER(5,0), 
	"FDULTIMAVISITA" DATE, 
	"FIRESULUVISITA" NUMBER(5,0), 
	"FINOPAGOS" NUMBER(5,0), 
	"FDULTIMOABONO" DATE, 
	"FNULTIMOABONO" NUMBER(15,2), 
	"FNULTABONOMORA" NUMBER(15,2), 
	"FNBONIFICA" NUMBER(15,2), 
	"FNIMPPAGARBONIF" NUMBER(15,2), 
	"FIPEDSTATUS" NUMBER(5,0), 
	"FDFECULTACT" DATE, 
	"FIDESPID" NUMBER(5,0), 
	"FNSDOANTMORA" NUMBER(15,2), 
	"FINOVECESATR" NUMBER(5,0), 
	"FIRUTA" NUMBER(10,0), 
	"FDCSALDOCAPITAL" NUMBER(15,2), 
	"FDCINTXFINANCIAR" NUMBER(15,2), 
	"FDCSALDOORIGINAL" NUMBER(15,2), 
	"FDCINTTOTXATRASO" NUMBER(15,2), 
	"FIPAGOSCAPITAL" NUMBER(15,2), 
	"FIPAGOSINTERESES" NUMBER(15,2), 
	"FCOBSERVACION" VARCHAR2(60 BYTE), 
	"FIDEPTOID" NUMBER(5,0), 
	"FIZONAID" NUMBER(10,0), 
	"FCEMPNUM" VARCHAR2(10 BYTE), 
	"FDFECHACANC" DATE, 
	"FNCREDVARIOS" NUMBER(15,2), 
	"FISEMATRAS" NUMBER(5,0), 
	"FITIPODEPTO" NUMBER(5,0), 
	"FIUNIDADNEGOCIO" NUMBER(5,0), 
	"FNPRECIOD" NUMBER(15,2), 
	"FIIDZONACOBZA" NUMBER(10,0), 
	"FIIDORIGEN" NUMBER(5,0), 
	"FNIMPTOTVENTA" NUMBER(15,2), 
	"FIEMISION" NUMBER(5,0), 
	"FISERIE" NUMBER(5,0), 
	"FIPERACTUAL" NUMBER(5,0), 
	"FIPERCORRIDO" NUMBER(5,0), 
	"FISTATUSEMISION" NUMBER(5,0), 
	"FCFOLIOPARAM" NUMBER(10,0), 
	"FITIPOCLIENTE" NUMBER(5,0), 
	"FIDIASSERV" NUMBER(5,0), 
	"FIDIASGRACIA" NUMBER(5,0), 
	"FISTATUSREGIONAL" NUMBER(5,0), 
	"FCEMPNUMET" VARCHAR2(10 BYTE), 
	"FNIMPPAGADO" NUMBER(15,2), 
	"FNIMPDEVENG" NUMBER(15,2), 
	"FNULTIMPMORA" NUMBER(15,2), 
	"FCSTATCARTERA" VARCHAR2(6 BYTE), 
	"FCCLASCAR" VARCHAR2(1 BYTE), 
	"FISALDOIDNCALVENC" NUMBER(15,2), 
	"FISOLICITUDID" NUMBER(10,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICACION" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "PEDCREDIT001"  VALUES LESS THAN (800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP01_DAT" , 
 PARTITION "PEDCREDIT002"  VALUES LESS THAN (1600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP02_DAT" , 
 PARTITION "PEDCREDIT003"  VALUES LESS THAN (2400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP03_DAT" , 
 PARTITION "PEDCREDIT004"  VALUES LESS THAN (3200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP04_DAT" , 
 PARTITION "PEDCREDIT005"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP05_DAT" , 
 PARTITION "PEDCREDIT006"  VALUES LESS THAN (4800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP06_DAT" , 
 PARTITION "PEDCREDIT007"  VALUES LESS THAN (5600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP07_DAT" , 
 PARTITION "PEDCREDIT008"  VALUES LESS THAN (6400) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP08_DAT" , 
 PARTITION "PEDCREDIT009"  VALUES LESS THAN (7200) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP09_DAT" , 
 PARTITION "PEDCREDIT010"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP10_DAT" , 
 PARTITION "PEDCREDIT011"  VALUES LESS THAN (8800) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP11_DAT" , 
 PARTITION "PEDCREDIT012"  VALUES LESS THAN (9600) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP12_DAT" , 
 PARTITION "PEDCREDIT013"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_PEDIDOS_CR_RP13_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."PEDIDOS_CREDITO" TO "USRINFSISGES";
