--------------------------------------------------------
--  DDL for Table TACREDCTECTES
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDCTECTES" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TACTESCRED_01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP01_DAT" , 
 PARTITION "TACTESCRED_02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP02_DAT" , 
 PARTITION "TACTESCRED_03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP03_DAT" , 
 PARTITION "TACTESCRED_04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP04_DAT" , 
 PARTITION "TACTESCRED_05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACRCTEST_RP05_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCTECTES" TO "USRINFVENTAST";
