--------------------------------------------------------
--  DDL for Table TACREDINVES
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDINVES" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FISOLICITUDID" NUMBER(15,0), 
	"FIINVESTSTAT" NUMBER(5,0), 
	"FCEMPNO" VARCHAR2(10 CHAR), 
	"FDINVESTFEC" DATE DEFAULT TO_DATE('01/01/1901','dd/mm/yyyy'), 
	"FCOBSERVINV" VARCHAR2(150 CHAR), 
	"FITRANNO" VARCHAR2(15 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACREDINVE_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDINVES" TO "USRINFVENTAST";
