--------------------------------------------------------
--  DDL for Table TACREDCLIENHST
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TACREDCLIENHST" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FIIDPERSONA" NUMBER(15,0), 
	"FITIPOCLIENTE" NUMBER(5,0), 
	"FIFISMOR" NUMBER(5,0), 
	"FDFECHAALTA" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FITRANNO" NUMBER(15,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACREDCLIE_RP01_DAT" 
  PARTITION BY RANGE ("FDFECHAALTA") 
 (PARTITION "PTACREDCLIENTES1"  VALUES LESS THAN (TO_DATE(' 2019-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TACREDCLIE_RP01_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TACREDCLIENHST" TO "USRINFVENTAST";
