--------------------------------------------------------
--  DDL for Table TAEST01001_0220
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_0220" 
   (	"FINOPEDIDO" NUMBER(10,0), 
	"FIPEDSTAT" NUMBER(3,0), 
	"FNPEDSALDO" NUMBER(13,2), 
	"FNIMPPAGADO_" NUMBER(9,2), 
	"FNIMPDEVENG_" NUMBER(9,2), 
	"FNPEDIMPMORA" NUMBER(9,2), 
	"FINOATRASOS" NUMBER(3,0), 
	"FCSTATCARTERA" VARCHAR2(6 CHAR), 
	"FICLASIFCUENTA" NUMBER(3,0), 
	"FIPERIODOACT" NUMBER(5,0), 
	"FDFECULTPAGO" DATE, 
	"FNDIASDESDESURT" NUMBER(5,0), 
	"FNPEDSALDOANTE" NUMBER(13,2), 
	"SEMVEN_" NUMBER(5,0), 
	"INACTSEMANAS_" NUMBER(5,0), 
	"ATRASOSEMANAS_" NUMBER(5,0), 
	"IMPATRA_" NUMBER(10,2), 
	"FNMOVPIMP" NUMBER(13,2), 
	"FNGESTIONCCOB" NUMBER(3,0), 
	"FNGESTIONSCOB" NUMBER(3,0), 
	"FDFECGEST" DATE, 
	"FIVISITAID" NUMBER(3,0), 
	"FITIPOVENTA" NUMBER(3,0), 
	"PAGANDO" VARCHAR2(8 CHAR), 
	"BONIFICAREMOS" VARCHAR2(8 CHAR), 
	"FNULTIMPMORA" NUMBER(9,2), 
	"FNMOVPIMPMOR" NUMBER(13,2), 
	"FINOPERIODOCORR_" NUMBER(5,0), 
	"FIPERINAC_" NUMBER(3,0), 
	"SEMATRA_" NUMBER(4,0), 
	"FNIMPPAGADO" NUMBER(13,2), 
	"FNIMPDEVENG" NUMBER(13,2), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA02_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0220" TO "USRINFVENTAST";
