--------------------------------------------------------
--  DDL for Table TAEST01001_0110
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_0110" 
   (	"FINOPEDIDO" NUMBER(10,0), 
	"FIPRODID" NUMBER(10,0), 
	"FCPRODTIPO" VARCHAR2(2 CHAR), 
	"FICANTART" NUMBER(5,0), 
	"FNPRCUNIT" NUMBER(9,2), 
	"FNPDCTODESCTO" NUMBER(9,2), 
	"FNIMPSOBREP" NUMBER(11,4), 
	"FNCOSTOPDCTO" NUMBER(9,2), 
	"FNPORCPROMOENG" NUMBER(4,2), 
	"FICVEPROM" NUMBER(10,0), 
	"FNPRODDESCTOE" NUMBER(9,2), 
	"FNDESCTOMKT" NUMBER(9,2), 
	"FNINTERESES" NUMBER(8,2), 
	"FIPORCIVA" NUMBER(9,2), 
	"FITIPOBLOQUEO" NUMBER(3,0), 
	"FIDEPTO" NUMBER(10,0), 
	"FISUBDEPTO" NUMBER(10,0), 
	"FNPRECIOVENTA" NUMBER(14,2), 
	"FIIDGEXT" NUMBER(10,0), 
	"FNCOMISIONV" NUMBER(7,2), 
	"FNCOMISIONG" NUMBER(7,2), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA01_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0110" TO "USRINFVENTAST";
