--------------------------------------------------------
--  DDL for Table TAEST01001_4633
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_4633" 
   (	"FINOPEDIDO" NUMBER(10,0), 
	"FNPEDTOTAL" NUMBER(13,2), 
	"FNPEDSALDO" NUMBER(13,2), 
	"FIPLAZO" NUMBER(3,0), 
	"FNPEDULTPAGO" NUMBER(9,2), 
	"FDVENCIMIENTO" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA03_DAT" ;
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4633" TO "USRINFVENTAST";
