--------------------------------------------------------
--  DDL for Table TAEST01001_4380
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_4380" 
   (	"FISOLICITUDID" NUMBER(10,0), 
	"FIINVESTSTAT" NUMBER(3,0), 
	"FCEMPNO" VARCHAR2(6 BYTE), 
	"FDINVESTFEC" DATE, 
	"FCOBSERVINV" VARCHAR2(100 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA03_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_4380" TO "USRINFVENTAST";
