--------------------------------------------------------
--  DDL for Table TAEST01001_0010
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAEST01001_0010" 
   (	"FINGCIOID" NUMBER(3,0), 
	"FINOTIENDA" NUMBER(5,0), 
	"FICTEID" NUMBER(10,0), 
	"FIDIGITOVER" NUMBER(3,0), 
	"FIOCUID" NUMBER(5,0), 
	"FCCTENOMBRE" VARCHAR2(18 CHAR), 
	"FCCTEAPATERNO" VARCHAR2(18 CHAR), 
	"FCCTEAMATERNO" VARCHAR2(18 CHAR), 
	"FCCTEDIRCALLE" VARCHAR2(25 CHAR), 
	"FCCTEDIRNOEXT" VARCHAR2(5 CHAR), 
	"FCCTEDIRNOINT" VARCHAR2(5 CHAR), 
	"FCCTECP" VARCHAR2(5 CHAR), 
	"FCCTECOLONIA" VARCHAR2(40 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_DATA01_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAEST01001_0010" TO "USRINFVENTAST";
