--------------------------------------------------------
--  DDL for Table TAMOVPEDIDOS
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAMOVPEDIDOS" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0), 
	"FINOMOVTO" NUMBER(10,0), 
	"FINOTRANSAC" NUMBER(15,0), 
	"FITIPOOP" NUMBER(10,0), 
	"FDFECMOVTOPED" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FIMOVPCARABO" NUMBER(5,0), 
	"FNMOVPIMP" NUMBER(15,2) DEFAULT 0, 
	"FCUSERID" VARCHAR2(10 CHAR) DEFAULT 0, 
	"FCWS" VARCHAR2(10 CHAR) DEFAULT 0, 
	"FICONCEPMOV" NUMBER(10,0), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAMOVPEDID_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAMOVPEDIDOS" TO "USRINFFENIX";
