--------------------------------------------------------
--  DDL for Table TAPREPARAME
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TAPREPARAME" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FINGCIOID" NUMBER(5,0), 
	"FINOTIENDA" NUMBER(10,0), 
	"FICTEID" NUMBER(15,0), 
	"FIDIGITOVER" NUMBER(5,0), 
	"FITIPOVENTA" NUMBER(5,0), 
	"FCEMPNO" VARCHAR2(10 CHAR), 
	"FIPLAZO" NUMBER(10,0), 
	"FIPERIODO" NUMBER(5,0), 
	"FNPABO" NUMBER(10,2), 
	"FNUABO" NUMBER(10,2), 
	"FDFECPREP" DATE DEFAULT TO_DATE ('01/01/1901', 'dd/mm/yyyy'), 
	"FIAUTORIZA" NUMBER(5,0), 
	"FITRANNO" NUMBER(10,0), 
	"FINOPEDIDO" NUMBER(10,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "PTTAPREPARAME01"  VALUES LESS THAN (1000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP01_DAT" , 
 PARTITION "PTTAPREPARAME02"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP02_DAT" , 
 PARTITION "PTTAPREPARAME03"  VALUES LESS THAN (3000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP03_DAT" , 
 PARTITION "PTTAPREPARAME04"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP04_DAT" , 
 PARTITION "PTTAPREPARAME05"  VALUES LESS THAN (5000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP05_DAT" , 
 PARTITION "PTTAPREPARAME06"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP06_DAT" , 
 PARTITION "PTTAPREPARAME07"  VALUES LESS THAN (7000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP07_DAT" , 
 PARTITION "PTTAPREPARAME08"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP08_DAT" , 
 PARTITION "PTTAPREPARAME09"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TAPREPARAM_RP09_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAME" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TAPREPARAME" TO "USRINFFENIX";
