--------------------------------------------------------
--  DDL for Table TASOLICITUDES
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TASOLICITUDES" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FISOLICITUDID" NUMBER(15,0), 
	"FIIDNEGOCIO" NUMBER(5,0), 
	"FIIDTIENDA" NUMBER(10,0), 
	"FIIDCLIENTE" NUMBER(15,0), 
	"FITIPOSOLICITUD" NUMBER(5,0), 
	"FIFOLIOPARAM" NUMBER(15,0), 
	"FCEMPNO" VARCHAR2(10 CHAR), 
	"FISUBSTAT" NUMBER(5,0), 
	"FISOLCOMPLETA" NUMBER(3,0) DEFAULT 0, 
	"FIINE" NUMBER(3,0) DEFAULT 0, 
	"FICOMPDOMICILIO" NUMBER(3,0) DEFAULT 0, 
	"FICOMPINGRESOS" NUMBER(3,0) DEFAULT 0, 
	"FIFIRMACONTRATO" NUMBER(3,0) DEFAULT 0, 
	"FIVISITAJVC" NUMBER(3,0) DEFAULT 0, 
	"FIAUTORIZADA" NUMBER(3,0) DEFAULT 0, 
	"FILCRSINTAZ" NUMBER(3,0) DEFAULT 0, 
	"FILCRCONTAZ" NUMBER(3,0) DEFAULT 0, 
	"FILIBERADA" NUMBER(3,0) DEFAULT 0, 
	"FNMONTO" NUMBER(15,2) DEFAULT 0, 
	"FCOBSERVACIONES" VARCHAR2(150 CHAR), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TASOLICITU_DAT" ;

   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FICOMPDOMICILIO" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FICOMPINGRESOS" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FIFIRMACONTRATO" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FIVISITAJVC" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FIAUTORIZADA" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FILCRSINTAZ" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FILCRCONTAZ" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FILIBERADA" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FISOLCOMPLETA" IS '0= sin completar , 1= completado , 2= No aplica';
   COMMENT ON COLUMN "SCVENTASTIENDA"."TASOLICITUDES"."FIINE" IS '0= sin completar , 1= completado , 2= No aplica';
  GRANT DELETE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TASOLICITUDES" TO "USRINFFENIX";
