--------------------------------------------------------
--  DDL for Table TATXNERROR_TMP
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TATXNERROR_TMP" 
   (	"FIPAISID" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FITRANNO" NUMBER(10,0), 
	"FITRANTIPO" NUMBER(5,0), 
	"FICONSECTIPO" NUMBER(10,0), 
	"FDTRANSFECHR" DATE, 
	"FCTRANWS" VARCHAR2(15 BYTE), 
	"FCTRANUSR" VARCHAR2(15 BYTE), 
	"FICONSDETA" NUMBER(5,0), 
	"FITIPOREG" NUMBER(5,0), 
	"FCDATODETA" VARCHAR2(4000 BYTE), 
	"FCDESCERROR" VARCHAR2(2000 BYTE), 
	"FDCREACION" DATE, 
	"FDMODIFICO" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE), 
	"FISTATUS" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSAL") 
 (PARTITION "TATXNERROR01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP01_DAT" , 
 PARTITION "TATXNERROR02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP02_DAT" , 
 PARTITION "TATXNERROR03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP03_DAT" , 
 PARTITION "TATXNERROR04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP04_DAT" , 
 PARTITION "TATXNERROR05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_TXNERRORTMP_RP05_DAT" ) ;
  GRANT DELETE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRSENDER";
  GRANT INSERT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRSENDER";
  GRANT SELECT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRSENDER";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRSENDER";
  GRANT DELETE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFFENIX";
  GRANT DELETE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."TATXNERROR_TMP" TO "USRINFSISGES";
