--------------------------------------------------------
--  DDL for Table TCPRODUCTO
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TCPRODUCTO" 
   (	"FNSKU" NUMBER(15,0), 
	"FCDESCSKU" VARCHAR2(200 CHAR), 
	"FNLINEASAP" NUMBER(4,0), 
	"FCDESCLINEASAP" VARCHAR2(200 CHAR), 
	"FNSUBLINEASAP" NUMBER(6,0), 
	"FCDESCSUBLINEASAP" VARCHAR2(200 CHAR), 
	"FNLINEASIE" NUMBER(4,0), 
	"FCDESCLINEASIE" VARCHAR2(200 CHAR), 
	"FNSUBLINEASIE" NUMBER(4,0), 
	"FCDESCSUBLINEASIE" VARCHAR2(200 CHAR), 
	"FNPRECIO" NUMBER(10,2), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CATALOGO_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "SCSISGES";
  GRANT DELETE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSASFNX";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSASFNXPRE";
  GRANT DELETE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSISGES";
  GRANT INSERT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSISGES";
  GRANT SELECT ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCPRODUCTO" TO "USRINFSISGES";
