--------------------------------------------------------
--  DDL for Table TCSUCURSAL
--------------------------------------------------------

  CREATE TABLE "SCVENTASTIENDA"."TCSUCURSAL" 
   (	"FIDSUCURSAL" VARCHAR2(6 BYTE), 
	"FCNOMBRESUCURSAL" VARCHAR2(100 CHAR), 
	"FNIVA" NUMBER(10,2), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCVEN_CATALOGO_DAT" ;
  GRANT DELETE ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFVENTAST";
  GRANT INSERT ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFVENTAST";
  GRANT SELECT ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFVENTAST";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFVENTAST";
  GRANT DELETE ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFFENIX";
  GRANT INSERT ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFFENIX";
  GRANT SELECT ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFFENIX";
  GRANT UPDATE ON "SCVENTASTIENDA"."TCSUCURSAL" TO "USRINFFENIX";
