--------------------------------------------------------
--  DDL for Type OBJGEOALERTA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."OBJGEOALERTA" AS OBJECT
(
   FIPAISID INTEGER,
   FITERRITORIOID INTEGER,
   FIZONAID INTEGER,
   FIREGIONID INTEGER,
   FISUCURSALID INTEGER,
   FIEMPNUM INTEGER
);

/

  GRANT EXECUTE ON "SCSISGES"."OBJGEOALERTA" TO "SCVENTASTIENDA";
  GRANT EXECUTE ON "SCSISGES"."OBJGEOALERTA" TO "USRSISGES";
