--------------------------------------------------------
--  DDL for Type TYOBJGEOGRAFIA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYOBJGEOGRAFIA" IS OBJECT (
    FCIDCANAL  NUMBER,
    FCCANAL  VARCHAR2(50 CHAR),
    FIIDPAIS  NUMBER(3),
    FCPAIS  VARCHAR2(30),
    FIIDCCBISABUELO  NUMBER(10),
    FCNOMBREBISABUELO  VARCHAR2(100),
    FIIDCCABUELO  NUMBER(10),
    FCNOMBREABUELO  VARCHAR2(100),
    FIIDCCPADRE  NUMBER(10),
    FCNOMBREPADRE  VARCHAR2(100),
    FINUMECO  NUMBER(10),
    FCNOMECO  VARCHAR2(100),
    FCSTATUS_DESC  VARCHAR2(15),
    FDFECHAAPACT  DATE,
    FDFECHACIERRE  DATE,
    FCTIPOOP  VARCHAR2(15),
    FIIDENTIDAD  NUMBER(10),
    FCNOMBREENTIDAD	VARCHAR2(100),
    FCCALLE	VARCHAR2(100),
    FCNUMEXT	VARCHAR2(20),
    FCNUMINT	VARCHAR2(20),
    FCCOLONIA	VARCHAR2(100),
    FCMUNICIPIO	VARCHAR2(100),
    FCESTADO	VARCHAR2(30),
    FICP	NUMBER(10),
    FIIVA	NUMBER(5,2)
);

/

  GRANT EXECUTE ON "SCSISGES"."TYOBJGEOGRAFIA" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYOBJGEOGRAFIA" TO "USRINFSISGES";
