--------------------------------------------------------
--  DDL for Type TYOBGETFUNCTE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYOBGETFUNCTE" AS OBJECT
       (FIPAIS NUMBER (5),
        FICANAL NUMBER (5),
        FISUCURSAL NUMBER (10),
        FIFOLIO NUMBER (10),
        FCCAMPO1 VARCHAR2 (250),
        FCCAMPO2 VARCHAR2 (250),
        FCCAMPO3 VARCHAR2 (250),
        FCCAMPO4 VARCHAR2 (250),
        FCCAMPO5 VARCHAR2 (250),
        FCCAMPO6 VARCHAR2 (250),
        FCCAMPO7 VARCHAR2 (250),
        FCCAMPO8 VARCHAR2 (250),
        FCCAMPO9 VARCHAR2 (250),
        FCCAMPO10 VARCHAR2 (250),
        FCCAMPO11 VARCHAR2 (250),
        FCCAMPO12 VARCHAR2 (250),
        FCCAMPO13 VARCHAR2 (250),
        FCCAMPO14 VARCHAR2 (250),
        FICAMPO1 NUMBER (8),
        FICAMPO2 NUMBER (8),
        FICAMPO3 NUMBER (8),
        FICAMPO4 NUMBER (8),
        FICAMPO5 NUMBER (8),
        FICAMPO6 NUMBER (8),
        FICAMPO7 NUMBER (8),
        FICAMPO8 NUMBER (8),
        FICAMPO9 NUMBER (8),
        FICAMPO10 NUMBER (8),
        FICAMPO11 NUMBER (8),
        FICAMPO12 NUMBER (8),
        FICAMPO13 NUMBER (8),
        FICAMPO14 NUMBER (8),
        FDFECHA1 DATE,
        FDFECHA2 DATE,
        FDFECHA3 DATE,
        FDFECHA4 DATE,
        FDFECHA5 DATE,
        FDFECHA6 DATE,
        FDFECHA7 DATE,
        FDFECHA8 DATE);

/

  GRANT EXECUTE ON "SCSISGES"."TYOBGETFUNCTE" TO "USRSISGES";
