--------------------------------------------------------
--  DDL for Type TYOBGESTIONACUM
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYOBGESTIONACUM" AS OBJECT
(
    FIIDENTIFICADOR NUMBER,
    FCDESCRIPCION VARCHAR2 (255),
    FINUMCECO INTEGER,
    FNEMPLEADO NUMBER,
    FNSUCURSAL NUMBER (4, 0),
    FNREGION NUMBER (6, 0),
    FNZONA NUMBER (6, 0),
    FNPAIS NUMBER (3, 0),
    FNPENDIENTESGES INTEGER,
    FNPENDIENTESTOTAL INTEGER,
    FNSOLICITUDESGES INTEGER,
    FNSOLICITUDESTOTAL INTEGER,
    FNPRESUPUESTOSGES INTEGER,
    FNPRESUPUESTOSTOTAL INTEGER,
    FNPROMOCIONESGES INTEGER,
    FNPROMOCIONESTOTAL INTEGER,
    FNCONPEDIDOGES INTEGER,
    FNCONPEDIDOTOTAL INTEGER,
    FNSINPEDIDOGES INTEGER,
    FNSINPEDIDOTOTAL INTEGER,
    FNLLAMADA INTEGER,
    FNCAMBACEO INTEGER,
    FNVISITA INTEGER,
    FNEVENTOS INTEGER,
    FNALERTAS INTEGER
);

/

  GRANT EXECUTE ON "SCSISGES"."TYOBGESTIONACUM" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYOBGESTIONACUM" TO "USRSISGES";
