--------------------------------------------------------
--  DDL for Type TYOBGESTREGION
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYOBGESTREGION" AS OBJECT (
   FNEMPLEADO     NUMBER,
   FIIDSUCURSAL   NUMBER,
   FIPENSURGES    INTEGER,
   FIPENSURTIR    INTEGER,
   FISOLGESTIO    INTEGER,
   FISOLICITUD    INTEGER,
   FIPREGESTIO    INTEGER,
   FIPRESUPUES    INTEGER,
   FIPROGESTIO    INTEGER,
   FIPROMOCION    INTEGER,
   FIREAGESTIO    INTEGER,
   FIREACTIVAC    INTEGER,
   FIGESTIONES    INTEGER
);

/

  GRANT EXECUTE ON "SCSISGES"."TYOBGESTREGION" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYOBGESTREGION" TO "USRSISGES";
