--------------------------------------------------------
--  DDL for Type TYTBGEOGRAFIAEKT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYTBGEOGRAFIAEKT" 
    IS TABLE OF SCSISGES.TYOBJGEOGRAFIAEKT;

/

  GRANT EXECUTE ON "SCSISGES"."TYTBGEOGRAFIAEKT" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYTBGEOGRAFIAEKT" TO "USRSISGES";
