--------------------------------------------------------
--  DDL for Type TYTBPRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYTBPRODUCTO" IS TABLE OF SCSISGES.TYOBPRODUCTO

/

  GRANT EXECUTE ON "SCSISGES"."TYTBPRODUCTO" TO "SCVENTASTIENDA";
  GRANT EXECUTE ON "SCSISGES"."TYTBPRODUCTO" TO "USRSISGES";
