--------------------------------------------------------
--  DDL for Type TYOBGESTIONBRANCH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYOBGESTIONBRANCH" AS OBJECT (
   FNEMPLEADO     NUMBER,
   FCNOMBRECOM    VARCHAR2(255),
   FIPENSURGES    INTEGER,
   FIPENSURTIR    INTEGER,
   FISOLGESTIO    INTEGER,
   FISOLICITUD    INTEGER,
   FIPREGESTIO    INTEGER,
   FIPRESUPUES    INTEGER,
   FIPROGESTIO    INTEGER,
   FIPROMOCION    INTEGER,
   FIREAGESTIO    INTEGER,
   FIREACTIVAC    INTEGER,
   FILLAMADAGE    INTEGER,
   FIVISITAGES    INTEGER,
   FICAMBACEGE    INTEGER,
   FIEVENTODIA    INTEGER,
   FIALERTASSL    INTEGER
);

/

  GRANT EXECUTE ON "SCSISGES"."TYOBGESTIONBRANCH" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYOBGESTIONBRANCH" TO "USRSISGES";
