--------------------------------------------------------
--  DDL for Type TYTBGESTIONBRANCH
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCSISGES"."TYTBGESTIONBRANCH" 
    AS TABLE OF SCSISGES.TYOBGESTIONBRANCH;

/

  GRANT EXECUTE ON "SCSISGES"."TYTBGESTIONBRANCH" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."TYTBGESTIONBRANCH" TO "USRSISGES";
