--------------------------------------------------------
--  DDL for Table TAALERTACLIENTE
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAALERTACLIENTE" 
   (	"FIALERTAID" NUMBER, 
	"FIPAIS" NUMBER(2,0), 
	"FICANAL" NUMBER(2,0), 
	"FISUCURSAL" NUMBER(6,0), 
	"FIFOLIO" NUMBER(10,0), 
	"FNVALOR" NUMBER, 
	"FNSTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(50 BYTE) DEFAULT user, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMOFIDICO" VARCHAR2(50 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA03_DAT" ;
  GRANT SELECT ON "SCSISGES"."TAALERTACLIENTE" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAALERTACLIENTE" TO "USRINFSISGES";
