--------------------------------------------------------
--  DDL for Table TABUZONDETALLE
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TABUZONDETALLE" 
   (	"FIBUZONDETID" NUMBER, 
	"FIBUZONID" NUMBER, 
	"FCEMPNUM" NUMBER(10,0), 
	"FNTIPOREGISTRO" NUMBER(1,0), 
	"FDFECHAREGISTRO" DATE DEFAULT SYSDATE, 
	"FCTEXTOBUZONDET" VARCHAR2(300 BYTE), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMOFIDICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TABUZONDET_DAT" ;
  GRANT DELETE ON "SCSISGES"."TABUZONDETALLE" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TABUZONDETALLE" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TABUZONDETALLE" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TABUZONDETALLE" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TABUZONDETALLE" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TABUZONDETALLE" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TABUZONDETALLE" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TABUZONDETALLE" TO "USRINFSISGES";
