--------------------------------------------------------
--  DDL for Table TACAMPANA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACAMPANA" 
   (	"FNCAMPANA" NUMBER, 
	"FCCAMPANA" VARCHAR2(50 BYTE), 
	"FCDESCCAMPANA" VARCHAR2(500 BYTE), 
	"FCUSRMODIFICO" VARCHAR2(10 BYTE) DEFAULT user, 
	"FDULTIMAMODIFICACION" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO3_DAT" ;
  GRANT DELETE ON "SCSISGES"."TACAMPANA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACAMPANA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACAMPANA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACAMPANA" TO "USRINFFENIX";
