--------------------------------------------------------
--  DDL for Table TACGESOPTRESULT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACGESOPTRESULT" 
   (	"FIGESOPCIONID" NUMBER(38,0), 
	"FIMEDIOGESTIONID" NUMBER(10,0), 
	"FIRESULTGESTIONID" NUMBER(10,0), 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACGESOPTRESULT"."FIGESOPCIONID" IS 'ID DEL CATALOGO TACGESOPTMEDIOS';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTRESULT"."FIMEDIOGESTIONID" IS 'ID DEL CATALOGO TACGESOPTMEDIOS';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTRESULT"."FIRESULTGESTIONID" IS 'ID DEL CATALOGO TCRESULTGESTION';
   COMMENT ON COLUMN "SCSISGES"."TACGESOPTRESULT"."FISTATUS" IS 'BORRADO LOGICO, USAR 0 PARA BORRADO';
  GRANT DELETE ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACGESOPTRESULT" TO "USRINFSISGES";
