--------------------------------------------------------
--  DDL for Table TACGESPERIODOS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TACGESPERIODOS" 
   (	"FIPERIODOID" NUMBER(3,0), 
	"FCDESCRIPCION" VARCHAR2(50 BYTE), 
	"FITIPO" NUMBER(2,0), 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FCDESTIPO" VARCHAR2(50 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TACGESPERIODOS"."FIPERIODOID" IS 'ID DEL PERIODO';
   COMMENT ON COLUMN "SCSISGES"."TACGESPERIODOS"."FCDESCRIPCION" IS 'DESCRIPCION DEL PERIODO';
   COMMENT ON COLUMN "SCSISGES"."TACGESPERIODOS"."FITIPO" IS 'TIPO DE PERIODO. 1: SEMANAS | 2: DIAS';
   COMMENT ON COLUMN "SCSISGES"."TACGESPERIODOS"."FISTATUS" IS 'BORRADO LOGICO, USAR 0 PARA BORRADO';
   COMMENT ON COLUMN "SCSISGES"."TACGESPERIODOS"."FCDESTIPO" IS 'DESCRIPCION DEL ID DE TIPO: SEMANAS | DIAS';
  GRANT DELETE ON "SCSISGES"."TACGESPERIODOS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TACGESPERIODOS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TACGESPERIODOS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TACGESPERIODOS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TACGESPERIODOS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TACGESPERIODOS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TACGESPERIODOS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TACGESPERIODOS" TO "USRINFSISGES";
