--------------------------------------------------------
--  DDL for Table TAEMPLEADO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAEMPLEADO" 
   (	"FNEMPLEADO" NUMBER, 
	"FCNOMBRE" VARCHAR2(255 CHAR), 
	"FCAPATERNO" VARCHAR2(255 CHAR), 
	"FCAMATERNO" VARCHAR2(255 CHAR), 
	"FNFUNCION" NUMBER, 
	"FNEMPLEADOJEFE" NUMBER, 
	"FNCC" NUMBER, 
	"FNFUNCIONJEFE" NUMBER, 
	"FCNEGOCIO" VARCHAR2(3 BYTE), 
	"FNLABORA" NUMBER, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDULTIMAMODIFICACION" DATE DEFAULT SYSDATE, 
	"FDBAJA" DATE, 
	"FDALTA" DATE, 
	"FISITUACION" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAEMPLEADO" TO "SCVENTASTIENDA";
  GRANT INSERT ON "SCSISGES"."TAEMPLEADO" TO "SCVENTASTIENDA";
  GRANT SELECT ON "SCSISGES"."TAEMPLEADO" TO "SCVENTASTIENDA";
  GRANT UPDATE ON "SCSISGES"."TAEMPLEADO" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TAEMPLEADO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAEMPLEADO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAEMPLEADO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAEMPLEADO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAEMPLEADO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAEMPLEADO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAEMPLEADO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAEMPLEADO" TO "USRINFSISGES";
