--------------------------------------------------------
--  DDL for Table TAEMPALERTA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAEMPALERTA" 
   (	"FIALERTAID" NUMBER(10,0), 
	"FIEMPNUM" NUMBER, 
	"FDVISTO" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user, 
	"FDULTMADIFICACION" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAEMPALERTA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAEMPALERTA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAEMPALERTA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAEMPALERTA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAEMPALERTA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAEMPALERTA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAEMPALERTA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAEMPALERTA" TO "USRINFSISGES";
