--------------------------------------------------------
--  DDL for Table TAEVENTO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAEVENTO" 
   (	"FIUSUARIOID" NUMBER(38,0), 
	"FCTITULO" VARCHAR2(160 BYTE), 
	"FCNOTA" VARCHAR2(500 BYTE), 
	"FDHORAINICIO" DATE, 
	"FDHORAFIN" DATE, 
	"FIEVENTO" NUMBER, 
	"FDFECHA" DATE, 
	"FIDURACION" NUMBER, 
	"FCCLIENTE" VARCHAR2(100 BYTE), 
	"FICLIENTE" VARCHAR2(14 BYTE), 
	"FDBITACORA" DATE, 
	"FIIDEVENTO" NUMBER DEFAULT "SCSISGES"."SEQEVENTO".nextval, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user, 
	"FDULTIMAMODIFICACION" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAEVENTO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAEVENTO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAEVENTO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAEVENTO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAEVENTO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAEVENTO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAEVENTO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAEVENTO" TO "USRINFSISGES";
