--------------------------------------------------------
--  DDL for Table TAEVENTGEST
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAEVENTGEST" 
   (	"FIGESTIONID" NUMBER(10,0), 
	"FIUSUARIOID" NUMBER(38,0), 
	"FIEVENTOID" NUMBER, 
	"FICLIENTE" VARCHAR2(14 BYTE), 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user, 
	"FDULTIMAMODIFICACION" DATE DEFAULT sysdate
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAEVENTGEST" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAEVENTGEST" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAEVENTGEST" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAEVENTGEST" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAEVENTGEST" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAEVENTGEST" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAEVENTGEST" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAEVENTGEST" TO "USRINFSISGES";
