--------------------------------------------------------
--  DDL for Table TAFXZONAS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXZONAS" 
   (	"FIIDPAIS" NUMBER(3,0), 
	"FIIDTERRITORIO" NUMBER(10,0), 
	"FIIDZONA" NUMBER(10,0), 
	"FCDESCZONAS" VARCHAR2(100 BYTE), 
	"FIESTATUS" NUMBER(1,0), 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FIIDPAIS" IS 'ID DEL PAIS, DEL CATALOGO TCPAIS';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FIIDTERRITORIO" IS 'ID DEL TERRITORIO, DEL CATALOGO TAFXTERRITORIOS';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FIIDZONA" IS 'ID DE LA ZONA, PROPORCIONADO POR CECO';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FCDESCZONAS" IS 'NOMBRE DE LA ZONA';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FIESTATUS" IS 'BORRADO LOGICO: 1 ACTIVO | 0 INACTIVO';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FDMODIFICACION" IS 'CAMPO DE AUDITORIA: ULTIMA MODIFICACION';
   COMMENT ON COLUMN "SCSISGES"."TAFXZONAS"."FCUSRMODIFICO" IS 'CAMPO DE AUDITORIA: USUARIO QUE MODIFICO';
  GRANT DELETE ON "SCSISGES"."TAFXZONAS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXZONAS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXZONAS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXZONAS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXZONAS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXZONAS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXZONAS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXZONAS" TO "USRINFSISGES";
