--------------------------------------------------------
--  DDL for Table TAFXCAMPANASPF
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXCAMPANASPF" 
   (	"FIIDCAMPANA" NUMBER(8,0), 
	"FCNOMCAMPANA" VARCHAR2(250 BYTE), 
	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FIFOLIO" NUMBER(20,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPANASPF" TO "USRINFSISGES";
