--------------------------------------------------------
--  DDL for Table TAFXREGIONES
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXREGIONES" 
   (	"FIIDPAIS" NUMBER(3,0), 
	"FIIDTERRITORIO" NUMBER(10,0), 
	"FIIDZONA" NUMBER(10,0), 
	"FIIDREGION" NUMBER(10,0), 
	"FCDESCREGION" VARCHAR2(100 BYTE), 
	"FIESTATUS" NUMBER(1,0), 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FIIDPAIS" IS 'ID DEL PAIS, DEL CATALOGO TCPAIS';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FIIDTERRITORIO" IS 'ID DEL CATALOGO TAFXTERRITORIOS';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FIIDZONA" IS 'ID DEL CATALOGO TAFXZONAS';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FIIDREGION" IS 'ID DE LA REGION PROPORCIONADO POR CECO';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FCDESCREGION" IS 'NOMBRE DE LA REGION';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FIESTATUS" IS 'BORRADO LOGICO: 1 ACTIVO | 0 INACTIVO';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FDMODIFICACION" IS 'CAMPO DE AUDITORIA: ULTIMA MODIFICACION';
   COMMENT ON COLUMN "SCSISGES"."TAFXREGIONES"."FCUSRMODIFICO" IS 'CAMPO DE AUDITORIA: USUARIO QUE MODIFICO';
  GRANT DELETE ON "SCSISGES"."TAFXREGIONES" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXREGIONES" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXREGIONES" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXREGIONES" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXREGIONES" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXREGIONES" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXREGIONES" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXREGIONES" TO "USRINFSISGES";
