--------------------------------------------------------
--  DDL for Table TAFXCAMPREPPF
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXCAMPREPPF" 
   (	"FITIEMPO" NUMBER(10,0), 
	"FIIDCAMPANA" NUMBER(8,0), 
	"FIPAISCU" NUMBER(5,0), 
	"FICANALCU" NUMBER(5,0), 
	"FISUCURSALCU" NUMBER(10,0), 
	"FIFOLIOCU" NUMBER(10,0), 
	"FISUCGEST" NUMBER(10,0), 
	"FIPLAZO" NUMBER(10,0), 
	"FIIDPORTAFOLIO" NUMBER(8,0), 
	"FIIDEMPLEADO" NUMBER(10,0), 
	"FITIPOGESTIONID" NUMBER(10,0), 
	"FIANIO" NUMBER(5,0), 
	"FISEMANA" NUMBER(3,0), 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP01_DAT" 
  PARTITION BY RANGE ("FISUCGEST") 
 (PARTITION "TAFXCAMREPPF_01"  VALUES LESS THAN (1000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP01_DAT" , 
 PARTITION "TAFXCAMREPPF_02"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP02_DAT" , 
 PARTITION "TAFXCAMREPPF_03"  VALUES LESS THAN (3000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP03_DAT" , 
 PARTITION "TAFXCAMREPPF_04"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP04_DAT" , 
 PARTITION "TAFXCAMREPPF_05"  VALUES LESS THAN (5000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP05_DAT" , 
 PARTITION "TAFXCAMREPPF_06"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP06_DAT" , 
 PARTITION "TAFXCAMREPPF_07"  VALUES LESS THAN (7000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP07_DAT" , 
 PARTITION "TAFXCAMREPPF_08"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP08_DAT" , 
 PARTITION "TAFXCAMREPPF_09"  VALUES LESS THAN (9000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP09_DAT" , 
 PARTITION "TAFXCAMREPPF_10"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPRE_RP10_DAT" ) ;

   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIIDCAMPANA" IS 'ID DE LA CAMPA�A';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIPAISCU" IS 'Pa�s del cliente �nico';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FICANALCU" IS 'Canal del cliente �nico';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FISUCURSALCU" IS 'Sucursal del cliente �nico';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIFOLIOCU" IS 'Folio del cliente �nico';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIPLAZO" IS 'Puesto del empleado (vendedor,asesor,ejecutivo)';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIIDPORTAFOLIO" IS 'Portafolio al que se asigna al CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIIDEMPLEADO" IS 'ID del empleado';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FITIPOGESTIONID" IS 'ID del catalogo de modulo correspondiente de la tabla TCTIPOGESTION';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FIANIO" IS 'A�o';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPREPPF"."FISEMANA" IS 'Semana (Tomar en cuenta que esta debe estar en semana Mi�rcoles-Martes)';
  GRANT DELETE ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPREPPF" TO "USRINFSISGES";
