--------------------------------------------------------
--  DDL for Table TAFXCAMPANASMKT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAFXCAMPANASMKT" 
   (	"FIIDCAMPANA" NUMBER(5,0), 
	"FIPAISCU" NUMBER(5,0), 
	"FICANALCU" NUMBER(8,0), 
	"FISUCURSALCU" NUMBER(10,0), 
	"FIFOLIOCU" NUMBER(10,0), 
	"FCUSUARIO_MODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDFECHA_MODIFICA" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS 
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP01_DAT" 
  PARTITION BY RANGE ("FISUCURSALCU") 
 (PARTITION "CAMPANASMKT_01"  VALUES LESS THAN (2000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP01_DAT" , 
 PARTITION "CAMPANASMKT_02"  VALUES LESS THAN (4000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP02_DAT" , 
 PARTITION "CAMPANASMKT_03"  VALUES LESS THAN (6000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP03_DAT" , 
 PARTITION "CAMPANASMKT_04"  VALUES LESS THAN (8000) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP04_DAT" , 
 PARTITION "CAMPANASMKT_05"  VALUES LESS THAN (MAXVALUE) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING 
  STORAGE( INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TAFXCAMPAN_RP05_DAT" ) ;

   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FIIDCAMPANA" IS 'CAMPA�A A LA QUE PERTENECE EL CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FIPAISCU" IS 'PAIS DEL CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FICANALCU" IS 'CANAL DEL CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FISUCURSALCU" IS 'SUCURSAL DEL CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FIFOLIOCU" IS 'FOLIO DEL CU';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FCUSUARIO_MODIFICO" IS 'USUARIO QUE REALIZA LA MODIFICACION DE AUDITORIA';
   COMMENT ON COLUMN "SCSISGES"."TAFXCAMPANASMKT"."FDFECHA_MODIFICA" IS 'FECHA DE ACTUALIZACION DE AUDITORIA';
  GRANT DELETE ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAFXCAMPANASMKT" TO "USRINFSISGES";
