--------------------------------------------------------
--  DDL for Table TAGEOGRAFBAZEKT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAGEOGRAFBAZEKT" 
   (	"FCIDCANAL" VARCHAR2(3 BYTE), 
	"FCCANAL" VARCHAR2(30 BYTE), 
	"FIIDPAIS" NUMBER(5,0), 
	"FCPAIS" VARCHAR2(30 BYTE), 
	"FIIDCCBISABUELO" NUMBER(15,0), 
	"FITIPOBISABUELO" NUMBER(15,0), 
	"FCNOMBREBISABUELO" VARCHAR2(100 BYTE), 
	"FIRESPONSBISA" NUMBER(15,0), 
	"FCNOMRESPONSBISA" VARCHAR2(150 BYTE), 
	"FIIDCCABUELO" NUMBER(15,0), 
	"FITIPOABUELO" NUMBER(15,0), 
	"FCNOMBREABUELO" VARCHAR2(100 BYTE), 
	"FIRESPONSABUE" NUMBER(15,0), 
	"FCNOMRESPONSABUE" VARCHAR2(150 BYTE), 
	"FIIDCCPADRE" NUMBER(10,0), 
	"FITIPOPADRE" NUMBER(15,0), 
	"FCNOMBREPADRE" VARCHAR2(100 BYTE), 
	"FIRESPONSPAD" NUMBER(15,0), 
	"FCNOMRESPONSPAD" VARCHAR2(150 BYTE), 
	"FINUMECO" NUMBER(15,0), 
	"FIIDCC" NUMBER(15,0), 
	"FCNOMECO" VARCHAR2(100 BYTE), 
	"FIRESPONSCC" NUMBER(15,0), 
	"FCNOMRESPONSCC" VARCHAR2(150 BYTE), 
	"FCSTATUS_DESC" VARCHAR2(15 BYTE), 
	"FDFECHAAPACT" DATE, 
	"FDFECHACIERRE" DATE, 
	"FCTIPOOP" VARCHAR2(15 BYTE), 
	"FIIDENTIDAD" NUMBER(38,0), 
	"FCNOMBREENTIDAD" VARCHAR2(100 BYTE), 
	"FCCALLE" VARCHAR2(100 BYTE), 
	"FCNUMEXT" VARCHAR2(20 BYTE), 
	"FCNUMINT" VARCHAR2(20 BYTE), 
	"FCCOLONIA" VARCHAR2(100 BYTE), 
	"FCMUNICIPIO" VARCHAR2(100 BYTE), 
	"FCESTADO" VARCHAR2(30 BYTE), 
	"FICP" NUMBER(15,0), 
	"FIIVA" NUMBER(5,2), 
	"ULTIMA_MODIFICACION" DATE, 
	"USUARIO_MODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TEMPORAL_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAGEOGRAFBAZEKT" TO "USRINFSISGES";
