--------------------------------------------------------
--  DDL for Table TAGEOALERTAH_TMP
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAGEOALERTAH_TMP" 
   (	"FIGEOALERTAID" NUMBER(38,0), 
	"FIALERTAID" NUMBER(38,0), 
	"FIPAISID" NUMBER(38,0), 
	"FITERRITORIOID" NUMBER(38,0), 
	"FIZONAID" NUMBER(38,0), 
	"FIREGIONID" NUMBER(38,0), 
	"FISUCURSALID" NUMBER(38,0), 
	"FIEMPNUM" NUMBER(38,0), 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user, 
	"FDULTIMAMODIFICACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAGEOALERTAH_TMP" TO "USRINFSISGES";
