--------------------------------------------------------
--  DDL for Table TALOGCOLERR
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TALOGCOLERR" 
   (	"FICOLERRID" NUMBER(*,0), 
	"FCPROCESO" VARCHAR2(100 BYTE), 
	"FCSUBPROCESO" VARCHAR2(100 BYTE), 
	"FICODIGO" NUMBER(*,0), 
	"FCMENSAJE" VARCHAR2(500 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FISTATUS" NUMBER(*,0) DEFAULT 1, 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSUARIO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TALOGCOLERR" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TALOGCOLERR" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TALOGCOLERR" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TALOGCOLERR" TO "USRINFFENIX";
