--------------------------------------------------------
--  DDL for Table TAPARAMETROS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAPARAMETROS" 
   (	"FIIDPARAMETRO" NUMBER DEFAULT "SCSISGES"."SEQPARAMETRO".NEXTVAL, 
	"FCDESCRIPCION" VARCHAR2(255 BYTE), 
	"FCVALOR" VARCHAR2(4000 BYTE), 
	"FIACTIVO" NUMBER(2,0), 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA01_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "SCACTUALIZADORVT";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "SCACTUALIZADORVT";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "SCACTUALIZADORVT";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "SCACTUALIZADORVT";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "SCVENTASTIENDA";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "SCVENTASTIENDA";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "SCVENTASTIENDA";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "SCVENTASTIENDA";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRACTVT";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRACTVT";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRACTVT";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRACTVT";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRINFACTVT";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRINFACTVT";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRINFACTVT";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRINFACTVT";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRINFSISGES";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRSISGES";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRSISGES";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRSISGES";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRSISGES";
  GRANT DELETE ON "SCSISGES"."TAPARAMETROS" TO "USRVENTAST";
  GRANT INSERT ON "SCSISGES"."TAPARAMETROS" TO "USRVENTAST";
  GRANT SELECT ON "SCSISGES"."TAPARAMETROS" TO "USRVENTAST";
  GRANT UPDATE ON "SCSISGES"."TAPARAMETROS" TO "USRVENTAST";
