--------------------------------------------------------
--  DDL for Table TAPROMOHIST
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAPROMOHIST" 
   (	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(10,0), 
	"FIFOLIO" NUMBER(15,0), 
	"FCDESCPROD" VARCHAR2(100 CHAR), 
	"FIPRIORIDAD" NUMBER(5,0), 
	"FIESTATUSINTERES" NUMBER(5,0) DEFAULT 0, 
	"FCEMPNO" VARCHAR2(10 CHAR), 
	"FDFECHAMOD" DATE, 
	"FIIDSUBLINEA" NUMBER(10,0), 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(35 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;
  GRANT DELETE ON "SCSISGES"."TAPROMOHIST" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAPROMOHIST" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAPROMOHIST" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAPROMOHIST" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAPROMOHIST" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAPROMOHIST" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAPROMOHIST" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAPROMOHIST" TO "USRINFSISGES";
