--------------------------------------------------------
--  DDL for Table TAURL
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TAURL" 
   (	"OPCION" NUMBER(5,0), 
	"URLS" VARCHAR2(100 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TAURL"."OPCION" IS 'EL EL BOTON DE OPCIONES';
   COMMENT ON COLUMN "SCSISGES"."TAURL"."URLS" IS 'ES LA URL ACTUAL';
  GRANT DELETE ON "SCSISGES"."TAURL" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TAURL" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TAURL" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TAURL" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TAURL" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TAURL" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TAURL" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TAURL" TO "USRINFSISGES";
