--------------------------------------------------------
--  DDL for Table TCCATCAMBACEO
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCCATCAMBACEO" 
   (	"FICAMBACEOID" NUMBER(38,0), 
	"FCNOMBREARCHIVO" VARCHAR2(256 BYTE), 
	"FCDESCARCHIVO" VARCHAR2(256 BYTE), 
	"FCLOBIARCHIVO" CLOB, 
	"FISTATUS" NUMBER(38,0), 
	"FDCREACION" DATE, 
	"FDMODIFICACION" DATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE), 
	"FCMIMETYPE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TCCATCAMBA_DAT" 
 LOB ("FCLOBIARCHIVO") STORE AS SECUREFILE (
  TABLESPACE "SCSIS_TCCATCAMBA_DAT" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  GRANT DELETE ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCCATCAMBACEO" TO "USRINFSISGES";
