--------------------------------------------------------
--  DDL for Table TCCAMPANAMKT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCCAMPANAMKT" 
   (	"FIIDCAMPANA" NUMBER(8,0), 
	"FCCAMPANA" VARCHAR2(50 BYTE), 
	"FCDESCCAMPANA" VARCHAR2(500 BYTE), 
	"FIIDTIPO" NUMBER(1,0), 
	"FIIDNEGOCIO" NUMBER(1,0), 
	"FIIDPAIS" NUMBER(1,0), 
	"FCUSRMODIFICO" VARCHAR2(10 BYTE) DEFAULT USER, 
	"FDMODIFICACION" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCCAMPANAMKT" TO "USRINFSISGES";
