--------------------------------------------------------
--  DDL for Table TCCALENDARIOEKT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCCALENDARIOEKT" 
   (	"FIANIO" NUMBER(5,0), 
	"FISEMANA" NUMBER(2,0), 
	"FDFECHA" DATE, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCCALENDARIOEKT" TO "USRINFSISGES";
