--------------------------------------------------------
--  DDL for Table TCCONTROLJOBS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCCONTROLJOBS" 
   (	"FIANIO" NUMBER(4,0), 
	"FIMES" NUMBER(2,0), 
	"FIDIA" NUMBER(2,0), 
	"FCHORAINI" VARCHAR2(15 BYTE), 
	"FCHORAFIN" VARCHAR2(15 BYTE), 
	"FCNOMBREPROCESO" VARCHAR2(50 BYTE), 
	"FDFECHA" DATE DEFAULT SYSDATE, 
	"FCDESCERROR" VARCHAR2(250 BYTE), 
	"FISTATUSEJEC" NUMBER(1,0), 
	"FCUSRMODIFICO" VARCHAR2(100 BYTE), 
	"FDMODIFICACION" DATE, 
	"FIIDPROC" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_DATA02_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TCCONTROLJOBS"."FIIDPROC" IS 'ID DE PROCESO NECESARIO PARA TENER MAYOR CONTROL DESDE TIBCO';
  GRANT DELETE ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCCONTROLJOBS" TO "USRINFSISGES";
