--------------------------------------------------------
--  DDL for Table TCESTATUSCATBUZ
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCESTATUSCATBUZ" 
   (	"FIESTBUZONID" NUMBER(2,0), 
	"FICATBUZONID" NUMBER(2,0), 
	"FNINDICADORAUT" NUMBER(1,0), 
	"FNINACTIVO" NUMBER(1,0) DEFAULT 0, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FCUSRCREACION" VARCHAR2(30 BYTE) DEFAULT USER, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCESTATUSCATBUZ" TO "USRINFSISGES";
