--------------------------------------------------------
--  DDL for Table TCLINEA
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCLINEA" 
   (	"FNLINEA" NUMBER, 
	"FCPRDLINDESC" VARCHAR2(50 BYTE), 
	"FNLINEAPROD" NUMBER, 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FDMODIFICO" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT user, 
	"FNESTATUS" NUMBER(1,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO2_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCLINEA" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCLINEA" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCLINEA" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCLINEA" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCLINEA" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCLINEA" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCLINEA" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCLINEA" TO "USRINFSISGES";
