--------------------------------------------------------
--  DDL for Table TCPAIS
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCPAIS" 
   (	"FIIDPAIS" NUMBER(3,0), 
	"FINUMPAIS" NUMBER(3,0), 
	"FCNOMPAIS" VARCHAR2(50 BYTE), 
	"FDFECACTUAL" DATE, 
	"FCPAIS" VARCHAR2(50 BYTE), 
	"FIESTATUS" NUMBER(1,0), 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TCPAIS"."FIIDPAIS" IS 'ID DEL PAIS, SE USA EL QUE PROPONCIONA CECO';
   COMMENT ON COLUMN "SCSISGES"."TCPAIS"."FCPAIS" IS 'NOMBRE DEL PAIS';
   COMMENT ON COLUMN "SCSISGES"."TCPAIS"."FIESTATUS" IS 'BORRADO LOGICO: 1 ACTIVO | 0 INACTIVO';
   COMMENT ON COLUMN "SCSISGES"."TCPAIS"."FDMODIFICACION" IS 'CAMPO DE AUDITORIA: ULTIMA MODIFICACION';
   COMMENT ON COLUMN "SCSISGES"."TCPAIS"."FCUSRMODIFICO" IS 'CAMPO DE AUDITORIA: USUARIO QUE MODIFICO';
  GRANT DELETE ON "SCSISGES"."TCPAIS" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCPAIS" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCPAIS" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCPAIS" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCPAIS" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCPAIS" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCPAIS" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCPAIS" TO "USRINFSISGES";
