--------------------------------------------------------
--  DDL for Table TCRESULTGESTION
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCRESULTGESTION" 
   (	"FIRESULTGESTIONID" NUMBER(10,0), 
	"FCRESULTGESTIONDESC" VARCHAR2(50 BYTE), 
	"FDCREACION" DATE, 
	"FISTATUS" NUMBER(1,0), 
	"FDMODIFICACION" DATE, 
	"USRMODIFICO" VARCHAR2(30 BYTE), 
	"FNDIASENFRIAMIENTO" NUMBER(3,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO3_DAT" ;

   COMMENT ON COLUMN "SCSISGES"."TCRESULTGESTION"."FNDIASENFRIAMIENTO" IS 'DIAS DE ENFRIAMIENTO PARA GESTIONES';
  GRANT DELETE ON "SCSISGES"."TCRESULTGESTION" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCRESULTGESTION" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCRESULTGESTION" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCRESULTGESTION" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCRESULTGESTION" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCRESULTGESTION" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCRESULTGESTION" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCRESULTGESTION" TO "USRINFSISGES";
  GRANT DELETE ON "SCSISGES"."TCRESULTGESTION" TO "USRSISGES";
  GRANT INSERT ON "SCSISGES"."TCRESULTGESTION" TO "USRSISGES";
  GRANT SELECT ON "SCSISGES"."TCRESULTGESTION" TO "USRSISGES";
  GRANT UPDATE ON "SCSISGES"."TCRESULTGESTION" TO "USRSISGES";
