--------------------------------------------------------
--  DDL for Table TCSCRIPT
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TCSCRIPT" 
   (	"FISCRIPTID" NUMBER(10,0), 
	"FCCONTENIDO" VARCHAR2(900 BYTE), 
	"FDCREACION" DATE DEFAULT SYSDATE, 
	"FISTATUS" NUMBER(1,0) DEFAULT 1, 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_CATALOGO3_DAT" ;
  GRANT DELETE ON "SCSISGES"."TCSCRIPT" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TCSCRIPT" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TCSCRIPT" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TCSCRIPT" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TCSCRIPT" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TCSCRIPT" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TCSCRIPT" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TCSCRIPT" TO "USRINFSISGES";
