--------------------------------------------------------
--  DDL for Table TTCAMPANACTE
--------------------------------------------------------

  CREATE TABLE "SCSISGES"."TTCAMPANACTE" 
   (	"FIIDCAMPANA" NUMBER(8,0), 
	"FIPAIS" NUMBER(5,0), 
	"FICANAL" NUMBER(5,0), 
	"FISUCURSAL" NUMBER(5,0), 
	"FIFOLIO" NUMBER(20,0), 
	"FIIDEMPLEADO" NUMBER(10,0), 
	"FNSTATUSCTE" NUMBER(1,0), 
	"FIIDPAIS" NUMBER(1,0), 
	"FIIDTERRITORIO" NUMBER(6,0), 
	"FIIDZONA" NUMBER(6,0), 
	"FIIDREGION" NUMBER(6,0), 
	"FIIDSUCURSAL" NUMBER(5,0), 
	"FDMODIFICACION" DATE DEFAULT SYSDATE, 
	"FCUSRMODIFICO" VARCHAR2(30 BYTE) DEFAULT USER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 0 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SCSIS_TEMPORAL_DAT" ;
  GRANT DELETE ON "SCSISGES"."TTCAMPANACTE" TO "USRINFFENIX";
  GRANT INSERT ON "SCSISGES"."TTCAMPANACTE" TO "USRINFFENIX";
  GRANT SELECT ON "SCSISGES"."TTCAMPANACTE" TO "USRINFFENIX";
  GRANT UPDATE ON "SCSISGES"."TTCAMPANACTE" TO "USRINFFENIX";
  GRANT DELETE ON "SCSISGES"."TTCAMPANACTE" TO "USRINFSISGES";
  GRANT INSERT ON "SCSISGES"."TTCAMPANACTE" TO "USRINFSISGES";
  GRANT SELECT ON "SCSISGES"."TTCAMPANACTE" TO "USRINFSISGES";
  GRANT UPDATE ON "SCSISGES"."TTCAMPANACTE" TO "USRINFSISGES";
