--------------------------------------------------------
--  DDL for Type TYCABTXNGEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYCABTXNGEN" AS OBJECT
                  (FIPAISID NUMBER,
                   FICANALID NUMBER,
                   FISUCURSALID NUMBER,
                   FITRANNO NUMBER,
                   FITRANTIPO NUMBER,
                   FICONSECTIPO NUMBER,
                   FDTRANSFECHR DATE,
                   FCTRANWS VARCHAR2 (50),
                   FCTRANUSR VARCHAR2 (50),
                   FICONSDETA NUMBER,
                   FITIPOREG NUMBER,
                   FCDATODETA VARCHAR2 (4000));

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABTXNGEN" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABTXNGEN" TO "SCACTUALIZADORVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABTXNGEN" TO "USRACTVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABTXNGEN" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABTXNGEN" TO "USRINFSISGES";
