--------------------------------------------------------
--  DDL for Type TYHIJOREG_220
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYHIJOREG_220" UNDER TYTRANSACCION(
FINOPEDIDO  NUMBER(10),
FIPEDSTAT  NUMBER(3),
FNPEDSALDO  NUMBER(13,2),
FNIMPPAGADO_  NUMBER(9,2),
FNIMPDEVENG_  NUMBER(9,2),
FNPEDIMPMORA  NUMBER(9,2),
FINOATRASOS  NUMBER(3),
FCSTATCARTERA  VARCHAR2(6 CHAR),
FICLASIFCUENTA  NUMBER(3),
FIPERIODOACT  NUMBER(5),
FDFECULTPAGO  DATE,
FNDIASDESDESURT  NUMBER(5),
FNPEDSALDOANTE  NUMBER(13,2),
SEMVEN_  NUMBER(5),
INACTSEMANAS_  NUMBER(5),
ATRASOSEMANAS_  NUMBER(5),
IMPATRA_  NUMBER(10,2),
FNMOVPIMP  NUMBER(13,2),
FNGESTIONCCOB  NUMBER(3),
FNGESTIONSCOB  NUMBER(3),
FDFECGEST  DATE,
FIVISITAID  NUMBER(3),
FITIPOVENTA  NUMBER(3),
PAGANDO  VARCHAR2(8 CHAR),
BONIFICAREMOS  VARCHAR2(8 CHAR),
FNULTIMPMORA  NUMBER(9,2),
FNMOVPIMPMOR  NUMBER(13,2),
FINOPERIODOCORR_  NUMBER(5),
FIPERINAC_  NUMBER(3),
SEMATRA_  NUMBER(4),
FNIMPPAGADO  NUMBER(13,2),
FNIMPDEVENG  NUMBER(13,2),
FDCREACION  DATE,
FDMODIFICO  DATE,
FCUSRMODIFICO  VARCHAR2(30),
  CONSTRUCTOR FUNCTION TYHIJOREG_220(SELF IN OUT NOCOPY TYHIJOREG_220, pa_registerData XMLTYPE)
                               RETURN SELF AS RESULT,
  OVERRIDING MEMBER FUNCTION FNPROCESAREGISTRO(PACABECERO IN scventastienda.TYCABECEROTXN) RETURN INTEGER
)NOT FINAL INSTANTIABLE  ;
/
CREATE OR REPLACE EDITIONABLE TYPE BODY "SCVENTASTIENDA"."TYHIJOREG_220" AS
/*************************************************************************************************
Proyecto: Sistema de Gestion
Descripcion: SUBTYPES PARA PROCESAMIENTO DE TRANSACCIONES DEL SENDER,TIPO DE REGISTRO 220
Creador: Cesar David Campos Garcia
Fecha de creacion: 20/05/2019
**************************************************************************************************/
CONSTRUCTOR FUNCTION TYHIJOREG_220(SELF IN OUT NOCOPY TYHIJOREG_220, pa_registerData XMLTYPE)
                               RETURN SELF AS RESULT AS


BEGIN
  pa_registerData.TOOBJECT(SELF);
    RETURN;

END;

OVERRIDING MEMBER FUNCTION FNPROCESAREGISTRO(PACABECERO IN scventastienda.TYCABECEROTXN)
RETURN INTEGER AS

VL_ERROR VARCHAR2(100);
CSL_0 CONSTANT PLS_INTEGER :=0;
CSL_1 CONSTANT PLS_INTEGER :=1;
CSL_2 CONSTANT PLS_INTEGER :=2;
CSL_200 CONSTANT PLS_INTEGER :=200;
VL_ORACOD NUMBER;
VL_ORADESC VARCHAR2(2000);

--INICIO DE LA FUNCION
BEGIN
  BEGIN

   VL_ERROR := 'ERROR AL ACTUALIZAR EN PEDIDOS_CREDITO';
   MERGE INTO SCVENTASTIENDA.PEDIDOS_CREDITO PC
       USING (SELECT PACABECERO.FIPAISID AS PAIS,
                     PACABECERO.FICANALID AS CANAL,
                     PACABECERO.FISUCURSALID AS  SUC,
                     SELF.FINOPEDIDO AS PEDIDO
                FROM DUAL) VALORES
                  ON (PC.FIPAISID = VALORES.PAIS
                 AND  PC.FICANAL = VALORES.CANAL
                 AND  PC.FISUCURSAL = VALORES.SUC
                 AND  PC.FINOPEDIDO = VALORES.PEDIDO)
        WHEN MATCHED THEN
             UPDATE
                SET  FNSALDO = SELF.FNPEDSALDO,
                     FIPEDSTATUS = SELF.FIPEDSTAT,
                     FNIMPPAGADO = SELF.FNIMPPAGADO_,
                     FNIMPDEVENG = SELF.FNIMPDEVENG_,
                     FNULTIMPMORA = SELF.FNULTIMPMORA,
                     FCSTATCARTERA = SELF.FCSTATCARTERA,
                     FIPERACTUAL = SELF.FIPERIODOACT,
                     FIPERCORRIDO = SELF.FINOPERIODOCORR_,
                     FNSDOANTMORA = SELF.FNULTIMPMORA,
                     FDULTIMOABONO = SELF.FDFECULTPAGO,
                     FDULTPAGO = SELF.FDFECULTPAGO,
                     FNMORATORIOS = SELF.FNPEDIMPMORA,
                     FNSALDOATRASADO=SELF.IMPATRA_,
                     FIPERVENCIDOS = SELF.SEMVEN_,
                     FIPERINACTIVIDAD= SELF.INACTSEMANAS_,
                     FIPERATRASO= SELF.ATRASOSEMANAS_;

   VL_ERROR := 'ERROR AL INSERTAR EN TAPEDIDOS';
   MERGE INTO SCVENTASTIENDA.TAPEDIDOS DATOS
       USING (SELECT PACABECERO.FIPAISID AS PAIS,
                     PACABECERO.FICANALID AS CANAL,
                     PACABECERO.FISUCURSALID AS  SUC,
                     SELF.FINOPEDIDO AS PEDIDO
                FROM DUAL) VALORES
                  ON (DATOS.FIPAIS = VALORES.PAIS
                 AND  DATOS.FICANAL = VALORES.CANAL
                 AND  DATOS.FISUCURSAL = VALORES.SUC
                 AND  DATOS.FINOPEDIDO = VALORES.PEDIDO)
        WHEN MATCHED THEN
             UPDATE
                SET  FNPEDSALDO = SELF.FNPEDSALDO,
                     FIPEDSTAT = SELF.FIPEDSTAT;

   IF(SELF.FITIPOVENTA = CSL_2) THEN

      VL_ERROR  := 'ERROR AL INSERTAR EN TACREDITO';
      MERGE INTO SCVENTASTIENDA.TACREDITO CRED
          USING (SELECT PACABECERO.FIPAISID AS PAIS,
                        PACABECERO.FICANALID AS CANAL,
                        PACABECERO.FISUCURSALID AS  SUC,
                        SELF.FINOPEDIDO PEDIDO
                   FROM DUAL) TMP
                     ON (CRED.FIPAIS = TMP.PAIS
                    AND  CRED.FICANAL = TMP.CANAL
                    AND  CRED.FISUCURSAL = TMP.SUC
                    AND  CRED.FINOPEDIDO = TMP.PEDIDO)
           WHEN MATCHED THEN
                 UPDATE
                    SET FICLASIFCUENTA = SELF.FICLASIFCUENTA,
                        FDFECULTPAGO = SELF.FDFECULTPAGO,
                        FNPEDIMPMORA = SELF.FNPEDIMPMORA,
                        FINOATRASOS = SELF.FINOATRASOS,
                        FIPERIODOACT = SELF.FIPERIODOACT,
                        FINOPERIODOCORR = SELF.FINOPERIODOCORR_,
                        FNIMPPAGADO = SELF.FNIMPPAGADO,
                        FNIMPDEVENG = SELF.FNIMPDEVENG;
   END IF;
 EXCEPTION
       WHEN OTHERS THEN
         ROLLBACK;
         VL_ORACOD :=SQLCODE;
         VL_ORADESC :=  SUBSTR(SQLERRM, CSL_0,CSL_200);
       --LLAMAR AL SP PARA GUARDAR TXN EN ERROR
         SCVENTASTIENDA.SPTRANSACERROR(PACABECERO.FIPAISID,
                                       PACABECERO.FICANALID,
                                       PACABECERO.FISUCURSALID,
                                       PACABECERO.FITRANNO,
                                       PACABECERO.FITRANTIPO,
                                       PACABECERO.FICONSECTIPO,
                                       PACABECERO.FDTRANSFECHR,
                                       PACABECERO.FCTRANWS,
                                       PACABECERO.FCTRANUSR,
                                       FOBJDETALLE.ficonsdeta,
                                       FOBJDETALLE.fitiporeg,
                                       FOBJDETALLE.fcdatodeta,
                                       VL_ERROR||' -> '||VL_ORACOD||'-'||VL_ORADESC||'-> TYHIJOREG_220',
                                       CSL_1,
                                       VL_ORACOD,
                                       VL_ORADESC);
                                       END;

RETURN 0;
END;
END;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYHIJOREG_220" TO "SCACTUALIZADORVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYHIJOREG_220" TO "USRACTVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYHIJOREG_220" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYHIJOREG_220" TO "USRINFSISGES";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYHIJOREG_220" TO "USRVENTAST";
