--------------------------------------------------------
--  DDL for Type TYOBPRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYOBPRODUCTO" AS OBJECT(
        FISKU INTEGER
       ,FNCANTIDAD NUMBER(3)
       ,FCDESPRODUCTO VARCHAR2(100)
       ,FCDESLINEA VARCHAR2(100)
       ,FILINEAID INTEGER
       ,FNPRECIO  NUMBER(15,2)
)   ;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPRODUCTO" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPRODUCTO" TO "USRINFFENIX";
