--------------------------------------------------------
--  DDL for Type TYTBPEDPENDIENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYTBPEDPENDIENT" IS TABLE OF SCVENTASTIENDA.TYOBPEDPENDIENT;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPEDPENDIENT" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPEDPENDIENT" TO "USRVENTAST";
