--------------------------------------------------------
--  DDL for Type TYTBPRESUPUESTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYTBPRESUPUESTO" IS TABLE OF SCVENTASTIENDA.TYOBPRESUPUESTO

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPRESUPUESTO" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPRESUPUESTO" TO "USRVENTAST";
