--------------------------------------------------------
--  DDL for Type TYCABECEROTXN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYCABECEROTXN" AS OBJECT
                  (FIPAISID NUMBER,
                   FICANALID NUMBER,
                   FISUCURSALID NUMBER,
                   FITRANNO NUMBER,
                   FITRANTIPO NUMBER,
                   FICONSECTIPO NUMBER,
                   FDTRANSFECHR DATE,
                   FCTRANWS VARCHAR2 (50),
                   FCTRANUSR VARCHAR2 (50));

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABECEROTXN" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABECEROTXN" TO "SCACTUALIZADORVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABECEROTXN" TO "USRACTVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABECEROTXN" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYCABECEROTXN" TO "USRINFSISGES";
