--------------------------------------------------------
--  DDL for Type TYOBPRESUPUESTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYOBPRESUPUESTO" AS OBJECT(
        FIPRESUPUESTOID INTEGER
       ,FNMONTO NUMBER(15,2)
       ,FDFECHA DATE
       ,FIPLAZO INTEGER
       ,FCDESPERIODO VARCHAR2(100)
       ,FNABONO NUMBER(15,2)
       ,FTYPRODUCTOS SCVENTASTIENDA.TYTBPRODUCTO
);

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPRESUPUESTO" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPRESUPUESTO" TO "USRVENTAST";
