--------------------------------------------------------
--  DDL for Type TYOBPEDPENDIENT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYOBPEDPENDIENT" AS OBJECT(
        FIPEDIDOID INTEGER
       ,FIMONTO NUMBER(15,2)
       ,FDFECHA DATE
       , FIPLAZO NUMBER(5) 
       , FCPERIODO VARCHAR2(70) 
       ,FIABONO NUMBER(15,2)
       ,FTYPRODUCTOS SCVENTASTIENDA.TYTBPRODUCTO 
);

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPEDPENDIENT" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYOBPEDPENDIENT" TO "USRVENTAST";
