--------------------------------------------------------
--  DDL for Type TYTABCABTXNGEN
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYTABCABTXNGEN" AS TABLE OF SCVENTASTIENDA.
                                                                  TYCABTXNGEN;

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTABCABTXNGEN" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTABCABTXNGEN" TO "SCACTUALIZADORVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTABCABTXNGEN" TO "USRACTVT";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTABCABTXNGEN" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTABCABTXNGEN" TO "USRINFSISGES";
