--------------------------------------------------------
--  DDL for Type TYTBPRODUCTO
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SCVENTASTIENDA"."TYTBPRODUCTO" IS TABLE OF SCVENTASTIENDA.TYOBPRODUCTO

/

  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPRODUCTO" TO "USRSISGES";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPRODUCTO" TO "USRVENTAST";
  GRANT EXECUTE ON "SCVENTASTIENDA"."TYTBPRODUCTO" TO "USRINFFENIX";
