ALTER SESSION SET CONTAINER = ORCLPDB1;

CREATE USER SCACTUALIZADORVT IDENTIFIED BY "SC4CTU4L1Z4D0RVT"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT UNLIMITED TABLESPACE TO SCACTUALIZADORVT;
GRANT RESOURCE TO SCACTUALIZADORVT;
-- GRANT CREATE SESSION TO SCACTUALIZADORVT;
-- revoke CONNECT from SCACTUALIZADORVT;
-- revoke CREATE SESSION from SCACTUALIZADORVT;

CREATE USER SCVENTASTIENDA IDENTIFIED BY "SCV3NT4ST13ND4"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT UNLIMITED TABLESPACE TO SCVENTASTIENDA;
GRANT RESOURCE TO SCVENTASTIENDA;
-- GRANT CREATE SESSION TO SCVENTASTIENDA;
-- revoke CONNECT from SCVENTASTIENDA;
-- revoke CREATE SESSION from SCVENTASTIENDA;

CREATE USER SCSISGES IDENTIFIED BY "SCS1SG3S"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

GRANT UNLIMITED TABLESPACE TO SCSISGES;
GRANT RESOURCE TO SCSISGES;
-- GRANT CREATE SESSION TO SCSISGES;
-- revoke CONNECT from  SCSISGES;
-- revoke CREATE SESSION from SCSISGES;

CREATE USER USRSISGES     IDENTIFIED BY "USRS1SG3S";
CREATE USER USRVENTAST    IDENTIFIED BY "USRV3NT4ST";
CREATE USER USRACTVT      IDENTIFIED BY "USR4CTVT";
CREATE USER USRINFSISGES  IDENTIFIED BY "USR1NFS1SG3S";
CREATE USER USRINFFENIX   IDENTIFIED BY "USR1NFF3N1X";
CREATE USER USRINFVENTAST IDENTIFIED BY "USR1NFV3NT4ST";
CREATE USER USRINFACTVT   IDENTIFIED BY "USR1NF4CTVT";
CREATE USER USRINFSASFNX IDENTIFIED BY "USRINFSASFNX";
CREATE USER USRINFSASFNXPRE IDENTIFIED BY "USRINFSASFNXPRE";

GRANT CREATE SESSION TO USRSISGES;
GRANT CREATE SESSION TO USRVENTAST;
GRANT CREATE SESSION TO USRACTVT;
GRANT CREATE SESSION TO USRINFSISGES;
GRANT CREATE SESSION TO USRINFFENIX;
GRANT CREATE SESSION TO USRINFVENTAST;
GRANT CREATE SESSION TO USRINFACTVT;
GRANT CREATE SESSION TO USRINFSASFNX;
GRANT CREATE SESSION TO USRINFSASFNXPRE;


--Se crea usuario para los SERVICE NAME que se solicitaron para transacciones del SENDER
--Usuario: USRSENDER 
	--Tipo de usuario: Aplicativo
	--Responsable: 683464
	--IP Desde donde se conecta: 
		--10.53.54.44
		--10.53.54.45
		--10.53.54.51

CREATE USER USRSENDER IDENTIFIED BY "USRS3ND3R";
GRANT CREATE SESSION TO USRSENDER;

GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.cenlineacred TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.crecteunicped TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.credlineacred TO USRSENDER;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.pedidos_credito TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacenctetienda TO USRSENDER;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.taclientes TO USRSENDER;
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredclientes TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredctectes TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredinves TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredito TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredvtatienda TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tadetpedidos TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tadetpreparam TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tamovpedidos TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tapedcifrasctrl TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tapedidos TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tapreparame TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tasolicitudes TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tatransac_error TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tatxnerror_tmp TO USRSENDER; 
GRANT SELECT, UPDATE, INSERT, DELETE ON SCVENTASTIENDA.tacredsolicitud TO USRSENDER; 
