--------------------------------------------------------
--  DDL for Procedure SPCONSULTAPROC
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "SCSISGES"."SPCONSULTAPROC" (
   pa_NombreProc    IN SCSISGES.TCCONTROLJOBS.FCNOMBREPROCESO%TYPE,
   pa_fiidproc      IN SCSISGES.TCCONTROLJOBS.FIIDPROC%TYPE,
   pa_Status        OUT SCSISGES.TCCONTROLJOBS.FISTATUSEJEC%TYPE)
IS
    CSL_N1  CONSTANT PLS_INTEGER := -1;
    CSL_0  CONSTANT PLS_INTEGER := 0;
   BEGIN
     IF pa_fiidproc=CSL_0 THEN
     SELECT TC.FISTATUSEJEC --estatus de ejecucion 0: no termina - 1: exito - 2: error
     INTO pa_Status
    FROM SCSISGES.TCCONTROLJOBS TC
    WHERE TC.FIIDPROC=(SELECT MAX(FIIDPROC)
                       FROM SCSISGES.TCCONTROLJOBS
                       WHERE TRIM(FCNOMBREPROCESO)=TRIM(pa_NombreProc)
                       AND  TRUNC(FDFECHA)=TRUNC(SYSDATE))
     AND TRUNC(TC.FDFECHA)=TRUNC(SYSDATE);
     ELSE
         SELECT TC.FISTATUSEJEC --estatus de ejecucion 0: no termina - 1: exito - 2: error
         INTO pa_Status
        FROM SCSISGES.TCCONTROLJOBS TC
        WHERE TC.FIIDPROC=pa_fiidproc
          AND TC.FDFECHA=TRUNC(SYSDATE);
     END IF;

EXCEPTION
   WHEN OTHERS
   THEN
      SELECT CSL_N1
      INTO pa_Status FROM DUAL;

END SPCONSULTAPROC;

/

  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "SCACTUALIZADORVT";
  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "SCVENTASTIENDA";
  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "USRACTVT";
  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "USRINFFENIX";
  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "USRSISGES";
  GRANT EXECUTE ON "SCSISGES"."SPCONSULTAPROC" TO "USRVENTAST";
