<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1539119289031" xmlns:tns="http://www.example.org/wsdl/1539119288878" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BannersResource" targetNamespace="http://www.example.org/wsdl/1539119288878">
  <wsdl:import namespace="http://www.example.org/schema/1539119289031"/>
  <wsdl:message name="operationRequest">
    <wsdl:part element="extns:operationRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationResponse">
    <wsdl:part element="extns:operationResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="BannersResource">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      <wsdl:output message="tns:operationResponse" name="operationOutput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
